-- Daten: je 6 neue, typisch schweizerische Einträge pro Kategorie (54 Einträge)
-- Einmal im Supabase-Dashboard unter «SQL Editor» ausführen.
-- Doppelte werden übersprungen: Gibt es den Namen (oder bei Pflanzen und Tieren den lateinischen Namen)
-- schon in irgendeiner Kategorie, auch ausgeblendet, wird die Zeile nicht eingefügt.
-- Die Datei lässt sich darum gefahrlos mehrmals ausführen.
-- Bilder: Noch keine eigenen. Die Seite sucht sie online (Wikipedia-Titelbild und Suchbegriffe),
-- bis in der Verwaltung eigene hochgeladen werden.

begin;

insert into public.entries (category_id, name, subtitle, description, facts, search_terms, wp, sort)
select n.cat, n.name, n.sub, n.descr, n.facts::jsonb, n.terms, n.wp,
       coalesce((select max(e.sort) from public.entries e where e.category_id = n.cat), -1) + n.nr
from (values

-- ---------------------------------------------------------------- Bäume
('baeume', 1, 'Edelkastanie', 'Castanea sativa',
 'Die Edelkastanie prägt die Wälder der Alpensüdseite, vor allem im Tessin und im Bergell. Früher nannte man sie dort «Brotbaum», denn die Marroni waren im Winter ein wichtiges Grundnahrungsmittel. Die Früchte stecken in einer stacheligen Hülle. Die langen Blätter sind am Rand grob gesägt.',
 '[{"k":"Höhe","v":"bis 30 m"},{"k":"Alter","v":"bis über 500 Jahre"},{"k":"Vorkommen","v":"Tessin, Bergell, Misox, Genferseegebiet"},{"k":"Merkmal","v":"stachelige Fruchthülle mit Marroni"}]',
 array['Castanea sativa leaves','Castanea sativa chestnuts burr','Castanea sativa bark'], null),
('baeume', 2, 'Winterlinde', 'Tilia cordata',
 'Die Winterlinde hat herzförmige Blätter mit kleinen rostbraunen Haarbüscheln auf der Unterseite. Im Juni und Juli duften ihre Blüten stark und locken viele Bienen an; daraus wird Lindenblütentee gemacht. Linden wurden früher gerne auf Dorfplätzen gepflanzt, wo man sich in ihrem Schatten traf.',
 '[{"k":"Höhe","v":"bis 30 m"},{"k":"Alter","v":"bis 1000 Jahre"},{"k":"Vorkommen","v":"Mittelland, Jura, tiefe Lagen"},{"k":"Merkmal","v":"herzförmige Blätter, Frucht mit Flügelblatt"}]',
 array['Tilia cordata leaves','Tilia cordata fruit bract','Tilia cordata bark'], null),
('baeume', 3, 'Hagebuche', 'Carpinus betulus',
 'Die Hagebuche ist trotz ihres Namens nicht mit der Buche verwandt, sondern mit der Birke. Ihr Holz ist sehr hart und wurde früher für Werkzeugstiele und Zahnräder verwendet. Weil sie sich gut schneiden lässt, pflanzt man sie oft als Hecke («Hag»). Ihr grauer Stamm wirkt wie mit Muskeln überzogen.',
 '[{"k":"Höhe","v":"bis 25 m"},{"k":"Alter","v":"bis 150 Jahre"},{"k":"Vorkommen","v":"Mittelland, Jura, bis ca. 1000 m"},{"k":"Merkmal","v":"gerillter, «muskulöser» Stamm"}]',
 array['Carpinus betulus leaves','Carpinus betulus fruit','Carpinus betulus bark'], null),
('baeume', 4, 'Hängebirke', 'Betula pendula',
 'Die Hängebirke erkennt man sofort an ihrer weissen Rinde mit schwarzen Rissen. Ihre dünnen Zweige hängen im Alter nach unten. Sie ist eine Pionierpflanze: Ihre leichten, geflügelten Samen fliegen weit, und sie wächst als einer der ersten Bäume auf Kahlflächen und Brachland.',
 '[{"k":"Höhe","v":"bis 30 m"},{"k":"Alter","v":"bis 120 Jahre"},{"k":"Vorkommen","v":"ganze Schweiz, bis ca. 2000 m"},{"k":"Merkmal","v":"weisse Rinde mit schwarzen Rissen"}]',
 array['Betula pendula leaves','Betula pendula catkins','Betula pendula bark'], null),
('baeume', 5, 'Vogelbeere', 'Sorbus aucuparia',
 'Die Vogelbeere, auch Eberesche genannt, wächst bis hoch in die Alpen hinauf. Ihre gefiederten Blätter erinnern an die Esche. Im Herbst leuchten die orangeroten Beeren, die bei Amseln und Drosseln sehr beliebt sind. Roh sind die Beeren bitter, gekocht werden sie zu Konfitüre verarbeitet.',
 '[{"k":"Höhe","v":"bis 15 m"},{"k":"Alter","v":"bis 100 Jahre"},{"k":"Vorkommen","v":"ganze Schweiz, bis ca. 2000 m"},{"k":"Merkmal","v":"orangerote Beerendolden"}]',
 array['Sorbus aucuparia leaves','Sorbus aucuparia berries','Sorbus aucuparia bark'], null),
('baeume', 6, 'Eibe', 'Taxus baccata',
 'Die Eibe ist ein langsam wachsender Nadelbaum, der auch im Schatten anderer Bäume gedeiht. Fast alle Teile sind stark giftig, nur der rote Samenmantel nicht. Ihr zähes, elastisches Holz wurde früher für Pfeilbogen verwendet. Eiben können über 1000 Jahre alt werden.',
 '[{"k":"Höhe","v":"bis 15 m"},{"k":"Alter","v":"über 1000 Jahre"},{"k":"Vorkommen","v":"Jura, Voralpen, oft an steilen Hängen"},{"k":"Merkmal","v":"giftig, roter Samenmantel"}]',
 array['Taxus baccata needles','Taxus baccata red arils','Taxus baccata bark'], null),

-- ---------------------------------------------------------------- Sträucher
('straeucher', 1, 'Berberitze', 'Berberis vulgaris',
 'Die Berberitze hat scharfe, meist dreiteilige Dornen und gelbes Holz. Im Mai hängen gelbe Blütentrauben an den Zweigen. Die länglichen, roten Beeren sind sehr sauer und reich an Vitamin C. Weil sie den Getreiderost überträgt, wurde sie früher in Ackerbaugebieten stark bekämpft.',
 '[{"k":"Höhe","v":"1–3 m"},{"k":"Blütezeit","v":"Mai–Juni"},{"k":"Früchte","v":"rote, saure Beeren"},{"k":"Merkmal","v":"dreiteilige Dornen, gelbes Holz"}]',
 array['Berberis vulgaris leaves thorns','Berberis vulgaris flowers','Berberis vulgaris berries'], null),
('straeucher', 2, 'Gemeiner Schneeball', 'Viburnum opulus',
 'Der Gemeine Schneeball wächst gern an feuchten Orten, etwa an Bachufern und in Auenwäldern. Seine flachen, weissen Blütenstände haben am Rand grosse Schaublüten, die Insekten anlocken. Im Herbst leuchten die glasig roten Beeren, und das Laub färbt sich weinrot. Die Beeren sind roh giftig.',
 '[{"k":"Höhe","v":"2–4 m"},{"k":"Blütezeit","v":"Mai–Juni"},{"k":"Früchte","v":"glänzend rote Beeren (roh giftig)"},{"k":"Merkmal","v":"gelappte, ahornähnliche Blätter"}]',
 array['Viburnum opulus leaves','Viburnum opulus flowers','Viburnum opulus berries'], null),
('straeucher', 3, 'Rote Heckenkirsche', 'Lonicera xylosteum',
 'Die Rote Heckenkirsche ist ein häufiger Strauch in Laubwäldern und Hecken. Ihre gelblich-weissen Blüten stehen immer zu zweit an einem Stiel. Daraus entstehen paarweise, glänzend rote Beeren, die für Menschen giftig sind. Sie ist eng mit dem Geissblatt verwandt.',
 '[{"k":"Höhe","v":"1–3 m"},{"k":"Blütezeit","v":"Mai–Juni"},{"k":"Früchte","v":"rote Doppelbeeren (giftig)"},{"k":"Merkmal","v":"Blüten und Beeren immer paarweise"}]',
 array['Lonicera xylosteum leaves','Lonicera xylosteum flowers','Lonicera xylosteum berries'], null),
('straeucher', 4, 'Seidelbast', 'Daphne mezereum',
 'Der Seidelbast blüht schon im März, oft wenn noch Schnee liegt. Die rosa bis purpurroten Blüten sitzen direkt am kahlen Zweig und duften stark. Die ganze Pflanze ist sehr giftig, besonders die roten Beeren und die Rinde. Er wächst in Laubwäldern und steigt bis über 2000 m hinauf.',
 '[{"k":"Höhe","v":"0.5–1.5 m"},{"k":"Blütezeit","v":"Februar–April"},{"k":"Früchte","v":"rote Beeren (sehr giftig)"},{"k":"Merkmal","v":"blüht vor dem Blattaustrieb"}]',
 array['Daphne mezereum leaves','Daphne mezereum flowers','Daphne mezereum berries'], null),
('straeucher', 5, 'Grünerle', 'Alnus viridis',
 'Die Grünerle bildet an steilen, feuchten Hängen der Alpen dichte Gebüsche. Ihre biegsamen Stämme legen sich unter der Schneelast flach auf den Boden und richten sich im Frühling wieder auf. Mit Hilfe von Bakterien an den Wurzeln bindet sie Stickstoff aus der Luft. Auf aufgegebenen Alpweiden breitet sie sich stark aus.',
 '[{"k":"Höhe","v":"1–3 m"},{"k":"Blütezeit","v":"Mai–Juni"},{"k":"Früchte","v":"kleine, holzige Zäpfchen"},{"k":"Merkmal","v":"biegsame, bogig wachsende Stämme"}]',
 array['Alnus viridis leaves','Alnus viridis catkins','Alnus viridis cones'], 'Alnus alnobetula'),
('straeucher', 6, 'Heidelbeere', 'Vaccinium myrtillus',
 'Die Heidelbeere ist ein niedriger Zwergstrauch mit kantigen, grünen Zweigen. Sie wächst in lichten Nadelwäldern und auf sauren Böden bis über die Waldgrenze. Die blauschwarzen Beeren reifen im Juli und August und färben Mund und Finger blau. Im Herbst färbt sich ihr Laub leuchtend rot.',
 '[{"k":"Höhe","v":"15–50 cm"},{"k":"Blütezeit","v":"April–Juni"},{"k":"Früchte","v":"blauschwarze Beeren (essbar)"},{"k":"Merkmal","v":"kantige, grüne Zweige"}]',
 array['Vaccinium myrtillus leaves','Vaccinium myrtillus flowers','Vaccinium myrtillus berries'], null),

-- ---------------------------------------------------------------- Alpenblumen
('alpenblumen', 1, 'Gelber Enzian', 'Gentiana lutea',
 'Der Gelbe Enzian ist mit bis zu 1.5 m die grösste Enzianart. Er blüht erst, wenn er etwa zehn Jahre alt ist. Aus seiner bitteren Wurzel wird Enzianschnaps gebrannt. Das Vieh lässt ihn wegen des bitteren Geschmacks stehen, darum fällt er auf Weiden besonders auf.',
 '[{"k":"Blütezeit","v":"Juni–August"},{"k":"Höhenlage","v":"1000–2500 m"},{"k":"Standort","v":"Alpweiden, Kalkböden"},{"k":"Merkmal","v":"gelbe Blüten in Stockwerken"}]',
 array['Gentiana lutea flower','Gentiana lutea leaves','Gentiana lutea meadow'], null),
('alpenblumen', 2, 'Arnika', 'Arnica montana',
 'Die Arnika hat leuchtend gelbe, etwas zerzauste Blütenköpfe und eine Blattrosette am Boden. Sie wächst nur auf mageren, sauren Böden und verschwindet, wenn Wiesen gedüngt werden. Aus ihren Blüten werden Salben gegen Prellungen und Verstauchungen hergestellt.',
 '[{"k":"Blütezeit","v":"Juni–August"},{"k":"Höhenlage","v":"1000–2800 m"},{"k":"Standort","v":"Magerwiesen, saure Böden"},{"k":"Merkmal","v":"gelbe, zerzauste Blütenköpfe"}]',
 array['Arnica montana flower','Arnica montana leaves rosette','Arnica montana meadow'], null),
('alpenblumen', 3, 'Schwarzes Kohlröschen', 'Gymnadenia rhellicani',
 'Das Schwarze Kohlröschen ist eine kleine Orchidee der Alpweiden. Seine dunkel purpurroten Blütenköpfchen duften stark nach Vanille und Schokolade. Wie alle Orchideen ist es in der Schweiz geschützt und darf nicht gepflückt werden.',
 '[{"k":"Blütezeit","v":"Juni–August"},{"k":"Höhenlage","v":"1500–2800 m"},{"k":"Standort","v":"Alpweiden, Magerrasen"},{"k":"Schutz","v":"geschützt (wie alle Orchideen)"}]',
 array['Nigritella rhellicani flower','Nigritella rhellicani plant','Nigritella alpine meadow'], null),
('alpenblumen', 4, 'Alpen-Aster', 'Aster alpinus',
 'Die Alpen-Aster trägt einzelne, grosse Blütenköpfe mit violetten Strahlenblüten und einer gelben Mitte. Sie wächst auf trockenen, sonnigen Kalkrasen und Felsen. Die ganze Pflanze ist behaart, das schützt sie vor dem Austrocknen.',
 '[{"k":"Blütezeit","v":"Juli–August"},{"k":"Höhenlage","v":"1500–3000 m"},{"k":"Standort","v":"sonnige Kalkrasen, Felsen"},{"k":"Merkmal","v":"violette Strahlen, gelbe Mitte"}]',
 array['Aster alpinus flower','Aster alpinus leaves','Aster alpinus rocks'], null),
('alpenblumen', 5, 'Gletscher-Hahnenfuss', 'Ranunculus glacialis',
 'Der Gletscher-Hahnenfuss gehört zu den am höchsten steigenden Blütenpflanzen der Alpen: Am Finsteraarhorn wurde er auf über 4200 m gefunden. Seine weissen Blüten färben sich nach der Bestäubung rosa bis rot. Er wächst auf Geröll und Moränen, wo der Schnee lange liegen bleibt.',
 '[{"k":"Blütezeit","v":"Juli–August"},{"k":"Höhenlage","v":"2300–4200 m"},{"k":"Standort","v":"Geröll, Moränen"},{"k":"Merkmal","v":"weisse Blüten werden rötlich"}]',
 array['Ranunculus glacialis flower','Ranunculus glacialis leaves','Ranunculus glacialis scree'], null),
('alpenblumen', 6, 'Stängelloses Leimkraut', 'Silene acaulis',
 'Das Stängellose Leimkraut bildet flache, dichte Polster, die mit vielen kleinen rosa Blüten übersät sind. Die Polsterform schützt vor Wind und Kälte und speichert Wärme. Ein Polster wächst sehr langsam und kann über 100 Jahre alt werden.',
 '[{"k":"Blütezeit","v":"Juni–August"},{"k":"Höhenlage","v":"2000–3500 m"},{"k":"Standort","v":"Felsen, Geröll"},{"k":"Merkmal","v":"dichte, rosa blühende Polster"}]',
 array['Silene acaulis flowers close-up','Silene acaulis cushion','Silene acaulis rocks'], null),

-- ---------------------------------------------------------------- Säugetiere
('saeugetiere', 1, 'Schneehase', 'Lepus timidus',
 'Der Schneehase lebt in den Alpen oberhalb der Waldgrenze. Im Winter wird sein Fell ganz weiss, nur die Ohrenspitzen bleiben schwarz. Seine breiten, stark behaarten Hinterpfoten wirken wie Schneeschuhe. Im Sommer ist er graubraun und gut getarnt.',
 '[{"k":"Länge","v":"45–60 cm"},{"k":"Gewicht","v":"2–3.5 kg"},{"k":"Nahrung","v":"Gräser, Kräuter, Zwergsträucher"},{"k":"Lebensraum","v":"Alpen, 1300–3000 m"}]',
 array['Lepus timidus head','Lepus timidus leveret','Lepus timidus winter white'], null),
('saeugetiere', 2, 'Hermelin', 'Mustela erminea',
 'Das Hermelin ist ein kleines, flinkes Raubtier aus der Familie der Marder. Im Winter ist es schneeweiss, die Schwanzspitze bleibt aber immer schwarz. Es jagt vor allem Wühlmäuse und folgt ihnen sogar in ihre Gänge. Darum ist es bei Bauern als Mäusejäger beliebt.',
 '[{"k":"Länge","v":"20–30 cm (ohne Schwanz)"},{"k":"Gewicht","v":"100–350 g"},{"k":"Nahrung","v":"Wühlmäuse, Mäuse"},{"k":"Lebensraum","v":"Wiesen, Alpweiden, Hecken"}]',
 array['Mustela erminea head','Mustela erminea young','Mustela erminea winter white'], null),
('saeugetiere', 3, 'Biber', 'Castor fiber',
 'Der Biber ist das grösste Nagetier Europas. Er fällt Bäume mit seinen scharfen Zähnen und baut Dämme und Burgen. Anfang des 19. Jahrhunderts war er in der Schweiz ausgerottet; ab 1956 wurde er wieder angesiedelt und lebt heute an vielen Flüssen und Seen. Mit seinen Dämmen schafft er Lebensraum für viele andere Tiere.',
 '[{"k":"Länge","v":"80–100 cm (ohne Kelle)"},{"k":"Gewicht","v":"20–30 kg"},{"k":"Nahrung","v":"Rinde, Zweige, Wasserpflanzen"},{"k":"Lebensraum","v":"Flüsse, Bäche, Seen"}]',
 array['Castor fiber head','Castor fiber kit young','Castor fiber snow'], null),
('saeugetiere', 4, 'Eichhörnchen', 'Sciurus vulgaris',
 'Das Eichhörnchen klettert geschickt in den Bäumen und nutzt seinen buschigen Schwanz zum Steuern und Balancieren. Seine Fellfarbe reicht von fuchsrot bis fast schwarz. Im Herbst versteckt es Nüsse und Samen im Boden; vergessene Verstecke helfen dem Wald, neue Bäume wachsen zu lassen. Es hält keinen Winterschlaf.',
 '[{"k":"Länge","v":"20–25 cm (ohne Schwanz)"},{"k":"Gewicht","v":"250–400 g"},{"k":"Nahrung","v":"Samen, Nüsse, Knospen, Pilze"},{"k":"Lebensraum","v":"Wälder, Parks, Gärten"}]',
 array['Sciurus vulgaris head','Sciurus vulgaris young','Sciurus vulgaris snow'], null),
('saeugetiere', 5, 'Wildschwein', 'Sus scrofa',
 'Das Wildschwein ist ein kräftiges Tier mit borstigem, dunklem Fell. Mit seiner Schnauze wühlt es im Boden nach Wurzeln, Würmern und Engerlingen und kann dabei Wiesen und Äcker stark beschädigen. Die Jungen heissen Frischlinge und haben helle Längsstreifen als Tarnung. In der Schweiz lebt es vor allem im Jura, im Mittelland und im Tessin.',
 '[{"k":"Schulterhöhe","v":"bis 1 m"},{"k":"Gewicht","v":"Keiler bis 150 kg"},{"k":"Nahrung","v":"Allesfresser"},{"k":"Lebensraum","v":"Wälder, Felder"}]',
 array['Sus scrofa head','Sus scrofa piglets','Sus scrofa snow'], null),
('saeugetiere', 6, 'Igel', 'Erinaceus europaeus',
 'Der Igel trägt auf dem Rücken rund 7000 Stacheln. Bei Gefahr rollt er sich zu einer stacheligen Kugel ein. Er ist nachts unterwegs und frisst Käfer, Würmer und Schnecken. Von November bis März hält er Winterschlaf in einem Nest aus Laub, zum Beispiel unter einer Hecke.',
 '[{"k":"Länge","v":"20–30 cm"},{"k":"Gewicht","v":"800–1500 g"},{"k":"Nahrung","v":"Käfer, Würmer, Schnecken"},{"k":"Lebensraum","v":"Gärten, Hecken, Waldränder"}]',
 array['Erinaceus europaeus face','Erinaceus europaeus hoglets','Erinaceus europaeus hibernation leaves'], null),

-- ---------------------------------------------------------------- Amphibien
('amphibien', 1, 'Teichfrosch', 'Pelophylax esculentus',
 'Der Teichfrosch ist grün mit dunklen Flecken und hat oft einen hellen Streifen auf dem Rücken. Er verbringt den Sommer am und im Wasser und sonnt sich gerne am Ufer. Die Männchen quaken im Mai und Juni laut im Chor und blasen dabei zwei Schallblasen an den Mundwinkeln auf.',
 '[{"k":"Grösse","v":"7–10 cm"},{"k":"Laichzeit","v":"Mai–Juni"},{"k":"Lebensraum","v":"Weiher, Teiche, Gräben"},{"k":"Merkmal","v":"zwei Schallblasen seitlich"}]',
 array['Pelophylax esculentus close-up','Pelophylax esculentus tadpole','Pelophylax esculentus pond'], 'Edible frog'),
('amphibien', 2, 'Springfrosch', 'Rana dalmatina',
 'Der Springfrosch hat auffallend lange Hinterbeine und kann bis zu zwei Meter weit springen. Er ist hellbraun und hat wie der Grasfrosch einen dunklen Fleck hinter dem Auge. In der Schweiz ist er selten und kommt nur in wenigen Regionen vor, zum Beispiel im Tessin und in der Region Genf. Er laicht schon sehr früh im Jahr.',
 '[{"k":"Grösse","v":"6–9 cm"},{"k":"Laichzeit","v":"Februar–März"},{"k":"Lebensraum","v":"lichte Laubwälder, Waldweiher"},{"k":"Gefährdung","v":"selten, gefährdet"}]',
 array['Rana dalmatina close-up','Rana dalmatina spawn','Rana dalmatina forest pond'], null),
('amphibien', 3, 'Kreuzkröte', 'Epidalea calamita',
 'Die Kreuzkröte erkennt man an einem hellgelben Streifen, der über die Mitte ihres Rückens läuft. Sie hüpft kaum, sondern rennt wie eine Maus. Ursprünglich lebte sie in Flussauen; heute findet man sie oft in Kiesgruben, wo sich nach Regen flache Tümpel bilden. Ihr Ruf ist sehr laut und weit zu hören.',
 '[{"k":"Grösse","v":"5–8 cm"},{"k":"Laichzeit","v":"April–August"},{"k":"Lebensraum","v":"Kiesgruben, flache Tümpel"},{"k":"Gefährdung","v":"stark gefährdet"}]',
 array['Epidalea calamita close-up','Epidalea calamita tadpoles','Epidalea calamita gravel pit'], null),
('amphibien', 4, 'Fadenmolch', 'Lissotriton helveticus',
 'Der Fadenmolch ist der kleinste Molch der Schweiz. Sein lateinischer Name bedeutet «schweizerisch», weil er zuerst in der Schweiz beschrieben wurde. Das Männchen hat zur Paarungszeit einen fadenförmigen Fortsatz am Schwanzende und Schwimmhäute an den Hinterfüssen. Er lebt in kleinen Waldweihern und Tümpeln.',
 '[{"k":"Grösse","v":"6–9 cm"},{"k":"Laichzeit","v":"März–Juni"},{"k":"Lebensraum","v":"Waldweiher, Tümpel"},{"k":"Merkmal","v":"«Faden» am Schwanzende"}]',
 array['Lissotriton helveticus male','Lissotriton helveticus larva','Lissotriton helveticus pond'], null),
('amphibien', 5, 'Teichmolch', 'Lissotriton vulgaris',
 'Der Teichmolch ist in Europa weit verbreitet, in der Schweiz aber selten. Die Männchen tragen im Frühling einen hohen, gewellten Rückenkamm und einen orangen Bauch mit dunklen Punkten. Nach der Paarungszeit verlassen die Molche das Wasser und leben versteckt an Land.',
 '[{"k":"Grösse","v":"7–11 cm"},{"k":"Laichzeit","v":"März–Juni"},{"k":"Lebensraum","v":"sonnige Weiher mit Pflanzen"},{"k":"Gefährdung","v":"stark gefährdet"}]',
 array['Lissotriton vulgaris male crest','Lissotriton vulgaris larva','Lissotriton vulgaris pond'], null),
('amphibien', 6, 'Italienischer Laubfrosch', 'Hyla intermedia',
 'Der Italienische Laubfrosch lebt in der Schweiz nur auf der Alpensüdseite, vor allem im Tessin. Er ist leuchtend grün und kann dank Haftscheiben an den Zehen auf Schilf und Sträucher klettern. Vom Laubfrosch nördlich der Alpen unterscheidet er sich vor allem durch seine Gene und seinen Ruf.',
 '[{"k":"Grösse","v":"3–5 cm"},{"k":"Laichzeit","v":"April–Juni"},{"k":"Lebensraum","v":"Weiher mit Büschen, Tessin"},{"k":"Merkmal","v":"Haftscheiben an den Zehen"}]',
 array['Hyla intermedia close-up','Hyla intermedia tadpole','Hyla intermedia pond'], null),

-- ---------------------------------------------------------------- Steine
('steine', 1, 'Dolomit', 'Sedimentgestein',
 'Dolomit ähnelt Kalkstein, enthält aber viel Magnesium. Er entstand vor über 200 Millionen Jahren in warmen, flachen Meeren. Dolomit zerfällt zu scharfkantigem Schutt und bildet oft schroffe, helle Felswände mit grossen Geröllhalden, etwa im Schweizerischen Nationalpark.',
 '[{"k":"Entstehung","v":"Ablagerung in flachen Meeren (Trias)"},{"k":"Vorkommen","v":"Engadin, Nationalpark, Monte San Giorgio"},{"k":"Verwendung","v":"Baustoff, Düngekalk"}]',
 array['dolomite rock texture','dolomite rock sample','Swiss National Park dolomite scree'], 'Dolomite (rock)'),
('steine', 2, 'Mergel', 'Sedimentgestein',
 'Mergel ist ein eher weiches Gestein aus einer Mischung von Kalk und Ton. Er verwittert leicht und bildet darum sanfte Hänge statt steiler Wände. Mergel ist ein wichtiger Rohstoff für die Herstellung von Zement. Im Jura und im Mittelland ist er weit verbreitet.',
 '[{"k":"Entstehung","v":"Ablagerung von Kalk- und Tonschlamm"},{"k":"Vorkommen","v":"Jura, Mittelland"},{"k":"Verwendung","v":"Zement"}]',
 array['marl texture','marl rock sample','marl outcrop'], 'Marl'),
('steine', 3, 'Gips', 'Sedimentgestein',
 'Gips entsteht, wenn salzhaltiges Meerwasser verdunstet. Er ist so weich, dass man ihn mit dem Fingernagel ritzen kann. Gebrannter und gemahlener Gips wird mit Wasser wieder fest; darum braucht man ihn für Verputz, Gipsplatten und Gipsverbände.',
 '[{"k":"Härte","v":"2 (mit dem Fingernagel ritzbar)"},{"k":"Vorkommen","v":"Alpen und Jura (Trias-Schichten)"},{"k":"Verwendung","v":"Verputz, Gipsplatten, Gipsverband"}]',
 array['gypsum crystals','gypsum rock sample','gypsum outcrop Alps'], 'Gypsum'),
('steine', 4, 'Steinsalz', 'Sedimentgestein',
 'Steinsalz besteht aus dem Mineral Halit, also aus Kochsalz. Es entstand vor rund 200 Millionen Jahren, als Meeresbecken austrockneten. In der Schweiz wird es in Bex (VD) im Bergwerk abgebaut und am Rhein bei Schweizerhalle und Riburg aus der Tiefe gewonnen: Man löst es mit Wasser und dampft die Sole ein.',
 '[{"k":"Entstehung","v":"Verdunstung von Meerwasser"},{"k":"Vorkommen","v":"Bex, Schweizerhalle, Riburg"},{"k":"Verwendung","v":"Speisesalz, Streusalz"}]',
 array['halite crystals','rock salt sample','Bex salt mine'], 'Halite'),
('steine', 5, 'Speckstein (Giltstein)', 'Metamorphes Gestein',
 'Speckstein ist sehr weich und fühlt sich seifig an. Er speichert Wärme lange und gibt sie langsam wieder ab. Darum baute man daraus im Wallis, in Graubünden und im Tessin Öfen, die Giltsteinöfen. Im Bergell wurden aus dem «Lavez» auch Kochtöpfe gedrechselt.',
 '[{"k":"Härte","v":"1–2 (sehr weich)"},{"k":"Vorkommen","v":"Wallis, Bergell, Tessin"},{"k":"Verwendung","v":"Öfen, Kochtöpfe, Bildhauerei"}]',
 array['soapstone texture','soapstone carving','soapstone stove'], 'Soapstone'),
('steine', 6, 'Flysch', 'Sedimentgestein',
 'Flysch ist eine Abfolge aus vielen dünnen Schichten von Sandstein, Mergel und Tonschiefer. Er entstand, als bei der Bildung der Alpen Schutt in ein tiefes Meer rutschte. Das Wort stammt aus dem Simmental und bedeutet etwa «fliessen», weil Flyschhänge leicht ins Rutschen geraten. Flysch bildet oft grüne, sanfte Voralpenhügel.',
 '[{"k":"Entstehung","v":"Schutt im Meer während der Alpenbildung"},{"k":"Vorkommen","v":"Voralpen, z. B. Gurnigel, Prättigau"},{"k":"Merkmal","v":"dünne Schichten, rutschige Hänge"}]',
 array['flysch layers','flysch outcrop','flysch Alps'], 'Flysch'),

-- ---------------------------------------------------------------- Gräser
('graeser', 1, 'Glatthafer', 'Arrhenatherum elatius',
 'Der Glatthafer, auch Französisches Raigras genannt, ist das typische Gras der gedüngten Heuwiesen im Mittelland. Er wird bis 1.5 m hoch und gibt den Glatthaferwiesen ihren Namen. Seine Ährchen tragen eine geknickte Granne. Er erträgt das Mähen gut, aber keine häufige Beweidung.',
 '[{"k":"Höhe","v":"50–150 cm"},{"k":"Blütezeit","v":"Juni–Juli"},{"k":"Lebensraum","v":"Fettwiesen im Mittelland"},{"k":"Merkmal","v":"Ährchen mit geknickter Granne"}]',
 array['Arrhenatherum elatius inflorescence','Arrhenatherum elatius spikelets','Arrhenatherum elatius meadow'], null),
('graeser', 2, 'Goldhafer', 'Trisetum flavescens',
 'Der Goldhafer hat lockere Rispen, die zur Blütezeit goldgelb glänzen. Er ist ein wertvolles Futtergras der Bergwiesen, die nach ihm Goldhaferwiesen heissen. Die kleinen Ährchen tragen feine, geknickte Grannen.',
 '[{"k":"Höhe","v":"30–80 cm"},{"k":"Blütezeit","v":"Juni–Juli"},{"k":"Lebensraum","v":"Bergwiesen bis ca. 2000 m"},{"k":"Merkmal","v":"goldglänzende Rispe"}]',
 array['Trisetum flavescens inflorescence','Trisetum flavescens spikelets','Trisetum flavescens meadow'], null),
('graeser', 3, 'Wiesen-Rispengras', 'Poa pratensis',
 'Das Wiesen-Rispengras bildet mit unterirdischen Ausläufern einen dichten Rasen. Darum ist es wichtig für Wiesen, Weiden und Sportrasen. Seine Blätter haben eine kahnförmige Spitze, typisch für alle Rispengräser.',
 '[{"k":"Höhe","v":"20–80 cm"},{"k":"Blütezeit","v":"Mai–Juli"},{"k":"Lebensraum","v":"Wiesen, Weiden, Rasen"},{"k":"Merkmal","v":"kahnförmige Blattspitze"}]',
 array['Poa pratensis inflorescence','Poa pratensis spikelets','Poa pratensis meadow'], null),
('graeser', 4, 'Borstgras', 'Nardus stricta',
 'Das Borstgras hat steife, borstenartige Blätter und eine dünne, einseitige Ähre. Es wächst auf mageren, sauren Alpweiden. Das Vieh frisst es nur ungern, deshalb breitet es sich auf überweideten Flächen aus. Solche Borstgrasweiden sind reich an Blumen wie der Arnika.',
 '[{"k":"Höhe","v":"10–30 cm"},{"k":"Blütezeit","v":"Mai–Juli"},{"k":"Lebensraum","v":"magere, saure Alpweiden"},{"k":"Merkmal","v":"borstige Blätter, einseitige Ähre"}]',
 array['Nardus stricta inflorescence','Nardus stricta spike','Nardus stricta alpine pasture'], null),
('graeser', 5, 'Blaugras', 'Sesleria caerulea',
 'Das Blaugras blüht schon im Frühling mit kleinen, blauviolett schimmernden Ähren. Es wächst an sonnigen Kalkhängen und auf Felsen im Jura und in den Alpen. Mit seinen dichten Horsten hält es den Boden an steilen Hängen fest.',
 '[{"k":"Höhe","v":"10–45 cm"},{"k":"Blütezeit","v":"März–Juni"},{"k":"Lebensraum","v":"Kalkfelsen, Kalkrasen"},{"k":"Merkmal","v":"blauviolette Ährenrispe"}]',
 array['Sesleria caerulea inflorescence','Sesleria caerulea spikelets','Sesleria caerulea limestone grassland'], null),
('graeser', 6, 'Pfeifengras', 'Molinia caerulea',
 'Das Pfeifengras wächst in Riedwiesen und Mooren mit wechselfeuchtem Boden. Seine Halme haben fast keine Knoten; früher reinigte man damit Tabakpfeifen. Im Herbst färbt es sich goldgelb bis orange. Riedwiesen mit Pfeifengras werden erst im Herbst gemäht, das Schnittgut dient als Einstreu im Stall.',
 '[{"k":"Höhe","v":"40–150 cm"},{"k":"Blütezeit","v":"Juli–September"},{"k":"Lebensraum","v":"Riedwiesen, Moore"},{"k":"Merkmal","v":"Halme fast ohne Knoten"}]',
 array['Molinia caerulea inflorescence','Molinia caerulea spikelets','Molinia caerulea autumn fen'], null),

-- ---------------------------------------------------------------- Insekten
('insekten', 1, 'Alpenbock', 'Rosalia alpina',
 'Der Alpenbock ist ein auffälliger Bockkäfer mit hellblauem Körper, schwarzen Flecken und sehr langen Fühlern. Seine Larven entwickeln sich mehrere Jahre lang im toten Holz von alten, besonnten Buchen. Weil solches Holz selten geworden ist, ist der Alpenbock gefährdet.',
 '[{"k":"Grösse","v":"15–38 mm"},{"k":"Nahrung","v":"Larve: totes Buchenholz"},{"k":"Entwicklung","v":"2–4 Jahre als Larve"},{"k":"Besonderes","v":"Fühler länger als der Körper"}]',
 array['Rosalia alpina macro','Rosalia alpina larva','Rosalia alpina beech wood'], null),
('insekten', 2, 'Hirschkäfer', 'Lucanus cervus',
 'Der Hirschkäfer ist der grösste Käfer der Schweiz. Die Männchen haben riesige, geweihartige Oberkiefer, mit denen sie um die Weibchen kämpfen. Die Larven leben bis zu sechs Jahre in morschem Eichenholz, die Käfer selbst nur wenige Wochen im Sommer.',
 '[{"k":"Grösse","v":"bis 8 cm (Männchen)"},{"k":"Nahrung","v":"Baumsaft"},{"k":"Entwicklung","v":"3–6 Jahre als Larve"},{"k":"Besonderes","v":"«Geweih» der Männchen"}]',
 array['Lucanus cervus male macro','Lucanus cervus larva','Lucanus cervus oak'], null),
('insekten', 3, 'Apollofalter', 'Parnassius apollo',
 'Der Apollofalter ist ein grosser, weisser Tagfalter mit schwarzen Flecken und roten Augenflecken auf den Hinterflügeln. Er fliegt an sonnigen, felsigen Hängen der Alpen und des Juras. Seine Raupe frisst fast nur an der Weissen Fetthenne. Er ist in der Schweiz geschützt.',
 '[{"k":"Spannweite","v":"65–85 mm"},{"k":"Raupenfutter","v":"Weisse Fetthenne"},{"k":"Flugzeit","v":"Juni–August"},{"k":"Besonderes","v":"rote Augenflecken"}]',
 array['Parnassius apollo macro','Parnassius apollo caterpillar','Parnassius apollo on flower'], null),
('insekten', 4, 'Zitronenfalter', 'Gonepteryx rhamni',
 'Der Zitronenfalter ist oft der erste Schmetterling im Jahr, manchmal schon an warmen Tagen im Februar. Er überwintert als Falter frei an Zweigen und übersteht dabei auch Frost. Die Männchen sind zitronengelb, die Weibchen blass grünlich-weiss. Die Raupen fressen an Faulbaum und Kreuzdorn.',
 '[{"k":"Spannweite","v":"50–60 mm"},{"k":"Raupenfutter","v":"Faulbaum, Kreuzdorn"},{"k":"Flugzeit","v":"Februar–Oktober"},{"k":"Besonderes","v":"überwintert als Falter"}]',
 array['Gonepteryx rhamni macro','Gonepteryx rhamni caterpillar','Gonepteryx rhamni on flower'], null),
('insekten', 5, 'Feldgrille', 'Gryllus campestris',
 'Die Feldgrille ist schwarz, glänzend und hat einen grossen, runden Kopf. Sie lebt in selbst gegrabenen Erdröhren auf sonnigen Wiesen. Im Mai und Juni zirpen die Männchen vor dem Eingang, indem sie die Flügel aneinander reiben. Bei Gefahr verschwinden sie blitzschnell in ihrer Röhre.',
 '[{"k":"Grösse","v":"20–26 mm"},{"k":"Nahrung","v":"Pflanzen, kleine Insekten"},{"k":"Lebensweise","v":"lebt in Erdröhren"},{"k":"Besonderes","v":"Zirpen im Frühsommer"}]',
 array['Gryllus campestris macro','Gryllus campestris nymph','Gryllus campestris burrow meadow'], null),
('insekten', 6, 'Hornisse', 'Vespa crabro',
 'Die Hornisse ist die grösste Wespe der Schweiz. Trotz ihres Rufs ist sie friedlich und sticht nur, wenn man ihr Nest bedroht; ihr Stich ist nicht gefährlicher als ein Wespenstich. Sie jagt viele andere Insekten. Ihr Nest aus Holzfasern baut sie in hohlen Bäumen oder Nistkästen.',
 '[{"k":"Grösse","v":"18–35 mm"},{"k":"Nahrung","v":"Insekten, Baumsaft, Obst"},{"k":"Lebensweise","v":"einjähriger Staat"},{"k":"Besonderes","v":"friedlich, jagt Insekten"}]',
 array['Vespa crabro macro','Vespa crabro nest larvae','Vespa crabro tree hollow'], null),

-- ---------------------------------------------------------------- Sehenswürdigkeiten
('sehenswuerdigkeiten', 1, 'Jungfraujoch', 'Berner Oberland / Wallis',
 'Das Jungfraujoch ist ein Bergsattel zwischen Mönch und Jungfrau. Seit 1912 fährt die Jungfraubahn durch einen Tunnel in Eiger und Mönch bis hierher; der Bahnhof ist der höchstgelegene Europas. Von der Sphinx-Terrasse blickt man auf den Grossen Aletschgletscher.',
 '[{"k":"Höhe","v":"3454 m (Bahnhof)"},{"k":"Baujahr","v":"Jungfraubahn 1912 eröffnet"},{"k":"Besonderes","v":"höchstgelegener Bahnhof Europas"}]',
 array['Jungfraujoch Sphinx Observatory','Jungfrau Railway train','Jungfraujoch glacier view'], 'Jungfraujoch'),
('sehenswuerdigkeiten', 2, 'Creux du Van', 'Neuenburger Jura',
 'Der Creux du Van ist ein riesiger Felsenkessel im Neuenburger Jura. Die senkrechten Kalkwände sind bis 160 m hoch und bilden einen Halbkreis von über einem Kilometer Breite. Mit etwas Glück sieht man hier Steinböcke und Gämsen.',
 '[{"k":"Höhe","v":"1463 m (Le Soliat)"},{"k":"Breite","v":"rund 1.4 km"},{"k":"Besonderes","v":"Steinböcke, Gämsen"}]',
 array['Creux du Van cliffs','Creux du Van ibex','Creux du Van fog'], 'Creux du Van'),
('sehenswuerdigkeiten', 3, 'Stiftsbezirk St. Gallen', 'St. Gallen',
 'Der Stiftsbezirk geht auf das Kloster zurück, das im 8. Jahrhundert beim Grab des heiligen Gallus gegründet wurde. Die barocke Stiftsbibliothek gilt als einer der schönsten Bibliothekssäle der Welt und bewahrt über 2000 mittelalterliche Handschriften. Seit 1983 gehört der Stiftsbezirk zum UNESCO-Welterbe.',
 '[{"k":"Erste Erwähnung","v":"Kloster 719 gegründet"},{"k":"UNESCO-Welterbe","v":"seit 1983"},{"k":"Besonderes","v":"Stiftsbibliothek"}]',
 array['Abbey library of Saint Gall','St. Gallen Cathedral interior','St. Gallen Stiftsbezirk night'], 'Abbey of Saint Gall'),
('sehenswuerdigkeiten', 4, 'Burgen von Bellinzona', 'Bellinzona, Tessin',
 'Die drei Burgen Castelgrande, Montebello und Sasso Corbaro bewachten im Mittelalter den Weg zu den Alpenpässen. Zusammen mit einer langen Mauer sperrten sie das ganze Tal ab. Seit 2000 gehören sie zum UNESCO-Welterbe.',
 '[{"k":"Baujahr","v":"13.–15. Jahrhundert"},{"k":"UNESCO-Welterbe","v":"seit 2000"},{"k":"Besonderes","v":"drei Burgen und Talsperre"}]',
 array['Castelgrande Bellinzona','Montebello castle Bellinzona','Sasso Corbaro castle'], 'Castles of Bellinzona'),
('sehenswuerdigkeiten', 5, 'Jet d''eau', 'Genf',
 'Der Jet d''eau ist eine riesige Wasserfontäne im Genfersee und das Wahrzeichen von Genf. Pumpen schleudern pro Sekunde 500 Liter Wasser mit rund 200 km/h bis 140 m hoch. Ursprünglich war die Fontäne ein Überdruckventil der städtischen Wasserversorgung.',
 '[{"k":"Höhe","v":"140 m"},{"k":"Baujahr","v":"1891 (heutige Form seit 1951)"},{"k":"Besonderes","v":"500 Liter Wasser pro Sekunde"}]',
 array['Jet d''Eau Geneva','Jet d''Eau rainbow','Jet d''Eau night'], 'Jet d''Eau'),
('sehenswuerdigkeiten', 6, 'Staubbachfall', 'Lauterbrunnen, Bern',
 'Der Staubbachfall stürzt fast 300 m über eine senkrechte Felswand ins Lauterbrunnental. Das Wasser fällt so tief, dass es sich unterwegs in feinen Sprühnebel auflöst, daher der Name. Goethe schrieb hier 1779 sein Gedicht «Gesang der Geister über den Wassern».',
 '[{"k":"Höhe","v":"297 m"},{"k":"Lage","v":"Lauterbrunnental"},{"k":"Besonderes","v":"Goethe-Gedicht von 1779"}]',
 array['Staubbach Falls Lauterbrunnen','Staubbach Falls close-up','Lauterbrunnen valley'], 'Staubbach Falls')

) as n(cat, nr, name, sub, descr, facts, terms, wp)
where exists (select 1 from public.categories c where c.id = n.cat)
  and not exists (
    select 1 from public.entries e
    where lower(e.name) = lower(n.name)
       or (n.cat not in ('steine', 'sehenswuerdigkeiten') and lower(e.subtitle) = lower(n.sub))
  );

commit;

-- Kontrolle: Anzahl Einträge pro Kategorie (bisher 9, jetzt 15; ausgeblendete zählen mit)
select category_id, count(*) from public.entries group by category_id order by category_id;
