-- Daten: 5 neue Kategorien (Vögel, Wiesenblumen, Reptilien, Falter, Pilze) mit je 15 Einträgen,
-- die 4 Tagfalter wechseln von «Insekten» zu «Falter», «Insekten» bekommt 4 neue Arten.
-- Einmal im Supabase-Dashboard unter «SQL Editor» ausführen.
-- Doppelte werden übersprungen (gleicher Name oder gleicher lateinischer Name in irgendeiner Kategorie,
-- auch ausgeblendet). Die Datei lässt sich gefahrlos mehrmals ausführen.
-- Bilder danach in der Verwaltung mit «Fehlende Bilder von Wikimedia übernehmen» holen.

begin;

-- ------------------------------------------------------------------ Kategorien
insert into public.categories (id, name, description, latin, labels, sort) values
  ('wiesenblumen', 'Wiesenblumen', 'Blumen der Wiesen und Weiden im Tiefland', true,
   array['Pflanze','Blüte','Blätter','Lebensraum'], 3),
  ('pilze', 'Pilze', 'Speise- und Giftpilze – essen nur nach der Pilzkontrolle', true,
   array['Pilz','Unterseite','Junger Pilz','Lebensraum'], 5),
  ('voegel', 'Vögel', 'Vom Bartgeier bis zum Rotkehlchen', true,
   array['Vogel','Porträt','Nest/Jungvogel','Lebensraum'], 7),
  ('reptilien', 'Reptilien', 'Eidechsen, Schlangen und eine Schildkröte', true,
   array['Tier','Nahaufnahme','Jungtier','Lebensraum'], 8),
  ('falter', 'Falter', 'Tagfalter und tagaktive Nachtfalter', true,
   array['Falter','Nahaufnahme','Raupe','Lebensraum'], 11)
on conflict (id) do nothing;

-- Reihenfolge: Pflanzen, Tiere, Steine, Orte (in der Verwaltung mit ↑↓ änderbar)
update public.categories set sort = s.sort
from (values ('baeume',0),('straeucher',1),('alpenblumen',2),('wiesenblumen',3),('graeser',4),('pilze',5),
             ('saeugetiere',6),('voegel',7),('reptilien',8),('amphibien',9),('insekten',10),('falter',11),
             ('steine',12),('sehenswuerdigkeiten',13)) as s(id, sort)
where categories.id = s.id;

-- ------------------------------------------------------------------ Tagfalter umziehen
update public.entries
   set category_id = 'falter',
       sort = case name when 'Schwalbenschwanz' then 0 when 'Tagpfauenauge' then 1
                        when 'Apollofalter' then 2 else 3 end
 where category_id = 'insekten'
   and name in ('Schwalbenschwanz', 'Tagpfauenauge', 'Apollofalter', 'Zitronenfalter');

update public.categories
   set cover_entry_id = (select id from public.entries where category_id = 'falter' and name = 'Schwalbenschwanz')
 where id = 'falter' and cover_entry_id is null;

update public.categories
   set description = 'Käfer, Bienen, Libellen und mehr',
       cover_entry_id = case
         when cover_entry_id in (select id from public.entries where category_id = 'falter')
         then (select id from public.entries where category_id = 'insekten' and name = 'Siebenpunkt-Marienkäfer')
         else cover_entry_id end
 where id = 'insekten';

-- ------------------------------------------------------------------ Einträge
insert into public.entries (category_id, name, subtitle, description, facts, search_terms, wp, sort)
select n.cat, n.name, n.sub, n.descr, n.facts::jsonb, n.terms, null,
       coalesce((select max(e.sort) from public.entries e where e.category_id = n.cat), -1) + n.nr
from (values

-- ---------------------------------------------------------------- Vögel
('voegel', 1, 'Bartgeier', 'Gypaetus barbatus',
 'Der Bartgeier ist mit fast 3 m Flügelspannweite einer der grössten Vögel der Alpen. Er frisst vor allem Knochen: Grosse Knochen lässt er aus der Luft auf Felsen fallen, bis sie zerbrechen. Anfang des 20. Jahrhunderts war er in den Alpen ausgerottet; seit 1991 werden in der Schweiz wieder junge Bartgeier ausgewildert.',
 '[{"k":"Grösse","v":"Spannweite bis 2.9 m"},{"k":"Nahrung","v":"Knochen, Aas"},{"k":"Lebensraum","v":"Hochgebirge"},{"k":"Besonderes","v":"seit 1991 wieder angesiedelt"}]',
 array['Gypaetus barbatus portrait','Gypaetus barbatus chick nest','Gypaetus barbatus Alps flight']),
('voegel', 2, 'Steinadler', 'Aquila chrysaetos',
 'Der Steinadler ist ein mächtiger Greifvogel der Alpen. Er jagt vor allem Murmeltiere und Schneehasen und frisst im Winter auch Aas. Sein grosses Nest, den Horst, baut er in Felswänden und benutzt ihn oft viele Jahre lang. In der Schweiz brüten rund 300 Paare.',
 '[{"k":"Grösse","v":"Spannweite bis 2.2 m"},{"k":"Nahrung","v":"Murmeltiere, Schneehasen, Aas"},{"k":"Lebensraum","v":"Alpen"},{"k":"Besonderes","v":"Horst in Felswänden"}]',
 array['Aquila chrysaetos portrait','Aquila chrysaetos chick nest','Aquila chrysaetos mountains']),
('voegel', 3, 'Alpendohle', 'Pyrrhocorax graculus',
 'Die Alpendohle ist schwarz mit gelbem Schnabel und roten Beinen. Sie ist eine geschickte Fliegerin und nutzt die Aufwinde an den Berggipfeln. Auf Gipfeln und bei Bergrestaurants bettelt sie oft um Essensreste. Sie brütet in Felsspalten bis über 3000 m.',
 '[{"k":"Grösse","v":"36–39 cm"},{"k":"Nahrung","v":"Insekten, Beeren, Essensreste"},{"k":"Lebensraum","v":"Hochgebirge"},{"k":"Besonderes","v":"gelber Schnabel, rote Beine"}]',
 array['Pyrrhocorax graculus portrait','Pyrrhocorax graculus juvenile','Pyrrhocorax graculus mountain summit']),
('voegel', 4, 'Alpenschneehuhn', 'Lagopus muta',
 'Das Alpenschneehuhn lebt oberhalb der Waldgrenze. Im Winter ist sein Gefieder schneeweiss, im Sommer graubraun gesprenkelt, so ist es das ganze Jahr gut getarnt. Auch die Füsse sind befiedert und wirken im Schnee wie Schneeschuhe. Bei grosser Kälte gräbt es sich in den Schnee ein.',
 '[{"k":"Grösse","v":"34–36 cm"},{"k":"Nahrung","v":"Knospen, Blätter, Beeren"},{"k":"Lebensraum","v":"Alpen, 1900–2800 m"},{"k":"Besonderes","v":"weisses Wintergefieder"}]',
 array['Lagopus muta portrait','Lagopus muta chick','Lagopus muta winter snow']),
('voegel', 5, 'Weissstorch', 'Ciconia ciconia',
 'Der Weissstorch baut sein grosses Nest auf Dächern, Kaminen und hohen Masten. Um 1950 brütete in der Schweiz kein einziges Paar mehr. Dank eines Wiederansiedlungsprojekts in Altreu (SO) gibt es heute wieder mehrere hundert Brutpaare. Im Herbst ziehen viele Störche nach Spanien oder Afrika.',
 '[{"k":"Grösse","v":"80–100 cm, Spannweite 2 m"},{"k":"Nahrung","v":"Mäuse, Frösche, Insekten, Würmer"},{"k":"Lebensraum","v":"Wiesen, Felder, Feuchtgebiete"},{"k":"Besonderes","v":"Zugvogel"}]',
 array['Ciconia ciconia portrait','Ciconia ciconia nest chicks','Ciconia ciconia meadow']),
('voegel', 6, 'Graureiher', 'Ardea cinerea',
 'Der Graureiher steht oft lange reglos am Ufer oder auf einer Wiese und lauert auf Beute. Blitzschnell stösst er dann mit dem spitzen Schnabel zu. Er frisst Fische, Frösche und viele Mäuse. Im Flug zieht er den Hals S-förmig ein.',
 '[{"k":"Grösse","v":"90–98 cm"},{"k":"Nahrung","v":"Fische, Frösche, Mäuse"},{"k":"Lebensraum","v":"Gewässer, Wiesen"},{"k":"Besonderes","v":"brütet in Kolonien auf Bäumen"}]',
 array['Ardea cinerea portrait','Ardea cinerea nest chicks','Ardea cinerea river']),
('voegel', 7, 'Buntspecht', 'Dendrocopos major',
 'Der Buntspecht ist der häufigste Specht der Schweiz. Mit seinem kräftigen Schnabel zimmert er Bruthöhlen in Baumstämme. Im Frühling trommelt er schnell auf trockene Äste, um sein Revier zu markieren. Typisch sind das schwarz-weisse Gefieder und der rote Unterschwanz.',
 '[{"k":"Grösse","v":"22–23 cm"},{"k":"Nahrung","v":"Insekten, Samen, Nüsse"},{"k":"Lebensraum","v":"Wälder, Parks"},{"k":"Besonderes","v":"trommelt auf Äste"}]',
 array['Dendrocopos major portrait','Dendrocopos major nest hole juvenile','Dendrocopos major tree trunk']),
('voegel', 8, 'Amsel', 'Turdus merula',
 'Die Amsel ist einer der häufigsten Vögel der Schweiz. Das Männchen ist schwarz mit orangem Schnabel, das Weibchen dunkelbraun. Schon im Februar singt das Männchen in der Dämmerung sein flötendes Lied. Auf dem Rasen sucht die Amsel nach Regenwürmern.',
 '[{"k":"Grösse","v":"24–25 cm"},{"k":"Nahrung","v":"Würmer, Insekten, Beeren"},{"k":"Lebensraum","v":"Gärten, Wälder, Parks"},{"k":"Besonderes","v":"flötender Gesang"}]',
 array['Turdus merula male portrait','Turdus merula nest chicks','Turdus merula lawn']),
('voegel', 9, 'Rotkehlchen', 'Erithacus rubecula',
 'Das Rotkehlchen hat eine orangerote Brust und Kehle. Es ist wenig scheu und folgt Gärtnern oft, um Würmer aus der umgegrabenen Erde zu picken. Anders als die meisten Vögel singt es auch im Herbst und Winter. Männchen und Weibchen sehen gleich aus.',
 '[{"k":"Grösse","v":"13–14 cm"},{"k":"Nahrung","v":"Insekten, Würmer, Beeren"},{"k":"Lebensraum","v":"Wälder, Gärten"},{"k":"Besonderes","v":"singt auch im Winter"}]',
 array['Erithacus rubecula portrait','Erithacus rubecula juvenile','Erithacus rubecula garden']),
('voegel', 10, 'Schleiereule', 'Tyto alba',
 'Die Schleiereule hat einen herzförmigen, hellen Gesichtsschleier, der den Schall wie eine Schüssel zu den Ohren leitet. So findet sie Mäuse sogar in völliger Dunkelheit. Sie brütet gern in Scheunen und Kirchtürmen. In schneereichen Wintern verhungern viele Schleiereulen, weil sie keine Mäuse finden.',
 '[{"k":"Grösse","v":"33–35 cm"},{"k":"Nahrung","v":"Mäuse"},{"k":"Lebensraum","v":"Bauernland, Dörfer"},{"k":"Besonderes","v":"fliegt fast lautlos"}]',
 array['Tyto alba portrait','Tyto alba owlets','Tyto alba barn']),
('voegel', 11, 'Mauersegler', 'Apus apus',
 'Der Mauersegler verbringt fast sein ganzes Leben in der Luft: Er frisst, trinkt und schläft sogar im Flug. Er ist nur von Mai bis Anfang August in der Schweiz und brütet in Mauerlöchern und unter Dächern. In Gruppen jagen die Mauersegler mit schrillen Rufen um die Häuser.',
 '[{"k":"Grösse","v":"16–17 cm, Spannweite 40 cm"},{"k":"Nahrung","v":"Fluginsekten"},{"k":"Lebensraum","v":"Städte, Dörfer"},{"k":"Besonderes","v":"landet fast nie"}]',
 array['Apus apus portrait','Apus apus nest chicks','Apus apus flying town']),
('voegel', 12, 'Haussperling', 'Passer domesticus',
 'Der Haussperling oder Spatz lebt seit Jahrtausenden in der Nähe des Menschen. Das Männchen hat einen grauen Scheitel und einen schwarzen Kehlfleck, das Weibchen ist schlicht graubraun. Spatzen baden gern im Staub und brüten in Nischen an Gebäuden. Weil es immer weniger solche Nischen gibt, gehen die Bestände zurück.',
 '[{"k":"Grösse","v":"14–16 cm"},{"k":"Nahrung","v":"Samen, Insekten, Essensreste"},{"k":"Lebensraum","v":"Siedlungen, Bauernhöfe"},{"k":"Besonderes","v":"nimmt Staubbäder"}]',
 array['Passer domesticus male portrait','Passer domesticus nest chicks','Passer domesticus dust bath']),
('voegel', 13, 'Kohlmeise', 'Parus major',
 'Die Kohlmeise ist die grösste und häufigste Meise der Schweiz. Sie hat einen gelben Bauch mit einem schwarzen Längsstreifen und weisse Wangen. Gerne brütet sie in Nistkästen. Im Winter kommt sie oft ans Futterhäuschen.',
 '[{"k":"Grösse","v":"14 cm"},{"k":"Nahrung","v":"Insekten, Samen"},{"k":"Lebensraum","v":"Wälder, Gärten, Parks"},{"k":"Besonderes","v":"schwarzer Streifen am Bauch"}]',
 array['Parus major portrait','Parus major nest box chicks','Parus major winter feeder']),
('voegel', 14, 'Haubentaucher', 'Podiceps cristatus',
 'Der Haubentaucher lebt auf den Seen des Mittellandes. Zur Brutzeit trägt er eine dunkle Federhaube und einen rotbraunen Kragen. Die Paare führen im Frühling einen eindrucksvollen Balztanz auf dem Wasser auf. Die Küken reiten oft auf dem Rücken der Eltern.',
 '[{"k":"Grösse","v":"46–51 cm"},{"k":"Nahrung","v":"Fische"},{"k":"Lebensraum","v":"Seen"},{"k":"Besonderes","v":"Küken reiten auf dem Rücken"}]',
 array['Podiceps cristatus portrait','Podiceps cristatus chicks back','Podiceps cristatus lake']),
('voegel', 15, 'Tannenhäher', 'Nucifraga caryocatactes',
 'Der Tannenhäher ist der «Gärtner» des Arvenwaldes. Im Herbst versteckt er Tausende von Arvennüssen im Boden als Wintervorrat. Die meisten findet er dank seines guten Gedächtnisses wieder, aus den vergessenen wachsen neue Arven. Sein Gefieder ist dunkelbraun mit weissen Tupfen.',
 '[{"k":"Grösse","v":"32–35 cm"},{"k":"Nahrung","v":"Arven- und Haselnüsse, Insekten"},{"k":"Lebensraum","v":"Bergwälder"},{"k":"Besonderes","v":"verbreitet die Arve"}]',
 array['Nucifraga caryocatactes portrait','Nucifraga caryocatactes juvenile','Nucifraga caryocatactes Pinus cembra']),

-- ---------------------------------------------------------------- Wiesenblumen
('wiesenblumen', 1, 'Margerite', 'Leucanthemum vulgare',
 'Die Margerite ist eine der bekanntesten Wiesenblumen. Was wie eine einzige Blüte aussieht, ist ein Körbchen aus vielen kleinen Blüten: aussen weisse Zungenblüten, innen gelbe Röhrenblüten. Sie wächst in nicht zu stark gedüngten Wiesen und an Wegrändern.',
 '[{"k":"Blütezeit","v":"Mai–September"},{"k":"Höhe","v":"30–60 cm"},{"k":"Standort","v":"Magerwiesen, Wegränder"},{"k":"Merkmal","v":"weisse Strahlen, gelbe Mitte"}]',
 array['Leucanthemum vulgare flower','Leucanthemum vulgare leaves','Leucanthemum vulgare meadow']),
('wiesenblumen', 2, 'Wiesen-Salbei', 'Salvia pratensis',
 'Der Wiesen-Salbei hat leuchtend blauviolette Lippenblüten. Er hat einen raffinierten Hebel: Kriecht eine Hummel in die Blüte, klappen die Staubblätter herunter und pudern ihren Rücken mit Pollen ein. Er wächst auf trockenen, sonnigen Wiesen.',
 '[{"k":"Blütezeit","v":"Mai–August"},{"k":"Höhe","v":"30–60 cm"},{"k":"Standort","v":"trockene, magere Wiesen"},{"k":"Merkmal","v":"Hebel für Bestäuber"}]',
 array['Salvia pratensis flower','Salvia pratensis leaves','Salvia pratensis meadow']),
('wiesenblumen', 3, 'Wiesen-Glockenblume', 'Campanula patula',
 'Die Wiesen-Glockenblume trägt weit geöffnete, violette Glocken an dünnen, verzweigten Stängeln. Ihr lateinischer Name «patula» bedeutet «ausgebreitet», weil die Glocken so weit offen stehen. Sie wächst in Fettwiesen und an Böschungen.',
 '[{"k":"Blütezeit","v":"Mai–Juli"},{"k":"Höhe","v":"20–60 cm"},{"k":"Standort","v":"Fettwiesen, Böschungen"},{"k":"Merkmal","v":"weit offene, violette Glocken"}]',
 array['Campanula patula flower','Campanula patula leaves','Campanula patula meadow']),
('wiesenblumen', 4, 'Kuckucks-Lichtnelke', 'Silene flos-cuculi',
 'Die Kuckucks-Lichtnelke hat rosa Blüten mit tief zerschlitzten, fransigen Kronblättern. Sie blüht etwa dann, wenn der Kuckuck ruft, daher ihr Name. Sie wächst auf feuchten Wiesen und in Riedwiesen und wird seltener, wenn Wiesen entwässert werden.',
 '[{"k":"Blütezeit","v":"Mai–Juli"},{"k":"Höhe","v":"30–80 cm"},{"k":"Standort","v":"feuchte Wiesen, Riedwiesen"},{"k":"Merkmal","v":"zerschlitzte, rosa Kronblätter"}]',
 array['Silene flos-cuculi flower','Silene flos-cuculi leaves','Silene flos-cuculi wet meadow']),
('wiesenblumen', 5, 'Wiesen-Bocksbart', 'Tragopogon pratensis',
 'Der Wiesen-Bocksbart hat gelbe Blütenkörbe, die sich nur am Vormittag öffnen und gegen Mittag wieder schliessen. Nach der Blüte bildet er grosse, kugelige Samenstände, ähnlich wie der Löwenzahn, aber viel grösser. Seine Blätter sind lang und schmal wie Grasblätter.',
 '[{"k":"Blütezeit","v":"Mai–Juli"},{"k":"Höhe","v":"30–70 cm"},{"k":"Standort","v":"Fettwiesen"},{"k":"Merkmal","v":"Blüten nur am Vormittag offen"}]',
 array['Tragopogon pratensis flower','Tragopogon pratensis seed head','Tragopogon pratensis meadow']),
('wiesenblumen', 6, 'Zottiger Klappertopf', 'Rhinanthus alectorolophus',
 'Der Klappertopf ist ein Halbschmarotzer: Er hat grüne Blätter, zapft aber zusätzlich die Wurzeln von Gräsern an. Dadurch wachsen die Gräser weniger stark, und andere Blumen haben mehr Platz. Die reifen Samen klappern in der aufgeblasenen Kapsel, daher der Name.',
 '[{"k":"Blütezeit","v":"Mai–August"},{"k":"Höhe","v":"20–60 cm"},{"k":"Standort","v":"Wiesen, Weiden"},{"k":"Merkmal","v":"gelbe Blüten, Samen klappern"}]',
 array['Rhinanthus alectorolophus flower','Rhinanthus alectorolophus leaves','Rhinanthus alectorolophus meadow']),
('wiesenblumen', 7, 'Wiesen-Flockenblume', 'Centaurea jacea',
 'Die Wiesen-Flockenblume hat purpurrote Blütenkörbe, deren äussere Blüten grösser sind und wie Fransen abstehen. Sie ist bei Schmetterlingen, Bienen und Hummeln sehr beliebt. Man findet sie in mageren Wiesen und an Wegrändern bis in den Herbst.',
 '[{"k":"Blütezeit","v":"Juni–Oktober"},{"k":"Höhe","v":"30–80 cm"},{"k":"Standort","v":"Magerwiesen, Wegränder"},{"k":"Merkmal","v":"purpurrote, fransige Köpfe"}]',
 array['Centaurea jacea flower','Centaurea jacea leaves','Centaurea jacea meadow']),
('wiesenblumen', 8, 'Rot-Klee', 'Trifolium pratense',
 'Der Rot-Klee hat kugelige, rosarote Blütenköpfe und dreiteilige Blätter mit einem hellen Fleck. Wie alle Kleearten bindet er mit Hilfe von Bakterien an den Wurzeln Stickstoff aus der Luft und düngt so den Boden. Er ist ein wichtiges Futter für Kühe und wird darum auch angesät.',
 '[{"k":"Blütezeit","v":"Mai–September"},{"k":"Höhe","v":"15–50 cm"},{"k":"Standort","v":"Wiesen, Weiden"},{"k":"Merkmal","v":"Blätter mit hellem Fleck"}]',
 array['Trifolium pratense flower','Trifolium pratense leaves','Trifolium pratense meadow']),
('wiesenblumen', 9, 'Gewöhnlicher Hornklee', 'Lotus corniculatus',
 'Der Hornklee hat gelbe Schmetterlingsblüten, die oft rot überlaufen sind. Seine Früchte sind lange, dünne Hülsen, die wie Vogelkrallen abstehen. Er ist eine wichtige Futterpflanze für die Raupen vieler Bläulinge.',
 '[{"k":"Blütezeit","v":"Mai–September"},{"k":"Höhe","v":"10–30 cm"},{"k":"Standort","v":"magere Wiesen, Böschungen"},{"k":"Merkmal","v":"Hülsen wie Vogelkrallen"}]',
 array['Lotus corniculatus flower','Lotus corniculatus leaves','Lotus corniculatus meadow']),
('wiesenblumen', 10, 'Acker-Witwenblume', 'Knautia arvensis',
 'Die Acker-Witwenblume hat flache, lila Blütenköpfe, die wie kleine Nadelkissen aussehen. Trotz ihres Namens wächst sie meist in Wiesen und an Wegrändern. Viele Wildbienen, Schmetterlinge und Käfer besuchen ihre Blüten.',
 '[{"k":"Blütezeit","v":"Juni–September"},{"k":"Höhe","v":"30–80 cm"},{"k":"Standort","v":"Wiesen, Wegränder"},{"k":"Merkmal","v":"lila «Nadelkissen»"}]',
 array['Knautia arvensis flower','Knautia arvensis leaves','Knautia arvensis meadow']),
('wiesenblumen', 11, 'Scharfer Hahnenfuss', 'Ranunculus acris',
 'Der Scharfe Hahnenfuss färbt im Frühling ganze Wiesen gelb. Seine Blüten glänzen, als wären sie lackiert. Frisch ist die Pflanze giftig und wird vom Vieh gemieden; im Heu ist sie harmlos, weil das Gift beim Trocknen zerfällt.',
 '[{"k":"Blütezeit","v":"April–September"},{"k":"Höhe","v":"30–100 cm"},{"k":"Standort","v":"Fettwiesen, Weiden"},{"k":"Merkmal","v":"glänzend gelb, frisch giftig"}]',
 array['Ranunculus acris flower','Ranunculus acris leaves','Ranunculus acris meadow']),
('wiesenblumen', 12, 'Löwenzahn', 'Taraxacum officinale',
 'Der Löwenzahn ist eine der häufigsten Pflanzen der Schweiz. Aus den gelben Blütenkörben entstehen die bekannten «Pusteblumen»: Ihre Samen fliegen an kleinen Schirmen mit dem Wind davon. Die gezähnten Blätter gaben ihm den Namen. Junge Blätter kann man als Salat essen.',
 '[{"k":"Blütezeit","v":"April–Juni"},{"k":"Höhe","v":"10–40 cm"},{"k":"Standort","v":"Fettwiesen, Wegränder"},{"k":"Merkmal","v":"Pusteblume"}]',
 array['Taraxacum officinale flower','Taraxacum officinale leaves','Taraxacum officinale seed head']),
('wiesenblumen', 13, 'Wiesen-Schaumkraut', 'Cardamine pratensis',
 'Das Wiesen-Schaumkraut färbt feuchte Wiesen im April und Mai zartlila. Es ist die wichtigste Futterpflanze für die Raupen des Aurorafalters. Der Name kommt vom Schaum der Schaumzikaden-Larven, der oft an seinen Stängeln hängt.',
 '[{"k":"Blütezeit","v":"April–Juni"},{"k":"Höhe","v":"15–50 cm"},{"k":"Standort","v":"feuchte Wiesen"},{"k":"Merkmal","v":"zartlila Blüten"}]',
 array['Cardamine pratensis flower','Cardamine pratensis leaves','Cardamine pratensis wet meadow']),
('wiesenblumen', 14, 'Gewöhnliche Schafgarbe', 'Achillea millefolium',
 'Die Schafgarbe hat flache, weisse bis rosa Blütenschirme aus vielen kleinen Körbchen. Ihre Blätter sind fein gefiedert: «millefolium» bedeutet «tausend Blätter». Sie ist eine alte Heilpflanze und wird als Tee gegen Bauchweh verwendet.',
 '[{"k":"Blütezeit","v":"Juni–Oktober"},{"k":"Höhe","v":"20–60 cm"},{"k":"Standort","v":"Wiesen, Wegränder"},{"k":"Merkmal","v":"fein gefiederte Blätter"}]',
 array['Achillea millefolium flower','Achillea millefolium leaves','Achillea millefolium meadow']),
('wiesenblumen', 15, 'Herbstzeitlose', 'Colchicum autumnale',
 'Die Herbstzeitlose blüht im Herbst mit zartlila Blüten, aber ohne Blätter. Die Blätter und die Samenkapsel erscheinen erst im folgenden Frühling. Die ganze Pflanze ist sehr giftig; ihre Blätter werden manchmal mit Bärlauch verwechselt, was lebensgefährlich sein kann.',
 '[{"k":"Blütezeit","v":"August–Oktober"},{"k":"Höhe","v":"10–30 cm"},{"k":"Standort","v":"feuchte Wiesen"},{"k":"Merkmal","v":"sehr giftig"}]',
 array['Colchicum autumnale flower','Colchicum autumnale leaves spring','Colchicum autumnale meadow autumn']),

-- ---------------------------------------------------------------- Reptilien
('reptilien', 1, 'Zauneidechse', 'Lacerta agilis',
 'Die Zauneidechse ist kräftig gebaut. Zur Paarungszeit im Frühling leuchten die Flanken der Männchen grün. Sie sonnt sich gerne an Böschungen, Bahndämmen und Hecken. Bei Gefahr kann sie ihren Schwanz abwerfen, der danach kürzer nachwächst.',
 '[{"k":"Grösse","v":"bis 24 cm"},{"k":"Nahrung","v":"Insekten, Spinnen"},{"k":"Lebensraum","v":"Böschungen, Hecken, Bahndämme"},{"k":"Merkmal","v":"grüne Flanken (Männchen)"}]',
 array['Lacerta agilis close-up','Lacerta agilis juvenile','Lacerta agilis habitat']),
('reptilien', 2, 'Mauereidechse', 'Podarcis muralis',
 'Die Mauereidechse ist schlank und sehr flink. Sie klettert geschickt an Mauern, Felsen und Hauswänden und nutzt jede Ritze als Versteck. In der Südschweiz, im Wallis und am Jurasüdfuss ist sie häufig und lebt auch mitten in Städten.',
 '[{"k":"Grösse","v":"bis 20 cm"},{"k":"Nahrung","v":"Insekten, Spinnen"},{"k":"Lebensraum","v":"Mauern, Felsen, Bahnareale"},{"k":"Merkmal","v":"klettert an senkrechten Wänden"}]',
 array['Podarcis muralis close-up','Podarcis muralis juvenile','Podarcis muralis wall']),
('reptilien', 3, 'Waldeidechse', 'Zootoca vivipara',
 'Die Waldeidechse steigt höher hinauf als alle anderen Reptilien der Schweiz, bis fast 3000 m. Sie legt keine Eier, sondern bringt lebende Junge zur Welt; so müssen die Eier nicht im kühlen Boden reifen. Sie lebt in Mooren, lichten Wäldern und auf Alpweiden.',
 '[{"k":"Grösse","v":"bis 18 cm"},{"k":"Nahrung","v":"Insekten, Spinnen"},{"k":"Lebensraum","v":"Moore, Wälder, Alpweiden"},{"k":"Merkmal","v":"bringt lebende Junge zur Welt"}]',
 array['Zootoca vivipara close-up','Zootoca vivipara juvenile','Zootoca vivipara bog']),
('reptilien', 4, 'Westliche Smaragdeidechse', 'Lacerta bilineata',
 'Die Smaragdeidechse ist die grösste Eidechse der Schweiz. Die Männchen sind leuchtend grün und haben zur Paarungszeit eine blaue Kehle. Sie liebt die Wärme und lebt an sonnigen Hängen, vor allem im Tessin, im Wallis und in der Region Genf.',
 '[{"k":"Grösse","v":"bis 40 cm"},{"k":"Nahrung","v":"Insekten, Spinnen, Schnecken"},{"k":"Lebensraum","v":"sonnige Hänge mit Gebüsch"},{"k":"Merkmal","v":"blaue Kehle (Männchen)"}]',
 array['Lacerta bilineata close-up','Lacerta bilineata juvenile','Lacerta bilineata habitat']),
('reptilien', 5, 'Blindschleiche', 'Anguis fragilis',
 'Die Blindschleiche sieht aus wie eine Schlange, ist aber eine Eidechse ohne Beine. Anders als Schlangen kann sie die Augenlider schliessen und ihren Schwanz abwerfen. Sie ist nicht blind und völlig harmlos. Im Garten frisst sie gerne Nacktschnecken.',
 '[{"k":"Grösse","v":"bis 50 cm"},{"k":"Nahrung","v":"Nacktschnecken, Würmer"},{"k":"Lebensraum","v":"Gärten, Waldränder, Wiesen"},{"k":"Merkmal","v":"Eidechse ohne Beine"}]',
 array['Anguis fragilis close-up','Anguis fragilis juvenile','Anguis fragilis garden']),
('reptilien', 6, 'Barren-Ringelnatter', 'Natrix helvetica',
 'Die Barren-Ringelnatter lebt in der West- und Zentralschweiz. Sie schwimmt sehr gut und jagt vor allem Frösche und Kröten. Typisch sind die dunklen Querbarren an den Flanken. Bei Gefahr stellt sie sich tot oder sondert eine stinkende Flüssigkeit ab; sie ist ungiftig.',
 '[{"k":"Grösse","v":"bis 1.2 m"},{"k":"Nahrung","v":"Frösche, Kröten, Fische"},{"k":"Lebensraum","v":"Gewässer, Feuchtgebiete"},{"k":"Merkmal","v":"ungiftig, Querbarren an den Flanken"}]',
 array['Natrix helvetica close-up','Natrix helvetica juvenile','Natrix helvetica pond']),
('reptilien', 7, 'Östliche Ringelnatter', 'Natrix natrix',
 'Die Östliche Ringelnatter sieht der Barren-Ringelnatter sehr ähnlich. Erst seit 2017 gelten die beiden als getrennte Arten; sie unterscheiden sich vor allem in der Zeichnung und in ihren Genen. In der Schweiz lebt die Östliche Ringelnatter nur im Osten des Landes. Sie ist ungiftig und jagt vor allem Amphibien.',
 '[{"k":"Grösse","v":"bis 1.2 m"},{"k":"Nahrung","v":"Frösche, Kröten, Molche"},{"k":"Lebensraum","v":"Gewässer, Feuchtgebiete"},{"k":"Merkmal","v":"ungiftig, gelbe Nackenflecken"}]',
 array['Natrix natrix close-up','Natrix natrix juvenile','Natrix natrix pond']),
('reptilien', 8, 'Würfelnatter', 'Natrix tessellata',
 'Die Würfelnatter lebt fast nur im Wasser und jagt dort kleine Fische. Ihr Name kommt von den dunklen, würfelartigen Flecken auf dem Rücken. In der Schweiz kommt sie im Tessin und am Genfersee vor und ist stark gefährdet. Sie ist ungiftig.',
 '[{"k":"Grösse","v":"bis 1 m"},{"k":"Nahrung","v":"Fische"},{"k":"Lebensraum","v":"Seeufer, Flüsse"},{"k":"Merkmal","v":"ungiftig, würfelartige Flecken"}]',
 array['Natrix tessellata close-up','Natrix tessellata juvenile','Natrix tessellata lake shore']),
('reptilien', 9, 'Vipernatter', 'Natrix maura',
 'Die Vipernatter hat eine Zickzack-Zeichnung auf dem Rücken, ähnlich wie eine Viper, daher ihr Name. Sie ist aber ungiftig und harmlos. Sie lebt an Gewässern und frisst Fische und Frösche. In der Schweiz kommt sie nur im Wallis und in der Region Genf vor.',
 '[{"k":"Grösse","v":"bis 90 cm"},{"k":"Nahrung","v":"Fische, Frösche"},{"k":"Lebensraum","v":"Bäche, Teiche, Seeufer"},{"k":"Merkmal","v":"ungiftig, Zickzack-Zeichnung"}]',
 array['Natrix maura close-up','Natrix maura juvenile','Natrix maura water']),
('reptilien', 10, 'Schlingnatter', 'Coronella austriaca',
 'Die Schlingnatter ist eine kleine, ungiftige Schlange mit dunklen Flecken auf graubraunem Grund. Wegen der Zeichnung wird sie oft mit der Kreuzotter verwechselt, hat aber runde Pupillen. Ihre Beute, vor allem Eidechsen, umschlingt sie und hält sie fest. Sie lebt an sonnigen, steinigen Orten.',
 '[{"k":"Grösse","v":"bis 70 cm"},{"k":"Nahrung","v":"Eidechsen, Blindschleichen"},{"k":"Lebensraum","v":"Trockenmauern, Geröll, Waldränder"},{"k":"Merkmal","v":"ungiftig, runde Pupille"}]',
 array['Coronella austriaca close-up','Coronella austriaca juvenile','Coronella austriaca habitat']),
('reptilien', 11, 'Äskulapnatter', 'Zamenis longissimus',
 'Die Äskulapnatter ist mit bis zu 2 m die längste Schlange der Schweiz. Sie klettert sehr gut und jagt Mäuse und Vögel auch auf Bäumen. Sie ist das Zeichen der Medizin: Sie windet sich um den Stab des Äskulap. In der Schweiz lebt sie vor allem im Tessin und im Wallis.',
 '[{"k":"Grösse","v":"bis 2 m"},{"k":"Nahrung","v":"Mäuse, Vögel"},{"k":"Lebensraum","v":"Waldränder, Trockenmauern"},{"k":"Merkmal","v":"ungiftig, klettert gut"}]',
 array['Zamenis longissimus close-up','Zamenis longissimus juvenile','Zamenis longissimus tree']),
('reptilien', 12, 'Gelbgrüne Zornnatter', 'Hierophis viridiflavus',
 'Die Gelbgrüne Zornnatter ist sehr schnell und wehrt sich heftig, wenn man sie fängt, daher ihr Name. Sie ist aber ungiftig. Ihr schwarzer Körper ist mit gelbgrünen Flecken und Streifen gemustert. In der Schweiz lebt sie vor allem im Tessin.',
 '[{"k":"Grösse","v":"bis 1.6 m"},{"k":"Nahrung","v":"Eidechsen, Mäuse"},{"k":"Lebensraum","v":"sonnige Hänge"},{"k":"Merkmal","v":"ungiftig, sehr flink"}]',
 array['Hierophis viridiflavus close-up','Hierophis viridiflavus juvenile','Hierophis viridiflavus habitat']),
('reptilien', 13, 'Kreuzotter', 'Vipera berus',
 'Die Kreuzotter ist giftig und an einem dunklen Zickzackband auf dem Rücken zu erkennen. Sie lebt vor allem in den Alpen bis über 2500 m. Bisse sind selten und kommen fast nur vor, wenn man auf eine Otter tritt oder sie anfasst. Sie bringt lebende Junge zur Welt.',
 '[{"k":"Grösse","v":"bis 70 cm"},{"k":"Nahrung","v":"Mäuse, Eidechsen"},{"k":"Lebensraum","v":"Alpen, Moore"},{"k":"Merkmal","v":"giftig, senkrechte Pupille"}]',
 array['Vipera berus close-up','Vipera berus juvenile','Vipera berus alpine habitat']),
('reptilien', 14, 'Aspisviper', 'Vipera aspis',
 'Die Aspisviper ist die zweite Giftschlange der Schweiz. Sie hat eine leicht aufgestülpte Schnauze und eine Zeichnung aus Querbändern. Sie lebt an warmen, steinigen Hängen im Jura, in den Alpen und in der Südschweiz. Bei Gefahr flüchtet sie meist; nach einem Biss immer ärztliche Hilfe holen.',
 '[{"k":"Grösse","v":"bis 75 cm"},{"k":"Nahrung","v":"Mäuse, Eidechsen"},{"k":"Lebensraum","v":"sonnige, steinige Hänge"},{"k":"Merkmal","v":"giftig, senkrechte Pupille"}]',
 array['Vipera aspis close-up','Vipera aspis juvenile','Vipera aspis habitat']),
('reptilien', 15, 'Europäische Sumpfschildkröte', 'Emys orbicularis',
 'Die Europäische Sumpfschildkröte ist die einzige einheimische Schildkröte der Schweiz. Sie war fast ausgestorben und wird heute an wenigen Orten wieder angesiedelt. Sie lebt in ruhigen, pflanzenreichen Weihern und sonnt sich gern auf Baumstämmen im Wasser. Oft werden ausgesetzte fremde Schildkröten für sie gehalten.',
 '[{"k":"Grösse","v":"Panzer bis 20 cm"},{"k":"Nahrung","v":"Insekten, Schnecken, Fische"},{"k":"Lebensraum","v":"pflanzenreiche Weiher"},{"k":"Merkmal","v":"gelbe Punkte auf dunklem Panzer"}]',
 array['Emys orbicularis close-up','Emys orbicularis hatchling','Emys orbicularis pond basking']),

-- ---------------------------------------------------------------- Falter (dazu die 4 umgezogenen)
('falter', 1, 'Kleiner Fuchs', 'Aglais urticae',
 'Der Kleine Fuchs ist einer der häufigsten Tagfalter der Schweiz und fliegt bis hoch in die Alpen. Seine Flügel sind orangerot mit schwarzen und gelben Flecken und einem blauen Saum. Die Raupen leben in Gruppen an Brennnesseln. Er überwintert als Falter in Kellern oder Scheunen.',
 '[{"k":"Spannweite","v":"40–50 mm"},{"k":"Raupenfutter","v":"Brennnessel"},{"k":"Flugzeit","v":"März–Oktober"},{"k":"Besonderes","v":"fliegt bis über 3000 m"}]',
 array['Aglais urticae macro','Aglais urticae caterpillar','Aglais urticae on flower']),
('falter', 2, 'Admiral', 'Vanessa atalanta',
 'Der Admiral hat schwarze Flügel mit einer leuchtend roten Binde und weissen Flecken. Er ist ein Wanderfalter: Jeden Frühling fliegen Admirale aus dem Mittelmeerraum über die Alpen zu uns. Im Herbst saugt er gern an Fallobst.',
 '[{"k":"Spannweite","v":"50–60 mm"},{"k":"Raupenfutter","v":"Brennnessel"},{"k":"Flugzeit","v":"Mai–Oktober"},{"k":"Besonderes","v":"Wanderfalter"}]',
 array['Vanessa atalanta macro','Vanessa atalanta caterpillar','Vanessa atalanta on flower']),
('falter', 3, 'Distelfalter', 'Vanessa cardui',
 'Der Distelfalter ist ein unglaublicher Wanderer: Er zieht jedes Jahr von Afrika bis nach Nordeuropa und zurück, verteilt auf mehrere Generationen. In manchen Jahren fliegen Millionen über die Alpen. Er ist orange mit schwarzen und weissen Flecken.',
 '[{"k":"Spannweite","v":"50–60 mm"},{"k":"Raupenfutter","v":"Disteln, Brennnessel"},{"k":"Flugzeit","v":"Mai–Oktober"},{"k":"Besonderes","v":"wandert von Afrika bis Nordeuropa"}]',
 array['Vanessa cardui macro','Vanessa cardui caterpillar','Vanessa cardui on flower']),
('falter', 4, 'Kaisermantel', 'Argynnis paphia',
 'Der Kaisermantel ist einer der grössten Perlmutterfalter der Schweiz. Die Oberseite ist orange mit schwarzen Flecken, die Unterseite der Hinterflügel grünlich mit silbrigen Streifen. Man sieht ihn im Hochsommer auf Waldlichtungen, oft an Wasserdost oder Disteln. Die Raupen fressen Veilchen.',
 '[{"k":"Spannweite","v":"55–70 mm"},{"k":"Raupenfutter","v":"Veilchen"},{"k":"Flugzeit","v":"Juni–August"},{"k":"Besonderes","v":"silbrige Streifen unten"}]',
 array['Argynnis paphia macro','Argynnis paphia caterpillar','Argynnis paphia on flower']),
('falter', 5, 'Aurorafalter', 'Anthocharis cardamines',
 'Der Aurorafalter ist ein Frühlingsbote. Nur die Männchen haben leuchtend orange Flügelspitzen, die Weibchen sind weiss. Die grünlich marmorierte Unterseite der Hinterflügel tarnt ihn auf Doldenblüten. Seine Raupen fressen am Wiesen-Schaumkraut und an der Knoblauchsrauke.',
 '[{"k":"Spannweite","v":"40–48 mm"},{"k":"Raupenfutter","v":"Wiesen-Schaumkraut, Knoblauchsrauke"},{"k":"Flugzeit","v":"April–Juni"},{"k":"Besonderes","v":"orange Spitzen (Männchen)"}]',
 array['Anthocharis cardamines macro','Anthocharis cardamines caterpillar','Anthocharis cardamines on flower']),
('falter', 6, 'Grosser Kohlweissling', 'Pieris brassicae',
 'Der Grosse Kohlweissling ist weiss mit schwarzen Flügelspitzen; die Weibchen haben zusätzlich zwei schwarze Punkte. Seine gelb-schwarzen Raupen fressen in Gruppen an Kohl und können Gemüsegärten kahl fressen. Vögel mögen die Raupen nicht, weil sie scharfe Senföle aus dem Kohl speichern.',
 '[{"k":"Spannweite","v":"50–65 mm"},{"k":"Raupenfutter","v":"Kohl, Kapuzinerkresse"},{"k":"Flugzeit","v":"April–Oktober"},{"k":"Besonderes","v":"Raupen fressen Kohl"}]',
 array['Pieris brassicae macro','Pieris brassicae caterpillar','Pieris brassicae on flower']),
('falter', 7, 'Hauhechel-Bläuling', 'Polyommatus icarus',
 'Der Hauhechel-Bläuling ist der häufigste Bläuling der Schweiz. Die Männchen sind leuchtend himmelblau, die Weibchen meist braun mit orangen Flecken. Seine Raupen werden oft von Ameisen besucht: Sie geben eine süsse Flüssigkeit ab, und die Ameisen beschützen sie dafür.',
 '[{"k":"Spannweite","v":"25–35 mm"},{"k":"Raupenfutter","v":"Hornklee, Hauhechel, Klee"},{"k":"Flugzeit","v":"Mai–September"},{"k":"Besonderes","v":"Raupen werden von Ameisen beschützt"}]',
 array['Polyommatus icarus macro','Polyommatus icarus caterpillar','Polyommatus icarus on flower']),
('falter', 8, 'Schachbrett', 'Melanargia galathea',
 'Das Schachbrett ist wegen seiner schwarz-weissen Flügelzeichnung unverwechselbar. Es fliegt im Sommer in blumenreichen Magerwiesen und besucht gerne violette Blüten wie Flockenblumen und Witwenblumen. Seine Raupen fressen Gräser. Wird eine Wiese zu früh gemäht, verschwindet es.',
 '[{"k":"Spannweite","v":"45–55 mm"},{"k":"Raupenfutter","v":"Gräser"},{"k":"Flugzeit","v":"Juni–August"},{"k":"Besonderes","v":"Schachbrettmuster"}]',
 array['Melanargia galathea macro','Melanargia galathea caterpillar','Melanargia galathea on flower']),
('falter', 9, 'Grosser Schillerfalter', 'Apatura iris',
 'Beim Grossen Schillerfalter schillern die Flügel der Männchen je nach Blickwinkel tiefblau bis violett. Er fliegt vor allem in den Baumkronen und kommt nur herunter, um an Pfützen, Kot oder Aas zu saugen, nicht an Blüten. Seine Raupe frisst an Salweiden.',
 '[{"k":"Spannweite","v":"60–75 mm"},{"k":"Raupenfutter","v":"Salweide"},{"k":"Flugzeit","v":"Juni–August"},{"k":"Besonderes","v":"schillernde Flügel (Männchen)"}]',
 array['Apatura iris macro','Apatura iris caterpillar','Apatura iris puddling']),
('falter', 10, 'Taubenschwänzchen', 'Macroglossum stellatarum',
 'Das Taubenschwänzchen ist ein Nachtfalter, der am Tag fliegt. Es steht wie ein Kolibri schwirrend vor den Blüten und saugt mit seinem langen Rüssel Nektar. Viele Leute halten es darum für einen Kolibri. Es ist ein Wanderfalter aus dem Süden.',
 '[{"k":"Spannweite","v":"40–50 mm"},{"k":"Raupenfutter","v":"Labkraut"},{"k":"Flugzeit","v":"Mai–Oktober"},{"k":"Besonderes","v":"schwirrt wie ein Kolibri"}]',
 array['Macroglossum stellatarum macro','Macroglossum stellatarum caterpillar','Macroglossum stellatarum on flower']),
('falter', 11, 'Sechsfleck-Widderchen', 'Zygaena filipendulae',
 'Das Sechsfleck-Widderchen ist ein tagaktiver Nachtfalter mit schwarzgrün glänzenden Vorderflügeln und sechs roten Flecken. Die rote Farbe warnt Feinde: Der Falter enthält Blausäure und ist giftig. Er fliegt langsam und sitzt oft auf Flockenblumen und Witwenblumen.',
 '[{"k":"Spannweite","v":"30–38 mm"},{"k":"Raupenfutter","v":"Hornklee"},{"k":"Flugzeit","v":"Juni–August"},{"k":"Besonderes","v":"giftig (Warnfarbe)"}]',
 array['Zygaena filipendulae macro','Zygaena filipendulae caterpillar','Zygaena filipendulae on flower']),

-- ---------------------------------------------------------------- Insekten (Ersatz für die Falter)
('insekten', 1, 'Blaugrüne Mosaikjungfer', 'Aeshna cyanea',
 'Die Blaugrüne Mosaikjungfer ist eine grosse Libelle, die oft auch Gartenweiher besucht. Sie ist neugierig und fliegt manchmal ganz nahe an Menschen heran. Ihre Larven leben bis zu drei Jahre im Wasser und jagen dort Kaulquappen und Insektenlarven.',
 '[{"k":"Grösse","v":"7 cm, Spannweite 10 cm"},{"k":"Nahrung","v":"Fluginsekten"},{"k":"Entwicklung","v":"2–3 Jahre als Larve im Wasser"},{"k":"Besonderes","v":"neugierig"}]',
 array['Aeshna cyanea macro','Aeshna cyanea larva','Aeshna cyanea garden pond']),
('insekten', 2, 'Streifenwanze', 'Graphosoma italicum',
 'Die Streifenwanze ist mit ihren roten und schwarzen Längsstreifen unverwechselbar. Die Farben warnen Feinde, denn sie schmeckt schlecht. Man findet sie im Sommer oft auf den Blütendolden von Wilder Möhre und Bärenklau, wo sie Pflanzensaft saugt.',
 '[{"k":"Grösse","v":"8–11 mm"},{"k":"Nahrung","v":"Pflanzensaft von Doldenblütlern"},{"k":"Entwicklung","v":"ohne Puppe, Larven sehen den Wanzen ähnlich"},{"k":"Besonderes","v":"Warnfarben"}]',
 array['Graphosoma italicum macro','Graphosoma italicum nymph','Graphosoma italicum umbel flower']),
('insekten', 3, 'Grosses Glühwürmchen', 'Lampyris noctiluca',
 'Das Grosse Glühwürmchen ist ein Käfer. Die flügellosen Weibchen leuchten in warmen Sommernächten am Boden grünlich, um Männchen anzulocken. Das Licht entsteht durch einen chemischen Vorgang und wird kaum warm. Die Larven fressen Schnecken.',
 '[{"k":"Grösse","v":"10–18 mm (Weibchen bis 25 mm)"},{"k":"Nahrung","v":"Larve: Schnecken"},{"k":"Entwicklung","v":"2–3 Jahre als Larve"},{"k":"Besonderes","v":"leuchtet in der Nacht"}]',
 array['Lampyris noctiluca macro','Lampyris noctiluca larva','Lampyris noctiluca glowing night']),
('insekten', 4, 'Goldglänzender Rosenkäfer', 'Cetonia aurata',
 'Der Rosenkäfer glänzt metallisch grün bis golden. Er frisst Pollen und Blütenblätter, vor allem an Rosen und Holunder. Seine Larven sehen aus wie Engerlinge, fressen aber nur morsches Holz und Kompost und schaden keinen Pflanzen. Anders als die meisten Käfer fliegt er mit geschlossenen Deckflügeln.',
 '[{"k":"Grösse","v":"14–20 mm"},{"k":"Nahrung","v":"Pollen, Blüten"},{"k":"Entwicklung","v":"Larve im Kompost"},{"k":"Besonderes","v":"fliegt mit geschlossenen Deckflügeln"}]',
 array['Cetonia aurata macro','Cetonia aurata larva','Cetonia aurata on flower']),

-- ---------------------------------------------------------------- Pilze
('pilze', 1, 'Steinpilz', 'Boletus edulis',
 'Der Steinpilz ist einer der beliebtesten Speisepilze. Er hat einen braunen Hut, einen dicken, bauchigen Stiel mit feinem weissem Netz und unter dem Hut Röhren statt Lamellen. Die Röhren sind jung weiss und werden später gelbgrün. Er wächst in Nadel- und Laubwäldern, oft unter Fichten.',
 '[{"k":"Essbarkeit","v":"essbar (nur nach Pilzkontrolle)"},{"k":"Zeit","v":"Juni–Oktober"},{"k":"Standort","v":"Fichten- und Buchenwälder"},{"k":"Merkmal","v":"weisses Netz am Stiel"}]',
 array['Boletus edulis pores underside','Boletus edulis young','Boletus edulis forest']),
('pilze', 2, 'Eierschwamm', 'Cantharellus cibarius',
 'Der Eierschwamm, in Deutschland Pfifferling genannt, ist dottergelb und riecht leicht nach Aprikosen. Unter dem Hut hat er keine echten Lamellen, sondern weiche Leisten, die am Stiel herablaufen. Er gehört zu den beliebtesten Speisepilzen der Schweiz. Verwechseln kann man ihn mit dem Falschen Pfifferling.',
 '[{"k":"Essbarkeit","v":"essbar (nur nach Pilzkontrolle)"},{"k":"Zeit","v":"Juni–Oktober"},{"k":"Standort","v":"Wälder mit sauren Böden"},{"k":"Merkmal","v":"Leisten statt Lamellen"}]',
 array['Cantharellus cibarius underside ridges','Cantharellus cibarius young','Cantharellus cibarius forest moss']),
('pilze', 3, 'Maronen-Röhrling', 'Imleria badia',
 'Der Maronen-Röhrling hat einen kastanienbraunen Hut und gelbliche Röhren. Drückt man auf die Röhren, laufen sie blau an. Er wächst häufig in Fichtenwäldern und ist ein guter Speisepilz.',
 '[{"k":"Essbarkeit","v":"essbar (nur nach Pilzkontrolle)"},{"k":"Zeit","v":"Juli–November"},{"k":"Standort","v":"Nadelwälder"},{"k":"Merkmal","v":"Röhren laufen blau an"}]',
 array['Imleria badia pores underside','Imleria badia young','Imleria badia spruce forest']),
('pilze', 4, 'Parasol', 'Macrolepiota procera',
 'Der Parasol oder Riesenschirmling bekommt einen Hut von bis zu 30 cm Durchmesser. Jung sieht er aus wie ein Trommelschlegel, später spannt er sich auf wie ein Sonnenschirm. Typisch sind der verschiebbare Ring und der schlangenhautartig gemusterte Stiel.',
 '[{"k":"Essbarkeit","v":"Hut essbar (nur nach Pilzkontrolle)"},{"k":"Zeit","v":"Juli–Oktober"},{"k":"Standort","v":"Waldränder, Lichtungen, Wiesen"},{"k":"Merkmal","v":"verschiebbarer Ring am Stiel"}]',
 array['Macrolepiota procera gills underside','Macrolepiota procera young drumstick','Macrolepiota procera meadow']),
('pilze', 5, 'Speisemorchel', 'Morchella esculenta',
 'Die Speisemorchel wächst im Frühling, lange bevor die meisten anderen Pilze erscheinen. Ihr Hut sieht aus wie ein Schwamm oder eine Bienenwabe und ist innen hohl. Roh ist sie giftig, gut gekocht ein begehrter Speisepilz. Verwechseln kann man sie mit der giftigen Frühjahrslorchel.',
 '[{"k":"Essbarkeit","v":"nur gekocht essbar (nach Pilzkontrolle)"},{"k":"Zeit","v":"März–Mai"},{"k":"Standort","v":"Auenwälder, unter Eschen"},{"k":"Merkmal","v":"wabenartiger, hohler Hut"}]',
 array['Morchella esculenta cut hollow','Morchella esculenta young','Morchella esculenta forest ground']),
('pilze', 6, 'Semmel-Stoppelpilz', 'Hydnum repandum',
 'Der Semmel-Stoppelpilz hat einen semmelgelben Hut. Auf der Unterseite trägt er weder Lamellen noch Röhren, sondern viele kleine, weiche Stacheln. Er wird kaum von Maden befallen und ist ein guter Speisepilz.',
 '[{"k":"Essbarkeit","v":"essbar (nur nach Pilzkontrolle)"},{"k":"Zeit","v":"Juli–November"},{"k":"Standort","v":"Laub- und Nadelwälder"},{"k":"Merkmal","v":"Stacheln auf der Unterseite"}]',
 array['Hydnum repandum spines underside','Hydnum repandum young','Hydnum repandum forest']),
('pilze', 7, 'Hallimasch', 'Armillaria mellea',
 'Der Hallimasch wächst in grossen Büscheln an Baumstümpfen und lebenden Bäumen. Er ist ein gefürchteter Schädling im Wald, weil er Bäume befällt und zum Absterben bringt. Sein Pilzgeflecht kann sich im Boden über viele Hektaren ausbreiten. Roh ist er giftig.',
 '[{"k":"Essbarkeit","v":"roh giftig, nur gut gekocht essbar (nach Pilzkontrolle)"},{"k":"Zeit","v":"September–November"},{"k":"Standort","v":"Baumstümpfe, Stämme"},{"k":"Merkmal","v":"wächst in Büscheln"}]',
 array['Armillaria mellea gills underside','Armillaria mellea young cluster','Armillaria mellea tree stump']),
('pilze', 8, 'Riesenbovist', 'Calvatia gigantea',
 'Der Riesenbovist ist eine weisse Kugel, die so gross wie ein Fussball oder noch grösser werden kann. Solange er innen rein weiss ist, ist er essbar. Später wird das Innere braun und zerfällt zu unzähligen Sporen, die der Wind verbreitet.',
 '[{"k":"Essbarkeit","v":"jung essbar (nur nach Pilzkontrolle)"},{"k":"Zeit","v":"Juli–Oktober"},{"k":"Standort","v":"Wiesen, Weiden, Gärten"},{"k":"Merkmal","v":"weisse Kugel bis 50 cm"}]',
 array['Calvatia gigantea cut inside','Calvatia gigantea young','Calvatia gigantea meadow']),
('pilze', 9, 'Schwefelporling', 'Laetiporus sulphureus',
 'Der Schwefelporling wächst in auffälligen, schwefelgelben bis orangen Konsolen an Laubbäumen, vor allem an Eichen und Weiden. Er zersetzt das Holz im Innern des Stammes. Junge Fruchtkörper werden wegen ihres Geschmacks auch «Hühnchen des Waldes» genannt.',
 '[{"k":"Essbarkeit","v":"jung essbar, nicht für alle bekömmlich (nach Pilzkontrolle)"},{"k":"Zeit","v":"Mai–September"},{"k":"Standort","v":"Eichen, Weiden, Obstbäume"},{"k":"Merkmal","v":"gelbe Konsolen am Stamm"}]',
 array['Laetiporus sulphureus pores underside','Laetiporus sulphureus young','Laetiporus sulphureus tree trunk']),
('pilze', 10, 'Fliegenpilz', 'Amanita muscaria',
 'Der Fliegenpilz mit seinem roten Hut und den weissen Flocken ist der bekannteste Pilz überhaupt. Er ist giftig und kann Rausch, Übelkeit und Krämpfe auslösen. Früher legte man ihn in Milch, um Fliegen zu töten, daher sein Name. Er wächst oft unter Birken und Fichten.',
 '[{"k":"Essbarkeit","v":"giftig"},{"k":"Zeit","v":"Juli–November"},{"k":"Standort","v":"unter Birken und Fichten"},{"k":"Merkmal","v":"roter Hut mit weissen Flocken"}]',
 array['Amanita muscaria gills underside','Amanita muscaria young','Amanita muscaria forest birch']),
('pilze', 11, 'Grüner Knollenblätterpilz', 'Amanita phalloides',
 'Der Grüne Knollenblätterpilz ist der gefährlichste Giftpilz der Schweiz: Schon ein einziger Pilz kann tödlich sein. Die Vergiftung merkt man erst nach vielen Stunden, wenn die Leber schon schwer geschädigt ist. Er hat einen grünlichen Hut, weisse Lamellen, einen Ring und eine Knolle am Stielende.',
 '[{"k":"Essbarkeit","v":"tödlich giftig"},{"k":"Zeit","v":"Juli–Oktober"},{"k":"Standort","v":"Laubwälder, unter Eichen und Buchen"},{"k":"Merkmal","v":"Knolle, weisse Lamellen"}]',
 array['Amanita phalloides gills underside','Amanita phalloides young volva','Amanita phalloides forest']),
('pilze', 12, 'Pantherpilz', 'Amanita pantherina',
 'Der Pantherpilz hat einen braunen Hut mit weissen Flocken und ist stark giftig. Er wird manchmal mit dem essbaren Perlpilz verwechselt. Anders als beim Perlpilz ist der Ring am Stiel glatt, und die Knolle am Stielende hat einen deutlichen Rand.',
 '[{"k":"Essbarkeit","v":"stark giftig"},{"k":"Zeit","v":"Juli–Oktober"},{"k":"Standort","v":"Laub- und Nadelwälder"},{"k":"Merkmal","v":"brauner Hut mit weissen Flocken"}]',
 array['Amanita pantherina gills underside','Amanita pantherina young','Amanita pantherina forest']),
('pilze', 13, 'Satans-Röhrling', 'Rubroboletus satanas',
 'Der Satans-Röhrling hat einen hellen, grauweissen Hut, rote Röhrenmündungen und einen dicken, rot genetzten Stiel. Sein Fleisch läuft beim Anschneiden blau an. Er ist giftig und führt zu starkem Erbrechen und Durchfall. Er wächst in warmen Laubwäldern auf Kalkboden und ist eher selten.',
 '[{"k":"Essbarkeit","v":"giftig"},{"k":"Zeit","v":"Juli–September"},{"k":"Standort","v":"warme Laubwälder auf Kalk"},{"k":"Merkmal","v":"rote Poren, dicker Stiel"}]',
 array['Rubroboletus satanas pores underside','Rubroboletus satanas young','Rubroboletus satanas forest']),
('pilze', 14, 'Zunderschwamm', 'Fomes fomentarius',
 'Der Zunderschwamm wächst als harte, hufförmige Konsole an Buchen und Birken und kann viele Jahre alt werden. Jedes Jahr wächst eine neue Röhrenschicht dazu. Früher gewann man aus ihm Zunder zum Feuermachen; schon der Gletschermann Ötzi trug welchen bei sich.',
 '[{"k":"Essbarkeit","v":"ungeniessbar (holzig)"},{"k":"Zeit","v":"ganzjährig"},{"k":"Standort","v":"Buchen, Birken"},{"k":"Merkmal","v":"hufförmig, mehrjährig"}]',
 array['Fomes fomentarius pores underside','Fomes fomentarius young','Fomes fomentarius beech trunk']),
('pilze', 15, 'Stinkmorchel', 'Phallus impudicus',
 'Die Stinkmorchel wächst aus einem weichen, weissen «Hexenei» heraus. Ihr Kopf ist mit einer olivgrünen, schleimigen Sporenmasse bedeckt, die stark nach Aas riecht. Der Gestank lockt Fliegen an, die die Sporen verbreiten. Man riecht sie oft, bevor man sie sieht.',
 '[{"k":"Essbarkeit","v":"ungeniessbar"},{"k":"Zeit","v":"Juni–Oktober"},{"k":"Standort","v":"Wälder, Gärten"},{"k":"Merkmal","v":"Aasgeruch, wächst aus einem «Hexenei»"}]',
 array['Phallus impudicus close-up','Phallus impudicus egg','Phallus impudicus forest'])

) as n(cat, nr, name, sub, descr, facts, terms)
where exists (select 1 from public.categories c where c.id = n.cat)
  and not exists (
    select 1 from public.entries e
    where lower(e.name) = lower(n.name) or lower(e.subtitle) = lower(n.sub)
  );

commit;

-- Kontrolle: Einträge pro Kategorie (je 15; ausgeblendete zählen mit)
select c.sort, c.id, count(e.id) from public.categories c left join public.entries e on e.category_id = c.id
group by c.sort, c.id order by c.sort;
