-- Forscheraufträge (Version 2.14.0): Einstieg mit einer Alltagssituation, einem Rätsel, einer Rechenaufgabe oder einer
-- Forscherfrage; die Antwort steht in einem Eintrag der Kategorie. Die Anzeige zeigt einmal pro Tag einen Auftrag,
-- die Antworten bleiben nur auf dem Gerät (localStorage), in der Datenbank stehen nur die Aufträge selbst.
--   kind:        situation (Alltagssituation), raetsel (Rätsel), rechnen (Rechenaufgabe), frage (Forscherfrage)
--   guess:       vor dem Nachforschen eine Vermutung notieren
--   answer_type: choice (Auswahl aus choices, richtig = answer), text (kurze Antwort, mehrere richtige mit «|»,
--                nur Zahlen = Zahlenvergleich), free (freie Antwort, danach Musterlösung = explanation und Selbsteinschätzung)
--   hint:        Tipp nach einer falschen Antwort; explanation: Erklärung nach der Lösung
-- Einmal im Supabase-Dashboard unter «SQL Editor» ausführen, BEVOR die neue index.js online ist
-- (die Anzeige lädt die Aufträge mit den Kategorien). Lässt sich gefahrlos mehrmals ausführen.

begin;

create table if not exists public.tasks (
  id          text primary key check (id ~ '^[a-z0-9-]{2,60}$'),
  category_id text not null references public.categories(id) on update cascade on delete cascade,
  entry_id    uuid references public.entries(id) on delete set null,
  kind        text not null check (kind in ('situation', 'raetsel', 'rechnen', 'frage')),
  question    text not null check (char_length(question) between 10 and 600),
  guess       boolean not null default false,
  answer_type text not null check (answer_type in ('choice', 'text', 'free')),
  choices     jsonb not null default '[]'::jsonb check (jsonb_typeof(choices) = 'array'),
  answer      text not null default '' check (char_length(answer) <= 300),
  hint        text not null default '' check (char_length(hint) <= 400),
  explanation text not null default '' check (char_length(explanation) <= 1000),
  sort        integer not null default 0,
  visible     boolean not null default true,
  created_at  timestamptz not null default now()
);
create index if not exists tasks_category_idx on public.tasks (category_id);

alter table public.tasks enable row level security;
drop policy if exists "lesen" on public.tasks;
create policy "lesen" on public.tasks for select to anon, authenticated using (visible or public.is_admin());
drop policy if exists "admin_schreiben" on public.tasks;
create policy "admin_schreiben" on public.tasks for all to authenticated using (public.is_admin()) with check (public.is_admin());
grant select on public.tasks to anon, authenticated;
grant insert, update, delete on public.tasks to authenticated;

-- 25 Aufträge über alle 22 Kategorien; bestehende Aufträge (gleiche id) bleiben unverändert
insert into public.tasks (id, category_id, entry_id, kind, question, guess, answer_type, choices, answer, hint, explanation, sort)
select t.id, t.cat, (select e.id from public.entries e where e.category_id = t.cat and e.name = t.entry),
       t.kind, t.question, t.guess, t.answer_type, t.choices::jsonb, t.answer, t.hint, t.explanation, t.sort
  from (values
  ('kolibri', 'falter', 'Taubenschwänzchen', 'situation',
   'Deine Nachbarin ruft begeistert: «In meinem Garten schwirrt ein Kolibri vor den Blüten und saugt Nektar!» Kolibris leben aber nur in Amerika. Was hat sie wirklich gesehen?',
   true, 'text', '[]', 'Taubenschwänzchen',
   'Es ist kein Vogel, sondern ein Insekt. Schau bei den Faltern nach einem, der wie ein Kolibri vor den Blüten steht.',
   'Sie hat ein Taubenschwänzchen gesehen. Dieser Nachtfalter fliegt am Tag, steht schwirrend wie ein Kolibri vor den Blüten und saugt mit seinem langen Rüssel Nektar. Er ist ein Wanderfalter aus dem Süden.',
   10),
  ('knollenblaetterpilz', 'pilze', 'Grüner Knollenblätterpilz', 'situation',
   'Beim Waldspaziergang unter Buchen findest du einen schönen Pilz: grünlicher Hut, weisse Lamellen, ein Ring am Stiel und unten eine dicke Knolle. Dein Kollege meint: «Ein Champignon, den nehmen wir zum Znacht mit!» Was antwortest du?',
   true, 'choice',
   '["Auf keinen Fall essen: Das könnte der tödlich giftige Grüne Knollenblätterpilz sein.", "Mitnehmen und gut durchkochen, dann ist jedes Gift weg.", "Ein kleines Stück probieren: Wenn es nicht bitter ist, ist er essbar."]',
   'Auf keinen Fall essen: Das könnte der tödlich giftige Grüne Knollenblätterpilz sein.',
   'Vergleiche die Merkmale mit dem gefährlichsten Giftpilz der Schweiz: Achte auf Lamellen, Ring und Knolle.',
   'Weisse Lamellen, Ring und Knolle passen zum Grünen Knollenblätterpilz. Schon ein einziger Pilz kann tödlich sein, und Kochen zerstört das Gift nicht. Die Vergiftung merkt man erst nach vielen Stunden. Darum gilt: Pilze nur essen, wenn die Pilzkontrolle sie geprüft hat.',
   20),
  ('bergahorn', 'baeume', 'Bergahorn', 'raetsel',
   'Ich bin der häufigste Ahorn der Schweiz. Meine Früchte haben zwei Flügel und segeln wie Propeller zu Boden. Kinder kleben sie sich gern als «Nasenzwicker» auf die Nase. Wer bin ich?',
   false, 'text', '[]', 'Bergahorn|Berg-Ahorn',
   'Es ist ein Ahorn, aber welcher? Bei den Bäumen gibt es zwei. Lies nach, welcher «der häufigste» ist.',
   'Gesucht war der Bergahorn. Seine Flügelfrüchte stehen etwa im rechten Winkel zueinander. Beim Feldahorn stehen die Flügel waagrecht auseinander.',
   30),
  ('gewitter', 'wetterphaenomene', 'Gewitter', 'rechnen',
   'Du bist draussen und siehst einen Blitz. Du zählst langsam: Nach 9 Sekunden hörst du den Donner. Wie viele Kilometer ist das Gewitter ungefähr entfernt?',
   false, 'text', '[]', '3',
   'Im Steckbrief des Gewitters steht eine Faustregel: Wie viele Sekunden entsprechen etwa einem Kilometer?',
   '9 Sekunden : 3 = 3 km. Das Licht des Blitzes sehen wir fast sofort, der Schall braucht etwa 3 Sekunden für einen Kilometer. Wer den Donner hört, ist schon in Reichweite von Blitzen und sucht besser Schutz in einem Gebäude oder Auto.',
   40),
  ('baerlauch', 'wiesenblumen', 'Herbstzeitlose', 'situation',
   'Im Frühling willst du im Wald Bärlauch für ein Pesto sammeln. Daneben wachsen Pflanzen mit sehr ähnlichen Blättern. Woran erkennst du, dass du wirklich Bärlauch gepflückt hast? Und warum ist das so wichtig?',
   true, 'free', '[]', '',
   'Schau bei den Wiesenblumen nach der giftigen Pflanze, deren Blätter im Frühling mit Bärlauch verwechselt werden, und lies «Nicht verwechseln mit».',
   'Bärlauch riecht beim Zerreiben stark nach Knoblauch und hat gestielte Blätter. Die Blätter der Herbstzeitlose sehen ähnlich aus, riechen aber nicht nach Knoblauch und haben keinen Stiel. Die Herbstzeitlose ist sehr giftig, eine Verwechslung kann lebensgefährlich sein. Achtung: Wer schon Bärlauch zerrieben hat, riecht an den Fingern sowieso Knoblauch. Darum jedes Blatt einzeln prüfen und im Zweifel stehen lassen.',
   50),
  ('mauersegler', 'voegel', 'Mauersegler', 'raetsel',
   'Ich fresse, trinke und schlafe sogar im Flug und lande fast nie. Nur von Mai bis Anfang August bin ich in der Schweiz. In Gruppen jage ich mit schrillen Rufen um die Häuser. Wer bin ich?',
   false, 'text', '[]', 'Mauersegler',
   'Suche bei den Vögeln nach einem, der in Städten und Dörfern unter Dächern brütet.',
   'Gesucht war der Mauersegler. Er verbringt fast sein ganzes Leben in der Luft und brütet in Mauerlöchern und unter Dächern.',
   60),
  ('jet-deau', 'sehenswuerdigkeiten', 'Jet d''eau', 'rechnen',
   'Der Jet d''eau in Genf schleudert jede Sekunde 500 Liter Wasser in die Höhe. Wie viele Liter sind das in einer Minute?',
   false, 'text', '[]', '30000',
   'Eine Minute hat 60 Sekunden. Rechne 500 Liter mal 60.',
   '500 Liter × 60 = 30 000 Liter pro Minute. Das Wasser schiesst mit rund 200 km/h bis 140 m hoch. Ursprünglich war die Fontäne ein Überdruckventil der städtischen Wasserversorgung.',
   70),
  ('aspisviper', 'reptilien', 'Aspisviper', 'situation',
   'Auf einer Wanderung im Jura liegt eine Schlange auf einem sonnigen Stein. Sie hat Querbänder auf dem Rücken, eine leicht aufgestülpte Schnauze und senkrechte Pupillen. Was ist richtig?',
   true, 'choice',
   '["Das ist wohl eine Aspisviper. Abstand halten und in Ruhe weitergehen.", "Das ist eine harmlose Natter, man darf sie ruhig aufheben.", "Schnell mit einem Stock vertreiben, damit sie niemanden beisst."]',
   'Das ist wohl eine Aspisviper. Abstand halten und in Ruhe weitergehen.',
   'Senkrechte Pupillen haben in der Schweiz nur die beiden Giftschlangen. Welche von ihnen hat eine aufgestülpte Schnauze?',
   'Aufgestülpte Schnauze, Querbänder und senkrechte Pupillen passen zur Aspisviper, einer der zwei Giftschlangen der Schweiz. Bei Gefahr flüchtet sie meist. Bisse kommen fast nur vor, wenn jemand eine Schlange anfasst oder auf sie tritt. Nach einem Biss immer ärztliche Hilfe holen.',
   80),
  ('alpensalamander', 'amphibien', 'Alpensalamander', 'frage',
   'Der Alpensalamander lebt auf Alpweiden bis auf 2800 m. Dort gibt es kaum Tümpel oder Bäche. Trotzdem braucht er für seinen Nachwuchs kein Gewässer. Wie ist das möglich?',
   true, 'choice',
   '["Das Weibchen bringt nach einer Tragzeit von zwei bis vier Jahren fertig entwickelte Junge zur Welt.", "Er legt seine Eier in den Schnee, wo die Larven schlüpfen.", "Seine Larven leben in feuchtem Moos, bis sie erwachsen sind."]',
   'Das Weibchen bringt nach einer Tragzeit von zwei bis vier Jahren fertig entwickelte Junge zur Welt.',
   'Lies im Steckbrief des Alpensalamanders die Zeile «Fortpflanzung».',
   'Der Alpensalamander ist lebendgebärend: Die Jungen entwickeln sich zwei bis vier Jahre lang im Bauch der Mutter. Der Feuersalamander dagegen setzt fertig entwickelte Larven in Waldbächen ab.',
   90),
  ('inn', 'gewaesser', 'Inn', 'raetsel',
   'Ich entspringe beim Malojapass und gebe einem ganzen Tal meinen Namen. Mein Wasser fliesst weder in die Nordsee noch ins Mittelmeer, sondern bis ins Schwarze Meer. Welcher Fluss bin ich?',
   false, 'text', '[]', 'Inn',
   'Das Tal heisst Engadin. Suche bei den Gewässern nach dem Fluss, der dort fliesst.',
   'Gesucht war der Inn. Engadin bedeutet «Tal des Inn». Der Inn fliesst durch Österreich und mündet in Passau in die Donau, und die Donau fliesst ins Schwarze Meer.',
   100),
  ('dufourspitze', 'berge', 'Dufourspitze', 'rechnen',
   'Die Dufourspitze ist der höchste Berg der Schweiz, das Matterhorn der bekannteste. Um wie viele Meter ist die Dufourspitze höher als das Matterhorn?',
   false, 'text', '[]', '156',
   'Die Höhen stehen in den Steckbriefen der beiden Berge. Rechne: höherer Berg minus tieferer Berg.',
   '4634 m − 4478 m = 156 m. Die Dufourspitze ist nach General Dufour benannt, der die erste genaue Karte der Schweiz erstellen liess.',
   110),
  ('pfaffenhuetchen', 'straeucher', 'Pfaffenhütchen', 'situation',
   'Am Waldrand leuchten im Herbst auffällige rosarote Früchte. Manche sind aufgeplatzt und zeigen orange Samen. Deine kleine Schwester will sie probieren. Was tust du?',
   false, 'choice',
   '["Sofort abhalten: Das ist das Pfaffenhütchen, alle Teile sind stark giftig.", "Probieren lassen: Leuchtende Früchte am Waldrand sind Wildfrüchte und essbar.", "Nur die orangen Samen essen lassen, die sind ungefährlich."]',
   'Sofort abhalten: Das ist das Pfaffenhütchen, alle Teile sind stark giftig.',
   'Schau bei den Sträuchern nach einem, dessen Früchte an die Kopfbedeckung eines Priesters erinnern.',
   'Die rosaroten Kapseln mit orangen Samen gehören zum Pfaffenhütchen. Alle Teile der Pflanze sind stark giftig. Hat doch jemand davon gegessen: sofort die Notrufnummer 145 (Tox Info Suisse) anrufen.',
   120),
  ('gluehwuermchen', 'insekten', 'Grosses Glühwürmchen', 'situation',
   'In einer warmen Sommernacht siehst du am Waldrand kleine grünliche Lichtpunkte im Gras. Sie bewegen sich kaum. Welches Tier leuchtet da?',
   true, 'text', '[]', 'Glühwürmchen|Grosses Glühwürmchen|Leuchtkäfer|Johanniskäfer',
   'Es ist ein Käfer, auch wenn sein Name nach einem Wurm klingt.',
   'Es sind die flügellosen Weibchen des Grossen Glühwürmchens, eines Käfers. Sie leuchten am Boden, um Männchen anzulocken. Das Licht entsteht durch einen chemischen Vorgang und wird kaum warm. Die Larven fressen Schnecken.',
   130),
  ('nagelfluh', 'steine', 'Nagelfluh', 'raetsel',
   'Ich sehe aus wie Beton mit vielen runden Kieselsteinen darin. Die herausragenden Steine erinnern an Nagelköpfe, und die Rigi besteht zu grossen Teilen aus mir. Welches Gestein bin ich?',
   false, 'text', '[]', 'Nagelfluh',
   'Mein Name verrät es: Die Steine sehen aus wie die Köpfe von …?',
   'Gesucht war die Nagelfluh. Sie entstand aus dem Geröll von Urflüssen, die aus den jungen Alpen kamen; die runden Kiesel wurden durch natürlichen Zement verkittet.',
   140),
  ('ringkuhkampf', 'nutztiere', 'Eringer', 'frage',
   'Im Wallis gibt es Ringkuhkämpfe: Die Kühe messen ihre Kräfte, und die Siegerin wird «Königin». Welche Rasse tritt dort an?',
   false, 'choice', '["Eringer", "Braunvieh", "Simmentaler"]', 'Eringer',
   'Die Rasse stammt aus einem Seitental des Wallis, dem Val d''Hérens.',
   'Es ist die Eringerkuh: klein, kräftig und schwarz bis dunkel rotbraun. Bei den Kämpfen legen die Kühe wie auf der Alp ihre Rangordnung fest und verletzen sich dabei kaum.',
   150),
  ('steinbock', 'saeugetiere', 'Alpensteinbock', 'rechnen',
   'Der Steinbock war in der Schweiz um 1800 ausgerottet. Ab 1911 wurden wieder Steinböcke ausgesetzt. Wie viele Jahre lang gab es ungefähr keine wilden Steinböcke in der Schweiz?',
   false, 'text', '[]', '111|110|100',
   'Die Jahreszahlen stehen in der Frage. Rechne: späteres Jahr minus früheres Jahr.',
   '1911 − 1800 = 111 Jahre, also gut 100 Jahre. Die ersten Tiere kamen aus dem Gran-Paradiso-Gebiet in Italien. Dank der Wiederansiedlung leben heute wieder über 15 000 Steinböcke in der Schweiz.',
   160),
  ('edelweiss', 'alpenblumen', 'Edelweiss', 'frage',
   'Die weissen «Sterne» des Edelweiss sehen aus wie Blütenblätter. Sind das wirklich die Blüten?',
   true, 'choice',
   '["Nein: Es sind filzig behaarte Hochblätter. Die eigentlichen Blüten sind die kleinen gelben Köpfchen in der Mitte.", "Ja: Jeder weisse Stern ist eine einzelne Blüte.", "Nein: Es sind die Samen, die mit dem Wind davonfliegen."]',
   'Nein: Es sind filzig behaarte Hochblätter. Die eigentlichen Blüten sind die kleinen gelben Köpfchen in der Mitte.',
   'Lies die Beschreibung des Edelweiss genau: Wo sitzen die eigentlichen Blüten?',
   'Die weissen «Blütensterne» sind Hochblätter. Ihr dichter Haarfilz schützt vor Austrocknung und starker UV-Strahlung. Das Edelweiss ist in vielen Kantonen geschützt: anschauen und fotografieren, aber nicht pflücken.',
   170),
  ('foehn', 'wetterphaenomene', 'Föhn', 'situation',
   'In Altdorf im Kanton Uri ist es im Februar plötzlich 18 °C warm, es stürmt, und die Berge wirken zum Greifen nah. Im Tessin regnet es zur gleichen Zeit. Wie hängt das zusammen?',
   true, 'free', '[]', '',
   'Suche bei den Wetterphänomenen nach einem warmen Wind, der von den Alpen in die Täler hinunterweht.',
   'Es weht Südföhn. Feuchte Luft steigt an der Alpensüdseite auf und regnet sich dort ab, darum regnet es im Tessin. Auf der Nordseite fällt die trockene Luft ins Reusstal hinunter und erwärmt sich dabei um etwa 1 °C pro 100 Höhenmeter. Darum ist es in Altdorf warm, böig und die Sicht glasklar.',
   180),
  ('buchsbaum', 'schaedlinge', 'Buchsbaumzünsler', 'situation',
   'Der Buchsbaum im Garten deiner Grosseltern ist innert weniger Wochen fast kahl. Im Busch hängen Gespinste und grüne Raupen mit schwarzen Streifen und Punkten. Wer war das?',
   false, 'choice', '["Der Buchsbaumzünsler", "Der Kartoffelkäfer", "Der Japankäfer"]', 'Der Buchsbaumzünsler',
   'Gesucht ist die Raupe eines Nachtfalters, der aus Ostasien eingeschleppt wurde.',
   'Es war der Buchsbaumzünsler. Der Falter kam mit Pflanzenlieferungen aus Ostasien nach Europa. Seine Raupen fressen die Blätter des Buchsbaums und spinnen dabei Gespinste.',
   190),
  ('wels', 'fische', 'Wels', 'raetsel',
   'Ich habe keine Schuppen, ein breites Maul und lange Barteln, mit denen ich nachts meine Beute ertaste. Ich kann über 2 m lang werden und bin der grösste Süsswasserfisch der Schweiz. Wer bin ich?',
   false, 'text', '[]', 'Wels|Waller',
   'Suche bei den Fischen nach dem grössten.',
   'Gesucht war der Wels. Weil er warmes Wasser mag, breitet er sich in Schweizer Seen und Flüssen aus. Er frisst Fische, Frösche und sogar Wasservögel.',
   200),
  ('bernhardiner', 'hunde', 'Bernhardiner', 'raetsel',
   'Mein Name kommt von einem Pass im Wallis. Mönche hielten meine Vorfahren, damit sie Reisende begleiteten und Verschüttete im Schnee suchten. Der berühmteste von uns hiess Barry. Wer bin ich?',
   false, 'text', '[]', 'Bernhardiner|Bernhardinerhund',
   'Der Pass heisst Grosser St. Bernhard.',
   'Gesucht war der Bernhardiner. Barry soll über 40 Menschen gerettet haben. Das Fässchen um den Hals ist allerdings eine Legende.',
   210),
  ('giltsteinofen', 'steine', 'Speckstein (Giltstein)', 'situation',
   'In einem alten Bündner Haus steht ein Ofen aus grünlich-grauem Stein. Stunden nachdem das Feuer erloschen ist, ist er immer noch warm. Aus welchem Stein ist er wohl gebaut, und warum eignet sich dieser Stein so gut?',
   true, 'free', '[]', '',
   'Suche bei den Steinen nach einem sehr weichen Gestein, aus dem man Öfen baute.',
   'Der Ofen ist aus Speckstein, auch Giltstein genannt. Speckstein speichert Wärme lange und gibt sie langsam wieder ab. Weil er sehr weich ist, lässt er sich gut bearbeiten. Im Bergell wurden daraus sogar Kochtöpfe gedrechselt.',
   220),
  ('rheinfall', 'naturwunder', 'Rheinfall', 'frage',
   'Der Rheinfall gilt als grösster Wasserfall Europas. Was ist an ihm so gross?',
   true, 'choice',
   '["Die Breite und die Wassermenge: Er ist 150 m breit, aber nur 23 m hoch.", "Die Höhe: Das Wasser stürzt über 300 m in die Tiefe.", "Die Länge: Er fällt über mehrere Kilometer in vielen Stufen."]',
   'Die Breite und die Wassermenge: Er ist 150 m breit, aber nur 23 m hoch.',
   'Vergleiche Höhe und Breite im Steckbrief des Rheinfalls.',
   'Der Rheinfall ist nicht besonders hoch, aber sehr breit und wasserreich: Im Sommer fliessen im Durchschnitt rund 600 m³ Wasser pro Sekunde. Das sind etwa 4000 volle Badewannen, jede Sekunde!',
   230),
  ('zittergras', 'graeser', 'Zittergras', 'raetsel',
   'Meine herzförmigen Ährchen hängen an haarfeinen Stielen und bewegen sich schon beim leisesten Wind. Mein Name verrät, was sie dann tun. Ich wachse in mageren Wiesen. Wer bin ich?',
   false, 'text', '[]', 'Zittergras',
   'Was tun die Ährchen im Wind? Hänge «-gras» an.',
   'Gesucht war das Zittergras. Weil es nur in mageren, ungedüngten Wiesen wächst, zeigt es artenreiches Grünland an.',
   240),
  ('regenbogen', 'wetterphaenomene', 'Regenbogen', 'frage',
   'Nach einem Gewitter scheint die Sonne wieder, und es regnet noch ein bisschen. Du willst einen Regenbogen sehen. Wohin schaust du?',
   true, 'choice',
   '["Weg von der Sonne: Die Sonne muss in meinem Rücken stehen, der Regen vor mir.", "Direkt zur Sonne hin.", "Senkrecht nach oben."]',
   'Weg von der Sonne: Die Sonne muss in meinem Rücken stehen, der Regen vor mir.',
   'Lies im Steckbrief des Regenbogens die Zeile «Bedingung».',
   'Einen Regenbogen sieht man nur, wenn die Sonne im Rücken steht und vor einem Regen fällt. Das Sonnenlicht wird in den Regentropfen gebrochen und zurückgeworfen und dabei in seine Farben zerlegt: aussen Rot, innen Violett.',
   250)
  ) as t(id, cat, entry, kind, question, guess, answer_type, choices, answer, hint, explanation, sort)
 where exists (select 1 from public.categories c where c.id = t.cat)
on conflict (id) do nothing;

update public.app_meta set schema_version = 21, updated_at = now();

commit;

-- Kontrolle: 25 Aufträge, bei allen ist der Eintrag gefunden (eintrag_fehlt = 0)
select count(*) as auftraege, count(*) filter (where entry_id is null) as eintrag_fehlt from public.tasks;
