-- Neue Kategorien Spezialitäten, Geschichte und Politik (Version 2.18.0), je 16 Einträge aus der ganzen Schweiz,
-- davon 3 bzw. 4 aus dem Kanton Glarus (dem Kanton zugeordnet, bestätigt). Die Landsgemeinde wechselt von den
-- Sehenswürdigkeiten zu Politik (behält ihre Bilder und Beschriftungen).
-- Die Kategorien werden ausgeblendet angelegt: zuerst «Fehlende Bilder von Wikimedia übernehmen», durchsehen,
-- dann links in der Verwaltung einblenden.
-- Einmal im Supabase-Dashboard unter «SQL Editor» ausführen. Lässt sich gefahrlos mehrmals ausführen.

begin;

insert into public.categories (id, name, description, goal, latin, labels, visible, sort)
select v.id, v.name, v.description, v.goal, false, v.labels, false,
       (select coalesce(max(sort), 0) from public.categories) + v.nr
  from (values
  ('spezialitaeten', 'Spezialitäten', 'Typische Gerichte und Leckereien aus der Schweiz',
   'Typische Schweizer Spezialitäten erkennen und wissen, woraus sie bestehen und aus welcher Region sie stammen.',
   array['Gericht', 'Nahaufnahme', 'Zubereitung', 'Herkunft'], 1),
  ('geschichte', 'Geschichte', 'Wichtige Ereignisse und Personen der Schweizer Geschichte',
   'Wichtige Ereignisse und Personen der Schweizer Geschichte zeitlich einordnen und ihre Bedeutung erklären.',
   array['Bild', 'Ort', 'Detail', 'Erinnerung'], 2),
  ('politik', 'Politik', 'So funktioniert die Schweiz: Bund, Kantone und Gemeinden',
   'Erklären, wie die Schweiz regiert wird und wie Bürgerinnen und Bürger mitbestimmen.',
   array['Bild', 'Ort', 'Detail', 'Symbol'], 3)
  ) as v(id, name, description, goal, labels, nr)
on conflict (id) do nothing;

-- Landsgemeinde zu Politik verschieben (eigene Beschriftungen behalten, wie beim Verschieben in der Verwaltung)
update public.categories set cover_entry_id = null
 where id = 'sehenswuerdigkeiten'
   and cover_entry_id in (select id from public.entries where category_id = 'sehenswuerdigkeiten' and name = 'Landsgemeinde');
update public.entries
   set category_id = 'politik', sort = 13,
       labels = coalesce(labels, array['Ansicht', 'Detail', 'Umgebung', 'Stimmung'])
 where category_id = 'sehenswuerdigkeiten' and name = 'Landsgemeinde';

with neu(cat, name, subtitle, description, facts, terms, wp, nr, gl, note) as (values
  -- SPEZIALITÄTEN (Gericht, Nahaufnahme, Zubereitung, Herkunft)
  ('spezialitaeten', 'Fondue', 'Käsegericht, ganze Schweiz',
   'Beim Fondue tunkt man Brotwürfel an langen Gabeln in geschmolzenen Käse, der im Caquelon über einem Rechaud warm bleibt. Der Käse wird mit Weisswein und etwas Stärke geschmolzen, oft kommt ein Schuss Kirsch dazu. Bekannt ist das «Moitié-Moitié» aus Gruyère und Vacherin fribourgeois. Ab den 1930er-Jahren warb die Schweizerische Käseunion dafür, so wurde es zum Nationalgericht.',
   '[{"k":"Hauptzutat","v":"Käse, z. B. Gruyère und Vacherin"},{"k":"Gefäss","v":"Caquelon"},{"k":"Beilage","v":"Brotwürfel"}]',
   array['cheese fondue caquelon', 'fondue bread fork', 'Gruyère cheese wheel'], 'Fondue', 1, false, ''),
  ('spezialitaeten', 'Raclette', 'Käsegericht, Wallis',
   'Für Raclette wird ein halber Käselaib erhitzt und die geschmolzene Schicht auf den Teller geschabt. Dazu gibt es «Gschwellti», Kartoffeln in der Schale, Essiggurken und Silberzwiebeln. Das Gericht stammt aus dem Wallis; «racler» heisst auf Französisch «schaben». Der Walliser Raclettekäse ist als AOP geschützt.',
   '[{"k":"Herkunft","v":"Wallis"},{"k":"Beilagen","v":"Gschwellti, Essiggurken, Silberzwiebeln"},{"k":"Name","v":"von französisch «racler» (schaben)"}]',
   array['raclette cheese melting', 'raclette potatoes pickles', 'Valais alp cheese'], 'Raclette', 2, false, ''),
  ('spezialitaeten', 'Rösti', 'Kartoffelgericht, Bern',
   'Rösti besteht aus geraffelten Kartoffeln, die in Butter oder Fett zu einem goldbraunen Fladen gebraten werden. Ursprünglich war sie ein Bauernfrühstück im Kanton Bern. Heute isst man sie in der ganzen Schweiz, etwa zu Zürcher Geschnetzeltem. Der «Röstigraben» bezeichnet scherzhaft die Grenze zwischen Deutschschweiz und Romandie.',
   '[{"k":"Hauptzutat","v":"Kartoffeln"},{"k":"Herkunft","v":"Kanton Bern"},{"k":"Besonderes","v":"gab dem «Röstigraben» den Namen"}]',
   array['Rösti pan', 'grated potatoes', 'Rösti with fried egg'], 'Rösti', 3, false, ''),
  ('spezialitaeten', 'Zürcher Geschnetzeltes', 'Fleischgericht, Zürich',
   'Für das Zürcher Geschnetzelte werden dünne Streifen Kalbfleisch kurz angebraten und in einer Rahmsauce mit Champignons und Weisswein serviert. Klassisch gehört eine Rösti dazu. Es ist eines der bekanntesten Gerichte der Zürcher Küche.',
   '[{"k":"Hauptzutat","v":"Kalbfleisch"},{"k":"Sauce","v":"Rahm, Weisswein, Champignons"},{"k":"Beilage","v":"Rösti"}]',
   array['Zürcher Geschnetzeltes Rösti', 'veal cream sauce mushrooms', 'Zürich old town'], 'Zürcher Geschnetzeltes', 4, false, ''),
  ('spezialitaeten', 'Älplermagronen', 'Teigwarengericht, Zentralschweiz',
   'Älplermagronen sind ein Gericht der Älplerinnen und Älpler: Magronen (Teigwaren), Kartoffeln, Käse und Rahm werden zusammen gekocht und mit gerösteten Zwiebeln bestreut. Dazu isst man Apfelmus. Alles, was es dafür braucht, hatte man auf der Alp zur Hand.',
   '[{"k":"Zutaten","v":"Teigwaren, Kartoffeln, Käse, Rahm"},{"k":"Beilage","v":"Apfelmus"},{"k":"Herkunft","v":"Alpen der Zentralschweiz"}]',
   array['Älplermagronen apple sauce', 'macaroni potatoes cheese onions', 'Swiss alp hut'], 'Älplermagronen', 5, false, ''),
  ('spezialitaeten', 'Birchermüesli', 'Frühstück, Zürich',
   'Das Birchermüesli erfand der Zürcher Arzt Maximilian Bircher-Benner um 1900 als gesunde Kost für seine Patienten. Ursprünglich bestand es vor allem aus geriebenem Apfel mit eingeweichten Haferflocken, Nüssen, Zitronensaft und gezuckerter Kondensmilch. Heute kennt man es auf der ganzen Welt.',
   '[{"k":"Erfinder","v":"Maximilian Bircher-Benner"},{"k":"Zeit","v":"um 1900"},{"k":"Hauptzutaten","v":"Äpfel, Haferflocken, Nüsse"}]',
   array['Bircher muesli', 'rolled oats apple', 'Maximilian Bircher-Benner'], 'Muesli', 6, false, ''),
  ('spezialitaeten', 'Basler Läckerli', 'Gebäck, Basel',
   'Basler Läckerli sind harte, rechteckige Lebkuchen aus Honig, Mandeln, Haselnüssen, kandierten Früchten und Kirsch, überzogen mit einer dünnen Zuckerglasur. Sie werden in Basel seit Jahrhunderten gebacken. Lange gelagert, werden sie weicher.',
   '[{"k":"Zutaten","v":"Honig, Mandeln, kandierte Früchte, Kirsch"},{"k":"Herkunft","v":"Basel"},{"k":"Form","v":"rechteckig mit Zuckerglasur"}]',
   array['Basler Läckerli', 'Läckerli honey almonds', 'Basel old town'], 'Basler Läckerli', 7, false, ''),
  ('spezialitaeten', 'Zuger Kirschtorte', 'Torte, Zug',
   'Die Zuger Kirschtorte besteht aus einem mit Kirsch getränkten Biskuit zwischen zwei Böden aus Nussbaiser, bestrichen mit Buttercreme und bestreut mit Mandeln und Puderzucker. Der Konditor Heinrich Höhn entwickelte sie in Zug; 1915 erschien die erste Werbung für sie. So heissen darf sie nur, wenn sie im Kanton Zug mit Zuger Kirsch hergestellt wird.',
   '[{"k":"Erfinder","v":"Heinrich Höhn"},{"k":"Erstmals beworben","v":"1915"},{"k":"Hauptzutat","v":"Zuger Kirsch"}]',
   array['Zuger Kirschtorte slice', 'Kirsch cherry brandy', 'Zug lake'], 'Zuger Kirschtorte', 8, false, ''),
  ('spezialitaeten', 'Bündner Nusstorte', 'Gebäck, Graubünden',
   'Die Bündner Nusstorte ist ein Mürbeteiggebäck, gefüllt mit karamellisierten Baumnüssen und Rahm. Ihre heutige Form entstand im 20. Jahrhundert im Engadin. Viele Engadiner arbeiteten früher als Zuckerbäcker in ganz Europa und brachten Rezepte mit nach Hause. Wer die Torte genau erfunden hat, ist umstritten.',
   '[{"k":"Füllung","v":"karamellisierte Baumnüsse, Zucker, Rahm"},{"k":"Teig","v":"Mürbeteig"},{"k":"Herkunft","v":"Engadin"}]',
   array['Bündner Nusstorte slice', 'walnuts caramel', 'Engadin village'], 'Bündner Nusstorte', 9, false, ''),
  ('spezialitaeten', 'Berner Platte', 'Fleischgericht, Bern',
   'Die Berner Platte ist eine grosse Platte mit verschiedenem Fleisch, Speck und Würsten, dazu Sauerkraut, Bohnen und Salzkartoffeln. Der Überlieferung nach tischten die Berner sie 1798 erstmals auf, um den Sieg über die Franzosen bei Neuenegg zu feiern. Bis heute ist sie ein Essen für grosse Runden.',
   '[{"k":"Zutaten","v":"Fleisch, Speck, Würste"},{"k":"Beilagen","v":"Sauerkraut, Bohnen, Kartoffeln"},{"k":"Überlieferung","v":"Sieg bei Neuenegg 1798"}]',
   array['Berner Platte', 'sauerkraut sausages bacon', 'Bern old town'], 'Berner Platte', 10, false, ''),
  ('spezialitaeten', 'Luzerner Chügelipastete', 'Pastete, Luzern',
   'Die Luzerner Chügelipastete ist eine grosse Blätterteigpastete, gefüllt mit Kügelchen aus Kalbsbrät, den «Chügeli», mit Kalbfleisch, Champignons und einer Rahmsauce. Oft kommen Rosinen dazu. Sie ist ein typisches Festessen der Luzerner Küche.',
   '[{"k":"Teig","v":"Blätterteig"},{"k":"Füllung","v":"Brätkügelchen, Kalbfleisch, Champignons, Rahmsauce"},{"k":"Herkunft","v":"Luzern"}]',
   array['Luzerner Chügelipastete', 'vol-au-vent puff pastry', 'Lucerne old town'], null, 11, false, ''),
  ('spezialitaeten', 'St. Galler Bratwurst', 'Wurst, St. Gallen',
   'Die St. Galler Bratwurst ist eine helle Wurst aus Kalbfleisch, Schweinefleisch, Speck und Milch. Schon ein Zunftreglement von 1438 schrieb vor, was hineingehört. Traditionell isst man sie ohne Senf, dafür mit einem knusprigen «Bürli». Sie ist als IGP geschützt.',
   '[{"k":"Zutaten","v":"Kalbfleisch, Schweinefleisch, Speck, Milch"},{"k":"Tradition","v":"ohne Senf, mit Bürli"},{"k":"Schutz","v":"IGP"}]',
   array['St. Galler Bratwurst', 'Bratwurst grill', 'St. Gallen old town'], 'St. Galler Bratwurst', 12, false, ''),
  ('spezialitaeten', 'Polenta', 'Maisgericht, Tessin',
   'Polenta ist ein Brei aus Maisgriess, der lange gerührt wird, bis er dick und fest ist. Im Tessin war sie früher das tägliche Essen der Bergbevölkerung. Traditionell kocht man sie im Kupferkessel über dem Feuer. Dazu isst man Käse, Ragout oder Pilze.',
   '[{"k":"Hauptzutat","v":"Maisgriess"},{"k":"Herkunft","v":"Tessin"},{"k":"Beilagen","v":"Ragout, Käse, Pilze"}]',
   array['polenta copper pot', 'polenta ragout', 'Ticino grotto'], 'Polenta', 13, false, ''),
  ('spezialitaeten', 'Schabziger', 'Kräuterkäse, Glarus',
   'Der Schabziger ist ein grüner, kegelförmiger Kräuterkäse aus dem Glarnerland. Er wird aus entrahmter Kuhmilch hergestellt; Schabzigerklee gibt ihm die Farbe und den würzigen Geschmack. Schon 1463 legte die Glarner Landsgemeinde Regeln für Herstellung und Kennzeichnung fest, darum gilt er als eines der ältesten Markenprodukte der Schweiz. Man isst ihn gerieben über Teigwaren oder mit Butter vermischt als «Anke-Ziger» auf Brot.',
   '[{"k":"Milch","v":"entrahmte Kuhmilch"},{"k":"Gewürz","v":"Schabzigerklee"},{"k":"Form","v":"Kegel («Stöckli»)"},{"k":"Regeln","v":"seit 1463"}]',
   array['Schabziger cheese', 'Trigonella caerulea', 'Glarus'], 'Sapsago', 14, true, 'Das bekannteste Glarner Produkt, hergestellt in Glarus.'),
  ('spezialitaeten', 'Glarner Kalberwurst', 'Wurst, Glarus',
   'Die Glarner Kalberwurst ist eine helle Brühwurst aus Kalbfleisch, Speck, Milch und Weissbrot, gewürzt mit Pfeffer und Muskat. Brot und Milch machen sie besonders fein. Traditionell gibt es sie mit Zwiebelsauce, Kartoffelstock und gedörrten Zwetschgen. Sie ist als IGP geschützt.',
   '[{"k":"Zutaten","v":"Kalbfleisch, Speck, Milch, Weissbrot"},{"k":"Beilagen","v":"Zwiebelsauce, Kartoffelstock, Dörrzwetschgen"},{"k":"Schutz","v":"IGP"}]',
   array['Glarner Kalberwurst', 'mashed potatoes onion sauce', 'Glarus'], null, 15, true, ''),
  ('spezialitaeten', 'Glarner Pastete', 'Gebäck, Glarus',
   'Die Glarner Pastete ist ein Blätterteiggebäck, zur einen Hälfte mit Mandelmasse, zur anderen mit Zwetschgenmus gefüllt. Ihre Herkunft wird mit Glarner Offizieren im Solddienst in Frankreich verbunden, wo Pasteten meist mit Fleisch gefüllt waren. Oft trägt sie einen Fridolin aus Marzipan. Kleine Pasteten heissen «Beggeli».',
   '[{"k":"Teig","v":"Blätterteig"},{"k":"Füllung","v":"halb Mandeln, halb Zwetschgen"},{"k":"Verzierung","v":"oft ein Fridolin aus Marzipan"}]',
   array['Glarner Pastete', 'puff pastry almond plum', 'Glarus'], null, 16, true, ''),

  -- GESCHICHTE (Bild, Ort, Detail, Erinnerung)
  ('geschichte', 'Bundesbrief 1291', '1291, Schwyz',
   'Der Bundesbrief ist ein Bündnis zwischen Uri, Schwyz und Unterwalden, datiert auf Anfang August 1291. Die drei Talschaften versprachen sich gegenseitig Hilfe gegen Angriffe von aussen. Später wurde er zum Gründungsdokument der Eidgenossenschaft; darum feiert die Schweiz am 1. August ihren Nationalfeiertag. Das Original liegt im Bundesbriefmuseum in Schwyz.',
   '[{"k":"Datum","v":"Anfang August 1291"},{"k":"Partner","v":"Uri, Schwyz, Unterwalden"},{"k":"Heute","v":"Bundesbriefmuseum Schwyz"}]',
   array['Bundesbrief 1291', 'Bundesbriefmuseum Schwyz', 'Swiss National Day fireworks'], 'Federal Charter of 1291', 1, false, ''),
  ('geschichte', 'Wilhelm Tell', 'Sage, Uri',
   'Wilhelm Tell ist der bekannteste Held der Schweiz. Laut der Sage musste er in Altdorf mit der Armbrust einen Apfel vom Kopf seines Sohnes schiessen, weil er den Hut des Landvogts Gessler nicht gegrüsst hatte. Später tötete er Gessler in der Hohlen Gasse bei Küssnacht. Dass Tell wirklich gelebt hat, ist nicht belegt; Friedrich Schiller machte die Geschichte 1804 mit seinem Drama weltberühmt.',
   '[{"k":"Art","v":"Sage"},{"k":"Orte","v":"Altdorf, Hohle Gasse bei Küssnacht"},{"k":"Bekannt durch","v":"Schillers «Wilhelm Tell» (1804)"}]',
   array['Telldenkmal Altdorf', 'Hohle Gasse Küssnacht', 'crossbow apple'], 'William Tell', 2, false, ''),
  ('geschichte', 'Schlacht am Morgarten', '1315, Zug / Schwyz',
   'Am 15. November 1315 besiegten die Schwyzer mit Verbündeten aus Uri und Unterwalden am Morgarten ein habsburgisches Ritterheer. Sie lauerten den Rittern auf dem schmalen Weg zwischen Ägerisee und Berghang auf. Der Sieg stärkte den Bund der drei Länder.',
   '[{"k":"Datum","v":"15. November 1315"},{"k":"Gegner","v":"Habsburg"},{"k":"Ort","v":"am Ägerisee"}]',
   array['Morgarten monument', 'Ägerisee', 'Schlacht am Morgarten'], 'Battle of Morgarten', 3, false, ''),
  ('geschichte', 'Schlacht bei Sempach', '1386, Luzern',
   'Am 9. Juli 1386 besiegten die Eidgenossen bei Sempach ein habsburgisches Heer; Herzog Leopold III. von Österreich fiel in der Schlacht. Nach einer Sage öffnete Arnold Winkelried den Eidgenossen eine Gasse in die Lanzen der Ritter. Ob es Winkelried wirklich gab, ist umstritten.',
   '[{"k":"Datum","v":"9. Juli 1386"},{"k":"Gegner","v":"Herzog Leopold III. von Habsburg"},{"k":"Held der Sage","v":"Arnold Winkelried"}]',
   array['Schlachtkapelle Sempach', 'Winkelried monument Stans', 'Sempachersee'], 'Battle of Sempach', 4, false, ''),
  ('geschichte', 'Schlacht bei Näfels', '1388, Näfels',
   'Am 9. April 1388 besiegten die Glarner bei Näfels ein viel grösseres habsburgisches Heer. Sie kämpften unter dem Banner mit dem heiligen Fridolin. Der Sieg sicherte die Freiheit des Glarnerlandes und gilt als Ende der damaligen Kämpfe zwischen Habsburg und den Eidgenossen. Bis heute erinnert die Näfelser Fahrt jedes Jahr am ersten Donnerstag im April daran.',
   '[{"k":"Datum","v":"9. April 1388"},{"k":"Gegner","v":"Habsburg"},{"k":"Gedenktag","v":"Näfelser Fahrt (erster Donnerstag im April)"}]',
   array['Näfelser Fahrt', 'Schlachtdenkmal Näfels', 'Näfels'], 'Battle of Näfels', 5, true, 'Das wichtigste Ereignis der Glarner Geschichte, gefeiert an der Näfelser Fahrt.'),
  ('geschichte', 'Schlacht bei Marignano', '1515, Italien',
   'Am 13. und 14. September 1515 verloren die Eidgenossen bei Marignano südlich von Mailand gegen den französischen König Franz I. Tausende Söldner starben. Danach gaben die Eidgenossen ihre Eroberungspolitik auf; Marignano gilt als ein Anfang der Schweizer Neutralität.',
   '[{"k":"Datum","v":"13./14. September 1515"},{"k":"Gegner","v":"Frankreich (Franz I.)"},{"k":"Folge","v":"Ende der Eroberungspolitik"}]',
   array['Battle of Marignano painting', 'Swiss mercenaries pikemen', 'Marignano'], 'Battle of Marignano', 6, false, ''),
  ('geschichte', 'Huldrych Zwingli', 'Reformator, Zürich',
   'Huldrych Zwingli war ab 1519 Pfarrer am Grossmünster in Zürich und führte dort die Reformation ein. Er wollte nur nach der Bibel predigen und lehnte Heiligenbilder und den Ablass ab. 1531 fiel er in der Schlacht bei Kappel gegen die katholischen Orte. Zuvor war er zehn Jahre Pfarrer in Glarus.',
   '[{"k":"Lebensdaten","v":"1484–1531"},{"k":"Wirkungsort","v":"Grossmünster Zürich (ab 1519)"},{"k":"Tod","v":"Schlacht bei Kappel 1531"}]',
   array['Zwingli monument Zürich', 'Grossmünster Zürich', 'Zwingli portrait'], 'Huldrych Zwingli', 7, true, 'War von 1506 bis 1516 Pfarrer in Glarus.'),
  ('geschichte', 'Helvetische Republik', '1798–1803',
   '1798 eroberten französische Truppen die Alte Eidgenossenschaft. Frankreich machte daraus die Helvetische Republik, einen Einheitsstaat mit gleichen Rechten für alle Bürger; die Untertanengebiete wurden frei. Weil es viel Widerstand gab, ersetzte Napoleon sie 1803 durch die Mediationsakte.',
   '[{"k":"Zeit","v":"1798–1803"},{"k":"Form","v":"Einheitsstaat nach französischem Vorbild"},{"k":"Ende","v":"Mediationsakte 1803"}]',
   array['Helvetic Republic flag', 'French invasion Switzerland 1798', 'Napoleon Act of Mediation'], 'Helvetic Republic', 8, false, ''),
  ('geschichte', 'Bundesverfassung 1848', '1848, Bern',
   'Nach dem kurzen Sonderbundskrieg von 1847 gab sich die Schweiz am 12. September 1848 eine Bundesverfassung. Aus dem lockeren Staatenbund wurde ein Bundesstaat mit Parlament und Bundesrat; bald folgten eine gemeinsame Post und der Franken als Währung. Bern wurde Bundesstadt. Die Verfassung gilt in überarbeiteter Form bis heute.',
   '[{"k":"Datum","v":"12. September 1848"},{"k":"Vorher","v":"Sonderbundskrieg 1847"},{"k":"Neu","v":"Bundesrat, Nationalrat und Ständerat"}]',
   array['Swiss Federal Constitution 1848', 'Bundeshaus Bern', 'Sonderbundskrieg'], 'Federal Constitution of Switzerland', 9, false, ''),
  ('geschichte', 'Henri Dunant', 'Rotes Kreuz, Genf',
   'Der Genfer Henri Dunant erlebte 1859 das Leid der Verwundeten nach der Schlacht bei Solferino in Italien. In seinem Buch «Eine Erinnerung an Solferino» forderte er Hilfe für alle Verwundeten, egal auf welcher Seite. 1863 entstand in Genf das Internationale Komitee vom Roten Kreuz. 1901 erhielt Dunant den ersten Friedensnobelpreis.',
   '[{"k":"Lebensdaten","v":"1828–1910"},{"k":"Gründung IKRK","v":"1863 in Genf"},{"k":"Auszeichnung","v":"Friedensnobelpreis 1901"}]',
   array['Red Cross museum Geneva', 'Henry Dunant portrait', 'Red Cross emblem'], 'Henry Dunant', 10, false, ''),
  ('geschichte', 'Gotthardtunnel', '1882, Uri / Tessin',
   '1882 wurde der Eisenbahntunnel durch den Gotthard zwischen Göschenen und Airolo eröffnet; mit 15 km war er damals der längste Tunnel der Welt. Beim Bau starben viele Arbeiter, auch der Bauunternehmer Louis Favre starb 1879 im Tunnel. Seit 2016 fahren die meisten Züge durch den 57 km langen Gotthard-Basistunnel.',
   '[{"k":"Eröffnung","v":"1882"},{"k":"Länge","v":"15 km"},{"k":"Nachfolger","v":"Gotthard-Basistunnel, 57 km (2016)"}]',
   array['Gotthard tunnel portal Göschenen', 'Louis Favre', 'Gotthard railway'], 'Gotthard Rail Tunnel', 11, false, ''),
  ('geschichte', 'Brand von Glarus', '1861, Glarus',
   'In der Nacht vom 10. auf den 11. Mai 1861 zerstörte ein Grossbrand rund zwei Drittel der Stadt Glarus; ein heftiger Föhn trieb das Feuer durch die Gassen. Rund 3000 Menschen verloren ihr Zuhause. Hilfe kam aus der ganzen Schweiz und dem Ausland. Die Stadt wurde mit geraden Strassen nach einem Rasterplan neu gebaut, was man bis heute sieht.',
   '[{"k":"Datum","v":"10./11. Mai 1861"},{"k":"Zerstört","v":"rund 600 Gebäude"},{"k":"Wiederaufbau","v":"Strassen nach Rasterplan"}]',
   array['Brand von Glarus 1861', 'Glarus Rathaus', 'Glarus town aerial'], null, 12, true, 'Prägt mit dem Rasterplan das Stadtbild von Glarus bis heute.'),
  ('geschichte', 'Bergsturz von Elm', '1881, Elm',
   'Am 11. September 1881 stürzten bei Elm rund 10 Millionen m³ Fels vom Tschingelberg ins Tal und begruben 114 Menschen und 83 Gebäude. Ursache war der unvorsichtige Abbau von Schiefer am Fuss des Berges. Der Geologe Albert Heim untersuchte den Bergsturz genau; seine Forschung half, solche Gefahren besser zu verstehen.',
   '[{"k":"Datum","v":"11. September 1881"},{"k":"Todesopfer","v":"114"},{"k":"Ursache","v":"Schieferabbau am Tschingelberg"}]',
   array['Bergsturz Elm', 'Tschingelberg Elm', 'Elm village'], 'Rockslide of Elm', 13, true, ''),
  ('geschichte', 'Heiliger Fridolin', 'Glaubensbote, Säckingen / Glarus',
   'Fridolin war ein Glaubensbote, der wohl im 6. oder 7. Jahrhundert das Kloster Säckingen am Rhein gründete. Nach der Legende schenkte ihm Urso Land im Linthtal; als dessen Bruder die Schenkung bestritt, holte Fridolin den toten Urso als Zeugen vor Gericht. Er ist der Landespatron von Glarus und steht im Glarner Wappen. Am Fridolinstag, dem 6. März, brennen im Glarnerland die «Fridlisfüür».',
   '[{"k":"Gedenktag","v":"6. März"},{"k":"Kloster","v":"Säckingen"},{"k":"Legende","v":"der tote Urso als Zeuge"},{"k":"Heute","v":"im Glarner Wappen"}]',
   array['Fridolin Glarus', 'Fridolinsmünster Bad Säckingen', 'Fridolin Urso'], 'Fridolin of Säckingen', 14, true, 'Landespatron von Glarus.'),
  ('geschichte', 'Landesstreik 1918', '1918, ganze Schweiz',
   'Vom 12. bis 14. November 1918 legten rund 250 000 Arbeiterinnen und Arbeiter in der ganzen Schweiz die Arbeit nieder. Nach dem Ersten Weltkrieg herrschten Not und Teuerung. Gefordert wurden unter anderem die 48-Stunden-Woche, eine Altersversicherung, das Frauenstimmrecht und die Wahl des Nationalrats nach Proporz. Der Bundesrat setzte die Armee ein, der Streik wurde abgebrochen; einige Forderungen wurden später erfüllt.',
   '[{"k":"Datum","v":"12.–14. November 1918"},{"k":"Beteiligte","v":"rund 250 000"},{"k":"Später erfüllt","v":"Proporzwahl 1919, AHV 1948"}]',
   array['Landesstreik 1918', 'Swiss general strike 1918 soldiers', 'Zürich Paradeplatz 1918'], 'Swiss general strike of 1918', 15, false, ''),
  ('geschichte', 'Rütlirapport 1940', '1940, Rütli',
   'Am 25. Juli 1940, als die Schweiz von den Achsenmächten umgeben war, versammelte General Henri Guisan die höheren Offiziere der Armee auf dem Rütli. Er erklärte, die Schweiz werde sich verteidigen, und stellte den Plan des Réduits vor: Die Armee sollte sich in die Alpen zurückziehen. Der Rapport stärkte den Widerstandswillen im Land.',
   '[{"k":"Datum","v":"25. Juli 1940"},{"k":"Leitung","v":"General Henri Guisan"},{"k":"Plan","v":"Réduit in den Alpen"}]',
   array['Henri Guisan', 'Rütli meadow', 'Réduit fortress'], 'Henri Guisan', 16, false, ''),

  -- POLITIK (Bild, Ort, Detail, Symbol); die Landsgemeinde kommt aus den Sehenswürdigkeiten dazu (sort 13)
  ('politik', 'Bundesrat', 'Regierung, Bern',
   'Der Bundesrat ist die Regierung der Schweiz. Er hat sieben gleichberechtigte Mitglieder, die gemeinsam entscheiden; jedes leitet ein Departement. Die Bundesversammlung wählt sie für vier Jahre. Seit 1959 sind die grössten Parteien gemeinsam im Bundesrat vertreten; ihre Verteilung nannte man lange «Zauberformel».',
   '[{"k":"Mitglieder","v":"7"},{"k":"Wahl","v":"durch die Bundesversammlung, für 4 Jahre"},{"k":"Sitz","v":"Bundeshaus, Bern"}]',
   array['Swiss Federal Council', 'Bundeshaus Bern', 'Bundesratszimmer'], 'Federal Council (Switzerland)', 1, false, ''),
  ('politik', 'Nationalrat', 'Parlament, Bern',
   'Der Nationalrat ist die grosse Kammer des Schweizer Parlaments. Seine 200 Mitglieder vertreten das Volk; jeder Kanton hat so viele Sitze, wie es seiner Bevölkerung entspricht, mindestens aber einen. Gewählt wird alle vier Jahre nach Proporz. Zusammen mit dem Ständerat beschliesst er die Gesetze des Bundes.',
   '[{"k":"Mitglieder","v":"200"},{"k":"Wahl","v":"alle 4 Jahre, nach Proporz"},{"k":"Sitze","v":"nach Bevölkerung, mindestens 1 pro Kanton"}]',
   array['National Council chamber Bern', 'Bundeshaus Bern', 'Swiss parliament session'], 'National Council (Switzerland)', 2, true, 'Der Kanton Glarus hat einen Sitz im Nationalrat.'),
  ('politik', 'Ständerat', 'Parlament, Bern',
   'Der Ständerat ist die kleine Kammer des Parlaments und vertritt die Kantone. Jeder Kanton hat zwei Sitze, die sechs früheren Halbkantone je einen; zusammen sind es 46. Ein Gesetz gilt nur, wenn Nationalrat und Ständerat zugestimmt haben.',
   '[{"k":"Mitglieder","v":"46"},{"k":"Pro Kanton","v":"2 (frühere Halbkantone 1)"},{"k":"Aufgabe","v":"vertritt die Kantone"}]',
   array['Council of States chamber Bern', 'Bundeshaus Bern', 'Swiss cantons flags'], 'Council of States (Switzerland)', 3, false, ''),
  ('politik', 'Bundespräsident', 'Vorsitz im Bundesrat',
   'Jedes Jahr wählt die Bundesversammlung ein Mitglied des Bundesrats zur Bundespräsidentin oder zum Bundespräsidenten. Diese Person leitet die Sitzungen des Bundesrats und vertritt die Schweiz bei offiziellen Anlässen. Sie ist aber nicht Chefin oder Chef der anderen Bundesräte. Das Amt wechselt jedes Jahr.',
   '[{"k":"Amtszeit","v":"1 Jahr"},{"k":"Wahl","v":"durch die Bundesversammlung"},{"k":"Aufgaben","v":"Sitzungen leiten, Schweiz vertreten"}]',
   array['President of the Swiss Confederation', 'Bundeshaus Bern', 'Swiss flag'], 'President of the Swiss Confederation', 4, false, ''),
  ('politik', 'Bundesgericht', 'Lausanne',
   'Das Bundesgericht ist das höchste Gericht der Schweiz. Es entscheidet als letzte Instanz, wenn Urteile kantonaler Gerichte angefochten werden. Sein Sitz ist in Lausanne, eine Abteilung arbeitet in Luzern. Die Bundesversammlung wählt die Richterinnen und Richter.',
   '[{"k":"Sitz","v":"Lausanne (und Luzern)"},{"k":"Aufgabe","v":"höchstes Gericht"},{"k":"Wahl","v":"durch die Bundesversammlung"}]',
   array['Federal Supreme Court Lausanne', 'Mon Repos Lausanne', 'justice scales'], 'Federal Supreme Court of Switzerland', 5, false, ''),
  ('politik', 'Volksinitiative', 'Mitbestimmen, Bund',
   'Mit einer Volksinitiative können Bürgerinnen und Bürger eine Änderung der Bundesverfassung verlangen. Dafür braucht es 100 000 Unterschriften, gesammelt innert 18 Monaten. Angenommen ist sie nur, wenn das Volk und die Mehrheit der Kantone zustimmen.',
   '[{"k":"Unterschriften","v":"100 000"},{"k":"Frist","v":"18 Monate"},{"k":"Annahme","v":"Volk und Stände"}]',
   array['Swiss popular initiative signatures', 'ballot box Switzerland', 'Swiss vote'], 'Popular initiative (Switzerland)', 6, false, ''),
  ('politik', 'Referendum', 'Mitbestimmen, Bund',
   'Mit dem Referendum kann das Volk über Beschlüsse des Parlaments abstimmen. Gegen ein neues Gesetz kann man mit 50 000 Unterschriften innert 100 Tagen eine Abstimmung verlangen. Änderungen der Verfassung kommen immer vor das Volk. Abgestimmt wird mehrmals im Jahr.',
   '[{"k":"Fakultativ","v":"50 000 Unterschriften in 100 Tagen"},{"k":"Obligatorisch","v":"bei Änderungen der Verfassung"},{"k":"Abstimmungen","v":"mehrmals pro Jahr"}]',
   array['Swiss referendum ballot', 'voting envelope Switzerland', 'Swiss vote'], null, 7, false, ''),
  ('politik', 'Föderalismus', 'Bund, Kantone, Gemeinden',
   'Die Schweiz ist föderalistisch aufgebaut: Die Macht ist auf den Bund, 26 Kantone und über 2000 Gemeinden verteilt. Jeder Kanton hat eine eigene Verfassung, ein Parlament, eine Regierung und Gerichte. Darum sind zum Beispiel Schulen und Steuern von Kanton zu Kanton verschieden.',
   '[{"k":"Ebenen","v":"Bund, Kantone, Gemeinden"},{"k":"Kantone","v":"26"},{"k":"Beispiel","v":"Schulen sind Sache der Kantone"}]',
   array['Swiss cantons map', 'Swiss canton flags', 'Bundeshaus Bern'], 'Cantons of Switzerland', 8, false, ''),
  ('politik', 'Neutralität', 'Aussenpolitik',
   'Die Schweiz ist neutral: Sie beteiligt sich nicht an Kriegen zwischen anderen Staaten und tritt keinem Militärbündnis bei. 1815 anerkannten die europäischen Grossmächte die Neutralität der Schweiz. Trotzdem hat die Schweiz eine Armee, um sich selbst zu verteidigen. Dank der Neutralität finden hier oft internationale Verhandlungen statt.',
   '[{"k":"Anerkannt","v":"1815"},{"k":"Bedeutet","v":"keine Teilnahme an Kriegen, kein Militärbündnis"},{"k":"Folge","v":"Ort für Friedensgespräche"}]',
   array['Palais des Nations Geneva', 'Congress of Vienna 1815', 'Swiss flag'], 'Palace of Nations', 9, false, ''),
  ('politik', 'Frauenstimmrecht', '1971, Bund',
   'Erst am 7. Februar 1971 erhielten die Frauen in der Schweiz auf Bundesebene das Stimm- und Wahlrecht, viel später als in den meisten Ländern Europas. 1959 hatten die Männer es in einer Abstimmung noch abgelehnt. Als letzter Kanton musste Appenzell Innerrhoden das Frauenstimmrecht 1990 auf Befehl des Bundesgerichts einführen.',
   '[{"k":"Bund","v":"seit 1971"},{"k":"Erste Abstimmung","v":"1959 abgelehnt"},{"k":"Letzter Kanton","v":"Appenzell Innerrhoden 1990"}]',
   array['Swiss women suffrage 1971', 'Frauenstimmrecht Schweiz', 'women voting Switzerland'], 'Women''s suffrage in Switzerland', 10, false, ''),
  ('politik', 'Milizsystem', 'Ämter neben dem Beruf',
   'In der Schweiz übernehmen viele Bürgerinnen und Bürger öffentliche Aufgaben neben ihrem Beruf, etwa im Gemeinderat, in Kommissionen oder in der Feuerwehr. Auch die Mitglieder des Parlaments sind keine reinen Berufspolitiker. Man nennt das Milizsystem. Auch die Armee ist eine Milizarmee.',
   '[{"k":"Bedeutung","v":"Ämter neben dem Beruf"},{"k":"Beispiele","v":"Gemeinderat, Feuerwehr, Armee"},{"k":"Parlament","v":"Milizparlament"}]',
   array['Swiss volunteer fire brigade', 'Swiss militia army', 'municipal council meeting'], 'Militia system', 11, false, ''),
  ('politik', 'Gemeindeversammlung', 'Mitbestimmen in der Gemeinde',
   'In vielen Gemeinden entscheiden die Stimmberechtigten an der Gemeindeversammlung selbst über Budget, Steuerfuss und Bauprojekte. Wer kommt, kann mitreden, Anträge stellen und abstimmen. Grössere Gemeinden und Städte haben stattdessen ein Gemeindeparlament.',
   '[{"k":"Wer","v":"alle Stimmberechtigten der Gemeinde"},{"k":"Themen","v":"Budget, Steuern, Bauprojekte"},{"k":"Grössere Orte","v":"Gemeindeparlament"}]',
   array['Gemeindeversammlung', 'Swiss town hall', 'Swiss village'], null, 12, false, ''),
  ('politik', 'Glarner Gemeindereform', '2011, Glarus',
   'An der Landsgemeinde 2006 beschlossen die Glarnerinnen und Glarner überraschend, ihre 25 Gemeinden zu nur drei grossen Gemeinden zusammenzulegen. Regierung und Landrat hatten zehn Gemeinden vorgeschlagen. Seit dem 1. Januar 2011 gibt es Glarus Nord, Glarus und Glarus Süd. Die Reform galt in der ganzen Schweiz als mutiger Schritt.',
   '[{"k":"Beschluss","v":"Landsgemeinde 2006"},{"k":"Vorher","v":"25 Gemeinden"},{"k":"Seit 2011","v":"Glarus Nord, Glarus, Glarus Süd"}]',
   array['Glarus Nord', 'Glarus Süd', 'Landsgemeinde Glarus'], null, 14, true, ''),
  ('politik', 'Stimmrecht ab 16', '2007, Glarus',
   'Seit 2007 dürfen im Kanton Glarus Jugendliche ab 16 Jahren abstimmen und an der Landsgemeinde mitentscheiden, als erste in der Schweiz. Beschlossen hat das die Landsgemeinde selbst. In die meisten Ämter gewählt werden kann man aber erst ab 18. Bei Abstimmungen des Bundes gilt weiterhin 18 Jahre.',
   '[{"k":"Seit","v":"2007"},{"k":"Beschluss","v":"Landsgemeinde Glarus"},{"k":"Bund","v":"Stimmrecht ab 18"}]',
   array['Landsgemeinde Glarus', 'young voters Switzerland', 'Zaunplatz Glarus'], null, 15, true, 'Glarus war der erste Kanton mit Stimmrecht ab 16.'),
  ('politik', 'Landrat Glarus', 'Kantonsparlament, Glarus',
   'Der Landrat ist das Parlament des Kantons Glarus und hat seit 2008 noch 60 Mitglieder. Er berät die Gesetze und bereitet die Geschäfte der Landsgemeinde vor; dort hat das Volk das letzte Wort. Die Regierung, der Regierungsrat, hat fünf Mitglieder. Ihr Präsident heisst Landammann und leitet auch die Landsgemeinde.',
   '[{"k":"Mitglieder","v":"60 (seit 2008)"},{"k":"Regierung","v":"Regierungsrat mit 5 Mitgliedern"},{"k":"Vorsitz","v":"Landammann"}]',
   array['Rathaus Glarus', 'Landrat Glarus', 'Glarus'], null, 16, true, '')
)
insert into public.entries (category_id, name, subtitle, description, facts, search_terms, wp, visible, sort)
select n.cat, n.name, n.subtitle, n.description, n.facts::jsonb, n.terms, n.wp, true, n.nr
  from neu n
 where not exists (select 1 from public.entries e where e.category_id = n.cat and e.name = n.name);

-- Glarner Einträge dem Kanton zuordnen (bestätigt, mit Hinweis), auch Zwingli und Nationalrat
insert into public.entry_regions (entry_id, region_id, note, confirmed)
select e.id, 'glarus', v.note, true
  from public.entries e
  join (values
    ('spezialitaeten', 'Schabziger', 'Das bekannteste Glarner Produkt, hergestellt in Glarus.'),
    ('spezialitaeten', 'Glarner Kalberwurst', ''),
    ('spezialitaeten', 'Glarner Pastete', ''),
    ('geschichte', 'Schlacht bei Näfels', 'Das wichtigste Ereignis der Glarner Geschichte, gefeiert an der Näfelser Fahrt.'),
    ('geschichte', 'Huldrych Zwingli', 'War von 1506 bis 1516 Pfarrer in Glarus.'),
    ('geschichte', 'Brand von Glarus', 'Prägt mit dem Rasterplan das Stadtbild von Glarus bis heute.'),
    ('geschichte', 'Bergsturz von Elm', ''),
    ('geschichte', 'Heiliger Fridolin', 'Landespatron von Glarus.'),
    ('politik', 'Nationalrat', 'Der Kanton Glarus hat einen Sitz im Nationalrat.'),
    ('politik', 'Glarner Gemeindereform', ''),
    ('politik', 'Stimmrecht ab 16', 'Glarus war der erste Kanton mit Stimmrecht ab 16.'),
    ('politik', 'Landrat Glarus', '')
  ) as v(cat, name, note)
    on e.category_id = v.cat and e.name = v.name
on conflict (entry_id, region_id) do nothing;

update public.app_meta set schema_version = 24, updated_at = now();

commit;
