-- Weitere Kantone und Forscheraufträge (Version 2.19.0):
--   Kantone Graubünden, St. Gallen, Zürich und Tessin mit Farben und Zeichen aus dem Wappen (eigene Zeichnungen in icons/),
--   je eine Auswahl bestehender Einträge als Vorschlag (confirmed = false, in der Verwaltung bestätigen oder entfernen),
--   bei einigen mit Hinweis «Im Kanton …».
--   24 neue Forscheraufträge: 8 für Glarus, je 4 für Graubünden, St. Gallen, Zürich und Tessin. Ihre Antwort steht
--   jeweils in einem Eintrag des Kantons, darum erscheinen sie im Kanton und in der ganzen Schweiz.
-- Einmal im Supabase-Dashboard unter «SQL Editor» ausführen. Lässt sich gefahrlos mehrmals ausführen.

begin;

insert into public.regions (id, name, title, code, intro, color, color2, color3, on_color, emblem, sort) values
  ('graubuenden', 'Graubünden', 'Kanton Graubünden', 'GR',
   'Pflanzen, Tiere und Landschaften im grössten Kanton der Schweiz: vom Engadin bis zur Rheinschlucht, vom Steinbock bis zur Arve.',
   '#1f4e9c', '#1b1b1b', '#f4c400', '#ffffff', 'icons/kanton-graubuenden.svg', 20),
  ('st-gallen', 'St. Gallen', 'Kanton St. Gallen', 'SG',
   'Pflanzen, Tiere und Landschaften zwischen Bodensee, Säntis und Walensee.',
   '#00843d', '#ffffff', '#1b1b1b', '#ffffff', 'icons/kanton-st-gallen.svg', 30),
  ('zuerich', 'Zürich', 'Kanton Zürich', 'ZH',
   'Pflanzen, Tiere und Orte rund um den Zürichsee, im Wald und im Garten des Mittellandes.',
   '#0f5fa8', '#ffffff', '#0f5fa8', '#ffffff', 'icons/kanton-zuerich.svg', 40),
  ('tessin', 'Tessin', 'Kanton Tessin', 'TI',
   'Pflanzen, Tiere und Landschaften der Sonnenstube der Schweiz, vom Gotthard bis an den Lago Maggiore.',
   '#d52b1e', '#1f5aa6', '#ffffff', '#ffffff', 'icons/kanton-tessin.svg', 50)
on conflict (id) do nothing;

insert into public.entry_regions (entry_id, region_id, note, confirmed)
select e.id, v.region, v.note, false
  from (values
  -- Graubünden
  ('graubuenden', 'berge', 'Tödi', 'Steht an der Grenze zwischen Graubünden und Glarus.'),
  ('graubuenden', 'berge', 'Piz Bernina', 'Höchster Berg Graubündens.'),
  ('graubuenden', 'berge', 'Hausstock', ''),
  ('graubuenden', 'gewaesser', 'Silsersee', ''),
  ('graubuenden', 'gewaesser', 'Inn', ''),
  ('graubuenden', 'gewaesser', 'Rhein', 'Entsteht in Graubünden aus Vorder- und Hinterrhein.'),
  ('graubuenden', 'naturwunder', 'Viamala-Schlucht', ''),
  ('graubuenden', 'naturwunder', 'Ruinaulta', ''),
  ('graubuenden', 'naturwunder', 'Morteratschgletscher', ''),
  ('graubuenden', 'sehenswuerdigkeiten', 'Landwasserviadukt', ''),
  ('graubuenden', 'sehenswuerdigkeiten', 'Kloster St. Johann', ''),
  ('graubuenden', 'nutztiere', 'Rätisches Grauvieh', ''),
  ('graubuenden', 'nutztiere', 'Bündner Strahlenziege', ''),
  ('graubuenden', 'spezialitaeten', 'Bündner Nusstorte', ''),
  ('graubuenden', 'baeume', 'Arve', ''),
  ('graubuenden', 'baeume', 'Lärche', ''),
  ('graubuenden', 'baeume', 'Edelkastanie', 'Wächst in den Südtälern Bergell und Misox.'),
  ('graubuenden', 'saeugetiere', 'Alpensteinbock', 'Wappentier von Graubünden.'),
  ('graubuenden', 'saeugetiere', 'Gämse', ''),
  ('graubuenden', 'saeugetiere', 'Murmeltier', ''),
  ('graubuenden', 'saeugetiere', 'Rothirsch', ''),
  ('graubuenden', 'saeugetiere', 'Wolf', ''),
  ('graubuenden', 'voegel', 'Bartgeier', ''),
  ('graubuenden', 'voegel', 'Steinadler', ''),
  ('graubuenden', 'voegel', 'Tannenhäher', ''),
  ('graubuenden', 'voegel', 'Alpendohle', ''),
  ('graubuenden', 'alpenblumen', 'Edelweiss', ''),
  ('graubuenden', 'alpenblumen', 'Alpenrose', ''),
  ('graubuenden', 'alpenblumen', 'Stängelloser Enzian', ''),
  ('graubuenden', 'alpenblumen', 'Gletscher-Hahnenfuss', ''),
  ('graubuenden', 'steine', 'Gneis', ''),
  ('graubuenden', 'steine', 'Granit', 'Typisch für das Bergell.'),
  ('graubuenden', 'amphibien', 'Alpensalamander', ''),
  ('graubuenden', 'reptilien', 'Kreuzotter', ''),
  ('graubuenden', 'wetterphaenomene', 'Föhn', ''),
  -- St. Gallen
  ('st-gallen', 'berge', 'Säntis', ''),
  ('st-gallen', 'gewaesser', 'Walensee', 'Das Nordufer mit Quinten gehört zum Kanton St. Gallen.'),
  ('st-gallen', 'gewaesser', 'Bodensee', ''),
  ('st-gallen', 'gewaesser', 'Zürichsee', 'Der Obersee mit Rapperswil gehört zum Teil zum Kanton St. Gallen.'),
  ('st-gallen', 'gewaesser', 'Rhein', 'Fliesst durch das St. Galler Rheintal in den Bodensee.'),
  ('st-gallen', 'gewaesser', 'Linth', 'Der Linthkanal fliesst durch die St. Galler Linthebene.'),
  ('st-gallen', 'naturwunder', 'Taminaschlucht', ''),
  ('st-gallen', 'sehenswuerdigkeiten', 'Stiftsbezirk St. Gallen', ''),
  ('st-gallen', 'spezialitaeten', 'St. Galler Bratwurst', ''),
  ('st-gallen', 'nutztiere', 'Toggenburger Ziege', ''),
  ('st-gallen', 'nutztiere', 'Braunvieh', ''),
  ('st-gallen', 'steine', 'Nagelfluh', 'Der Speer im Toggenburg besteht aus Nagelfluh.'),
  ('st-gallen', 'steine', 'Kalkstein', ''),
  ('st-gallen', 'saeugetiere', 'Gämse', ''),
  ('st-gallen', 'saeugetiere', 'Murmeltier', ''),
  ('st-gallen', 'saeugetiere', 'Reh', ''),
  ('st-gallen', 'voegel', 'Steinadler', ''),
  ('st-gallen', 'voegel', 'Haubentaucher', ''),
  ('st-gallen', 'fische', 'Felchen', ''),
  ('st-gallen', 'fische', 'Bachforelle', ''),
  ('st-gallen', 'alpenblumen', 'Alpenrose', ''),
  ('st-gallen', 'alpenblumen', 'Edelweiss', ''),
  ('st-gallen', 'baeume', 'Buche', ''),
  ('st-gallen', 'baeume', 'Fichte (Rottanne)', ''),
  ('st-gallen', 'wetterphaenomene', 'Föhn', ''),
  -- Zürich
  ('zuerich', 'gewaesser', 'Zürichsee', ''),
  ('zuerich', 'gewaesser', 'Rhein', 'Bildet einen Teil der Nordgrenze des Kantons Zürich.'),
  ('zuerich', 'naturwunder', 'Rheinfall', 'Das Südufer mit Schloss Laufen gehört zum Kanton Zürich.'),
  ('zuerich', 'sehenswuerdigkeiten', 'Grossmünster', ''),
  ('zuerich', 'spezialitaeten', 'Zürcher Geschnetzeltes', ''),
  ('zuerich', 'spezialitaeten', 'Birchermüesli', ''),
  ('zuerich', 'geschichte', 'Huldrych Zwingli', ''),
  ('zuerich', 'steine', 'Sandstein (Molasse)', ''),
  ('zuerich', 'steine', 'Nagelfluh', 'Das Hörnli im Zürcher Oberland besteht aus Nagelfluh.'),
  ('zuerich', 'baeume', 'Buche', ''),
  ('zuerich', 'baeume', 'Stieleiche', ''),
  ('zuerich', 'baeume', 'Hagebuche', ''),
  ('zuerich', 'baeume', 'Feldahorn', ''),
  ('zuerich', 'straeucher', 'Hasel', ''),
  ('zuerich', 'straeucher', 'Weissdorn', ''),
  ('zuerich', 'straeucher', 'Hundsrose', ''),
  ('zuerich', 'saeugetiere', 'Rotfuchs', ''),
  ('zuerich', 'saeugetiere', 'Reh', ''),
  ('zuerich', 'saeugetiere', 'Dachs', ''),
  ('zuerich', 'saeugetiere', 'Igel', ''),
  ('zuerich', 'saeugetiere', 'Eichhörnchen', ''),
  ('zuerich', 'saeugetiere', 'Biber', ''),
  ('zuerich', 'voegel', 'Amsel', ''),
  ('zuerich', 'voegel', 'Kohlmeise', ''),
  ('zuerich', 'voegel', 'Blaumeise', ''),
  ('zuerich', 'voegel', 'Haussperling', ''),
  ('zuerich', 'voegel', 'Mauersegler', ''),
  ('zuerich', 'voegel', 'Graureiher', ''),
  ('zuerich', 'voegel', 'Haubentaucher', ''),
  ('zuerich', 'fische', 'Egli', ''),
  ('zuerich', 'fische', 'Hecht', ''),
  ('zuerich', 'fische', 'Felchen', ''),
  ('zuerich', 'wiesenblumen', 'Margerite', ''),
  ('zuerich', 'wiesenblumen', 'Wiesen-Salbei', ''),
  ('zuerich', 'wiesenblumen', 'Löwenzahn', ''),
  ('zuerich', 'insekten', 'Honigbiene', ''),
  ('zuerich', 'insekten', 'Maikäfer', ''),
  ('zuerich', 'falter', 'Tagpfauenauge', ''),
  ('zuerich', 'falter', 'Zitronenfalter', ''),
  -- Tessin
  ('tessin', 'gewaesser', 'Lago Maggiore', ''),
  ('tessin', 'gewaesser', 'Ticino', ''),
  ('tessin', 'berge', 'Monte Generoso', ''),
  ('tessin', 'sehenswuerdigkeiten', 'Burgen von Bellinzona', ''),
  ('tessin', 'spezialitaeten', 'Polenta', ''),
  ('tessin', 'geschichte', 'Gotthardtunnel', 'Der Tunnel endet im Süden in Airolo.'),
  ('tessin', 'baeume', 'Edelkastanie', ''),
  ('tessin', 'steine', 'Gneis', 'Daraus sind die Steindächer vieler Tessiner Dörfer.'),
  ('tessin', 'steine', 'Granit', ''),
  ('tessin', 'reptilien', 'Westliche Smaragdeidechse', ''),
  ('tessin', 'reptilien', 'Mauereidechse', ''),
  ('tessin', 'reptilien', 'Aspisviper', ''),
  ('tessin', 'reptilien', 'Gelbgrüne Zornnatter', ''),
  ('tessin', 'reptilien', 'Würfelnatter', ''),
  ('tessin', 'amphibien', 'Italienischer Laubfrosch', ''),
  ('tessin', 'amphibien', 'Feuersalamander', ''),
  ('tessin', 'schaedlinge', 'Kastaniengallwespe', ''),
  ('tessin', 'voegel', 'Mauersegler', ''),
  ('tessin', 'falter', 'Schwalbenschwanz', '')
  ) as v(region, cat, name, note)
  join public.entries e on e.category_id = v.cat and e.name = v.name
on conflict (entry_id, region_id) do nothing;

-- Forscheraufträge: Antwort jeweils in einem Eintrag (entry_id über Kategorie und Name)
insert into public.tasks (id, category_id, entry_id, kind, question, guess, answer_type, choices, answer, hint, explanation, sort)
select t.id, t.cat, (select e.id from public.entries e where e.category_id = t.cat and e.name = t.entry),
       t.kind, t.question, t.guess, t.answer_type, t.choices::jsonb, t.answer, t.hint, t.explanation, t.sort
  from (values
  -- Glarus
  ('gl-glarus-strassen', 'geschichte', 'Brand von Glarus', 'frage',
   'Auf dem Stadtplan von Glarus fällt dir auf: Im Zentrum sind die Strassen schnurgerade und kreuzen sich fast rechtwinklig, ganz anders als in vielen Altstädten mit krummen Gassen. Woher kommt das?',
   true, 'choice',
   '["Nach dem grossen Brand von 1861 wurde die Stadt nach einem Rasterplan neu gebaut.", "Die Römer haben die Stadt so angelegt.", "Die Strassen wurden so gebaut, damit der Föhn besser durch die Stadt wehen kann."]',
   'Nach dem grossen Brand von 1861 wurde die Stadt nach einem Rasterplan neu gebaut.',
   'Schau in der Kategorie Geschichte nach einem Unglück, das die Stadt Glarus fast ganz zerstört hat.',
   'In der Nacht vom 10. auf den 11. Mai 1861 zerstörte ein Grossbrand rund zwei Drittel der Stadt; der Föhn trieb das Feuer durch die engen Gassen. Beim Wiederaufbau legte man gerade, breite Strassen nach einem Rasterplan an. Man sieht ihn bis heute.',
   300),
  ('gl-kaerpf-jubilaeum', 'berge', 'Kärpf', 'rechnen',
   'Der Freiberg Kärpf gilt als ältestes Wildschutzgebiet Europas. In welchem Jahr kann er seinen 500. Geburtstag feiern?',
   false, 'text', '[]', '2048',
   'Such im Eintrag Kärpf, seit wann die Jagd dort verboten ist, und zähle 500 Jahre dazu.',
   'Seit 1548 ist die Jagd am Kärpf verboten. 1548 + 500 = 2048. Damals ging es vor allem darum, Gämsen und Murmeltiere vor dem Ausrotten zu schützen.',
   310),
  ('gl-schabziger', 'spezialitaeten', 'Schabziger', 'raetsel',
   'Ich bin grün, habe die Form eines kleinen Kegels und rieche kräftig nach Kräutern. Schon 1463 hat die Glarner Landsgemeinde Regeln für mich erlassen. Wer bin ich?',
   false, 'text', '[]', 'Schabziger|Ziger|Glarner Schabziger',
   'Es ist ein Käse. Schau bei den Spezialitäten aus Glarus.',
   'Der Schabziger wird aus entrahmter Kuhmilch gemacht; der Schabzigerklee gibt ihm Farbe und Geschmack. Weil die Landsgemeinde schon 1463 Regeln für Herstellung und Kennzeichnung festlegte, gilt er als eines der ältesten Markenprodukte der Schweiz.',
   320),
  ('gl-lochsite', 'naturwunder', 'Lochsite', 'frage',
   'Normalerweise liegen jüngere Gesteinsschichten oben auf den älteren, wie bei einem Stapel Zeitungen. Bei der Lochsite in Schwanden ist es umgekehrt: Das alte Gestein liegt oben. Wie ist das möglich?',
   true, 'free', '[]', '',
   'Denk daran, was bei der Entstehung der Alpen mit grossen Gesteinspaketen passiert ist.',
   'Bei der Entstehung der Alpen wurden riesige Gesteinspakete über weite Strecken geschoben. So kam der alte Verrucano auf den viel jüngeren Flysch zu liegen. Diese Linie heisst Glarner Hauptüberschiebung; sie gehört zum UNESCO-Welterbe Tektonikarena Sardona.',
   330),
  ('gl-martinsloch', 'naturwunder', 'Martinsloch', 'raetsel',
   'Hoch über einem Glarner Dorf ist ein Loch im Fels. Zweimal im Jahr scheint die Sonne genau hindurch auf die Dorfkirche. Wie heisst dieses Loch?',
   false, 'text', '[]', 'Martinsloch',
   'Das Dorf heisst Elm. Schau bei den Naturwundern.',
   'Das Martinsloch liegt in den Tschingelhörnern über Elm. Zweimal im Jahr scheint die Sonne durch das Loch auf die Kirche von Elm. Die Felsen gehören zur Tektonikarena Sardona, einem UNESCO-Welterbe.',
   340),
  ('gl-naefelser-fahrt', 'geschichte', 'Schlacht bei Näfels', 'situation',
   'Am ersten Donnerstag im April ziehen in Näfels viele Menschen in einer feierlichen Prozession über die Felder. Woran erinnern sie?',
   true, 'choice',
   '["An die Schlacht bei Näfels von 1388, in der die Glarner gegen Habsburg siegten.", "An den Brand von Glarus von 1861.", "An die erste Landsgemeinde im Kanton Glarus."]',
   'An die Schlacht bei Näfels von 1388, in der die Glarner gegen Habsburg siegten.',
   'Schau in der Kategorie Geschichte, welches Ereignis in Näfels stattfand.',
   'Am 9. April 1388 besiegten die Glarner bei Näfels ein viel grösseres habsburgisches Heer. Daran erinnert jedes Jahr die Näfelser Fahrt. Für Glarus ist sie bis heute der wichtigste Gedenktag.',
   350),
  ('gl-elm', 'geschichte', 'Bergsturz von Elm', 'frage',
   'Im September 1881 stürzten bei Elm Millionen Kubikmeter Fels ins Tal. Was war die Ursache?',
   true, 'choice',
   '["Am Fuss des Berges wurde unvorsichtig Schiefer abgebaut.", "Ein starkes Erdbeben liess den Berg einstürzen.", "Ein Gletscher war geschmolzen und hielt den Fels nicht mehr."]',
   'Am Fuss des Berges wurde unvorsichtig Schiefer abgebaut.',
   'Der Bergsturz hängt mit einem Gestein zusammen, aus dem man früher Schreibtafeln machte.',
   'Am Tschingelberg bei Elm wurde Schiefer abgebaut, und zwar so unvorsichtig, dass der Berg den Halt verlor. Der Bergsturz begrub 114 Menschen und 83 Gebäude. Der Geologe Albert Heim untersuchte ihn genau.',
   360),
  ('gl-stimmrecht', 'politik', 'Stimmrecht ab 16', 'rechnen',
   'Lara ist im Kanton Glarus geboren und feiert im März 2027 ihren 16. Geburtstag. Wie viele Jahre gibt es dann in Glarus schon das Stimmrecht ab 16?',
   false, 'text', '[]', '20',
   'Such, seit welchem Jahr Jugendliche ab 16 in Glarus mitstimmen dürfen.',
   'Die Landsgemeinde beschloss 2007 das Stimmrecht ab 16, als erster Kanton der Schweiz. 2027 − 2007 = 20 Jahre. Lara darf also an der Landsgemeinde im Mai 2027 schon mitstimmen.',
   370),
  -- Graubünden
  ('gr-bernina', 'berge', 'Piz Bernina', 'raetsel',
   'Ich bin der einzige Viertausender der Ostalpen und der höchste Berg Graubündens. Mein verschneiter Nordgrat heisst «Himmelsleiter». Wer bin ich?',
   false, 'text', '[]', 'Piz Bernina|Bernina',
   'Schau bei den Bergen nach einem Gipfel im Oberengadin.',
   'Der Piz Bernina ist 4049 m hoch. Sein Nordgrat, der Biancograt, wird «Himmelsleiter» genannt. Erstbestiegen wurde er 1850 vom Bündner Vermesser Johann Coaz.',
   400),
  ('gr-landwasser', 'sehenswuerdigkeiten', 'Landwasserviadukt', 'rechnen',
   'Das Landwasserviadukt ist 65 m hoch. Ein Stockwerk eines Wohnhauses ist etwa 3 m hoch. Wie viele Stockwerke müsste ein Haus ungefähr haben, um so hoch zu sein wie das Viadukt?',
   true, 'text', '[]', '22|21',
   'Teile die Höhe des Viadukts durch die Höhe eines Stockwerks und runde.',
   '65 m : 3 m ergibt etwa 21,7, also rund 22 Stockwerke. Das Landwasserviadukt ist das Wahrzeichen der Rhätischen Bahn; die Züge fahren direkt in einen Tunnel in der senkrechten Felswand.',
   410),
  ('gr-ruinaulta', 'naturwunder', 'Ruinaulta', 'frage',
   'Die Rheinschlucht zwischen Ilanz und Reichenau wird «Swiss Grand Canyon» genannt. Wie ist sie entstanden?',
   true, 'choice',
   '["Der Rhein grub sich durch die Schuttmassen des riesigen Flimser Bergsturzes.", "Ein Gletscher hat sie in der letzten Eiszeit ausgeschliffen.", "Sie wurde für die Eisenbahn gesprengt."]',
   'Der Rhein grub sich durch die Schuttmassen des riesigen Flimser Bergsturzes.',
   'Schau bei den Naturwundern in Graubünden, was vor rund 10 000 Jahren das Tal verschüttete.',
   'Vor rund 10 000 Jahren verschüttete der Flimser Bergsturz, der grösste bekannte Bergsturz der Alpen, das Tal. Seither hat sich der Vorderrhein durch die hellen Schuttmassen gegraben und die bizarren Felswände geformt.',
   420),
  ('gr-morteratsch', 'naturwunder', 'Morteratschgletscher', 'rechnen',
   'Der Morteratschgletscher hat sich seit dem Ende des 19. Jahrhunderts um mehr als zwei Kilometer zurückgezogen. Rechne mit 2000 m in 130 Jahren: Wie viele Meter sind das im Durchschnitt pro Jahr?',
   true, 'text', '[]', '15',
   'Teile 2000 m durch 130 Jahre und runde auf ganze Meter.',
   '2000 m : 130 Jahre ergibt rund 15 m pro Jahr. Auf dem Gletscherlehrpfad zeigen Tafeln, wo das Eis früher lag. Der Rückgang hängt mit der Klimaerwärmung zusammen.',
   430),
  -- St. Gallen
  ('sg-taminaschlucht', 'naturwunder', 'Taminaschlucht', 'situation',
   'Im Mittelalter liess man Kranke an Seilen in eine enge Felsschlucht bei Bad Ragaz hinunter. Warum?',
   true, 'choice',
   '["Damit sie in einer warmen Quelle baden konnten.", "Weil die Luft in der Schlucht besonders frisch war.", "Weil dort ein berühmter Arzt wohnte."]',
   'Damit sie in einer warmen Quelle baden konnten.',
   'Schau bei den Naturwundern in St. Gallen nach einer Schlucht mit einer besonderen Quelle.',
   'In der Taminaschlucht entspringt eine Quelle mit rund 36,5 °C warmem Wasser. Weil die Schlucht so eng und steil war, liess man Kranke an Seilen hinunter. Heute wird das Wasser nach Bad Ragaz geleitet.',
   440),
  ('sg-stiftsbibliothek', 'sehenswuerdigkeiten', 'Stiftsbezirk St. Gallen', 'raetsel',
   'In mir steht einer der schönsten Bibliothekssäle der Welt mit über 2000 mittelalterlichen Handschriften. Begonnen hat alles mit einem Kloster beim Grab des heiligen Gallus. Wie heisse ich?',
   false, 'text', '[]', 'Stiftsbezirk St. Gallen|Stiftsbezirk|Stiftsbibliothek',
   'Schau bei den Sehenswürdigkeiten nach einem UNESCO-Welterbe in der Stadt St. Gallen.',
   'Der Stiftsbezirk St. Gallen geht auf ein Kloster zurück, das im 8. Jahrhundert gegründet wurde. Die barocke Stiftsbibliothek bewahrt über 2000 mittelalterliche Handschriften. Seit 1983 gehört der Stiftsbezirk zum UNESCO-Welterbe.',
   450),
  ('sg-bratwurst', 'spezialitaeten', 'St. Galler Bratwurst', 'situation',
   'Du kaufst an einem Stand in St. Gallen eine Bratwurst und fragst nach Senf. Die Verkäuferin lacht. Was sagt sie wohl?',
   true, 'choice',
   '["Eine echte St. Galler Bratwurst isst man ohne Senf, dafür mit einem Bürli.", "Senf gibt es nur zum Cervelat, nicht zur Bratwurst.", "Senf ist in St. Gallen verboten."]',
   'Eine echte St. Galler Bratwurst isst man ohne Senf, dafür mit einem Bürli.',
   'Lies den Eintrag St. Galler Bratwurst bei den Spezialitäten.',
   'Die St. Galler Bratwurst aus Kalbfleisch, Schweinefleisch, Speck und Milch isst man traditionell ohne Senf, dafür mit einem knusprigen Bürli. Schon ein Zunftreglement von 1438 schrieb vor, was hineingehört.',
   460),
  ('sg-quinten', 'gewaesser', 'Walensee', 'frage',
   'Am Nordufer des Walensees liegt das Dorf Quinten. Dort wachsen sogar Reben und Feigen. Wie kommt man nach Quinten?',
   true, 'choice',
   '["Nur zu Fuss oder mit dem Schiff.", "Mit dem Postauto über eine Passstrasse.", "Mit einer Seilbahn von Walenstadt."]',
   'Nur zu Fuss oder mit dem Schiff.',
   'Schau im Eintrag Walensee nach, was Quinten besonders macht.',
   'Quinten hat keinen Strassenanschluss: Man erreicht es nur zu Fuss oder mit dem Schiff. Unter den Felswänden der Churfirsten ist es so mild, dass Reben und Feigen wachsen.',
   470),
  -- Zürich
  ('zh-grossmuenster', 'sehenswuerdigkeiten', 'Grossmünster', 'raetsel',
   'Ich habe zwei Türme und bin das Wahrzeichen von Zürich. Ab 1519 predigte hier ein Pfarrer, der die Reformation in der deutschen Schweiz begann. Wer bin ich?',
   false, 'text', '[]', 'Grossmünster',
   'Gesucht ist eine Kirche. Schau bei den Sehenswürdigkeiten in Zürich.',
   'Im Grossmünster predigte ab 1519 Huldrych Zwingli. Auf den Karlsturm führen fast 200 Stufen, von oben sieht man über Stadt und See. Die Kirchenfenster stammen von Augusto Giacometti und Sigmar Polke.',
   480),
  ('zh-birchermuesli', 'spezialitaeten', 'Birchermüesli', 'frage',
   'Das Birchermüesli kennt man auf der ganzen Welt. Wer hat es erfunden, und wozu?',
   true, 'choice',
   '["Ein Zürcher Arzt um 1900 als gesunde Kost für seine Patienten.", "Bergbauern als Proviant für die Alp.", "Ein Hotelkoch für Touristen aus England."]',
   'Ein Zürcher Arzt um 1900 als gesunde Kost für seine Patienten.',
   'Der Name verrät schon viel: Schau bei den Spezialitäten nach.',
   'Der Zürcher Arzt Maximilian Bircher-Benner erfand es um 1900 für seine Patienten. Ursprünglich bestand es vor allem aus geriebenem Apfel mit eingeweichten Haferflocken, Nüssen, Zitronensaft und gezuckerter Kondensmilch.',
   490),
  ('zh-seen-vergleich', 'gewaesser', 'Zürichsee', 'rechnen',
   'Der Bodensee ist 536 km² gross, der Zürichsee 88 km². Wie viele Male grösser ist der Bodensee ungefähr?',
   true, 'text', '[]', '6',
   'Teile die Fläche des Bodensees durch die Fläche des Zürichsees und runde auf eine ganze Zahl.',
   '536 : 88 ergibt etwa 6,1. Der Bodensee ist also rund sechsmal so gross wie der Zürichsee. Der Zürichsee ist dafür über 40 km lang und liefert einen grossen Teil des Zürcher Trinkwassers.',
   500),
  ('zh-trinkwasser', 'gewaesser', 'Zürichsee', 'situation',
   'Du drehst in Zürich den Wasserhahn auf und trinkst ein Glas Wasser. Woher kommt ein grosser Teil dieses Wassers?',
   true, 'choice',
   '["Aus dem Zürichsee.", "Aus dem Rhein bei Basel.", "Aus Gletschern im Wallis."]',
   'Aus dem Zürichsee.',
   'Lies den Eintrag Zürichsee genau.',
   'Ein grosser Teil des Zürcher Trinkwassers kommt aus dem Zürichsee. Das Wasser wird aufbereitet, bevor es in die Leitungen kommt. Darum ist es wichtig, den See sauber zu halten.',
   510),
  -- Tessin
  ('ti-ticino', 'gewaesser', 'Ticino', 'raetsel',
   'Ich entspringe beim Nufenenpass, fliesse durch die Leventina in den Lago Maggiore und habe einem ganzen Kanton meinen Namen gegeben. Wer bin ich?',
   false, 'text', '[]', 'Ticino|Tessin',
   'Gesucht ist ein Fluss. Schau bei den Gewässern im Tessin.',
   'Der Ticino gab dem Kanton Tessin seinen Namen. Nach dem Lago Maggiore fliesst er in Italien in den Po und mit ihm in die Adria.',
   520),
  ('ti-brotbaum', 'baeume', 'Edelkastanie', 'frage',
   'Im Tessin nannte man einen Baum früher «Brotbaum». Warum?',
   true, 'choice',
   '["Seine Früchte, die Marroni, waren im Winter ein wichtiges Nahrungsmittel.", "Aus seinem Holz baute man Backöfen.", "Seine Rinde riecht nach frischem Brot."]',
   'Seine Früchte, die Marroni, waren im Winter ein wichtiges Nahrungsmittel.',
   'Schau bei den Bäumen nach einem Baum der Alpensüdseite mit stacheligen Früchten.',
   'Die Edelkastanie prägt die Wälder der Alpensüdseite. Ihre Marroni waren früher im Winter ein wichtiges Grundnahrungsmittel, darum hiess sie «Brotbaum». Die Früchte stecken in einer stacheligen Hülle.',
   530),
  ('ti-tiefster-punkt', 'gewaesser', 'Lago Maggiore', 'rechnen',
   'Die Oberfläche des Lago Maggiore liegt auf rund 193 m über Meer, das ist der tiefste Punkt der Schweiz. Die Dufourspitze, der höchste Punkt, ist 4634 m hoch. Wie gross ist der Höhenunterschied?',
   true, 'text', '[]', '4441',
   'Ziehe die tiefere Höhe von der höheren ab.',
   '4634 m − 193 m = 4441 m. Auf kleinem Raum liegen in der Schweiz also über 4400 Höhenmeter. Am Lago Maggiore ist es so mild, dass Palmen und Kamelien wachsen.',
   540),
  ('ti-bellinzona', 'sehenswuerdigkeiten', 'Burgen von Bellinzona', 'frage',
   'Warum baute man in Bellinzona im Mittelalter gleich drei Burgen und eine lange Mauer quer durchs Tal?',
   true, 'choice',
   '["Um den Weg zu den Alpenpässen zu bewachen und das Tal abzusperren.", "Um sich vor Überschwemmungen des Ticino zu schützen.", "Weil drei Brüder je eine eigene Burg wollten."]',
   'Um den Weg zu den Alpenpässen zu bewachen und das Tal abzusperren.',
   'Schau bei den Sehenswürdigkeiten im Tessin nach.',
   'Castelgrande, Montebello und Sasso Corbaro bewachten zusammen mit einer langen Mauer den Weg zu den Alpenpässen und sperrten das ganze Tal ab. Seit 2000 gehören sie zum UNESCO-Welterbe.',
   550)
  ) as t(id, cat, entry, kind, question, guess, answer_type, choices, answer, hint, explanation, sort)
on conflict (id) do nothing;

update public.app_meta set schema_version = 25, updated_at = now();

commit;
