-- Einfache Texte (Version 2.21.0): pro Eintrag eine Kurzfassung in einfacher Sprache für die Mittelstufe und für
-- Lernende mit Deutsch als Zweitsprache (Spalte entries.simple aus 026). Kurze Sätze, wenig Fachwörter, nichts, was
-- nicht auch auf der Karte steht. Bestehende Kurzfassungen (z. B. von Hand geändert) bleiben unverändert.
-- Nach 026 einmal im Supabase-Dashboard unter «SQL Editor» ausführen. Lässt sich gefahrlos mehrmals ausführen.

begin;

update public.entries e set simple = v.txt
  from (values
  -- Bäume
  ('baeume', 'Fichte (Rottanne)', 'Die Fichte ist der häufigste Baum in der Schweiz. Ihre Nadeln sind spitz und stechen. Die Zapfen hängen nach unten.'),
  ('baeume', 'Buche', 'Die Buche ist der häufigste Laubbaum der Schweiz. Ihre Rinde ist glatt und silbergrau. Ihre Früchte heissen Bucheckern.'),
  ('baeume', 'Weisstanne', 'Die Weisstanne hat weiche Nadeln mit zwei weissen Streifen unten. Ihre Zapfen stehen aufrecht und zerfallen am Baum. Darum findet man am Boden keine ganzen Tannzapfen.'),
  ('baeume', 'Lärche', 'Die Lärche ist ein Nadelbaum, der im Herbst gelb wird und seine Nadeln verliert. Ihre weichen Nadeln wachsen in Büscheln. Sie wächst in den Bergen bis hoch hinauf.'),
  ('baeume', 'Waldföhre', 'Die Waldföhre hat lange Nadeln, immer zwei zusammen. Oben am Stamm ist ihre Rinde rotbraun. Sie wächst auch dort, wo es sehr trocken ist.'),
  ('baeume', 'Bergahorn', 'Der Bergahorn hat grosse Blätter mit fünf Spitzen. Seine Früchte haben zwei Flügel und drehen sich beim Fallen wie ein Propeller. Kinder kleben sie gern auf die Nase.'),
  ('baeume', 'Esche', 'Die Esche hat gefiederte Blätter und schwarze Knospen. Ihr Holz ist zäh, man macht daraus Stiele für Werkzeuge. Heute sind viele Eschen wegen eines Pilzes krank.'),
  ('baeume', 'Stieleiche', 'Die Stieleiche trägt ihre Eicheln an langen Stielen. Ihre Rinde ist dick und hat tiefe Risse. In einer Eiche leben sehr viele Insekten und Vögel.'),
  ('baeume', 'Arve', 'Die Arve wächst hoch oben in den Bergen und hält grosse Kälte aus. Sie hat immer fünf weiche Nadeln zusammen. Ihr Holz duftet gut.'),
  ('baeume', 'Edelkastanie', 'Die Edelkastanie wächst vor allem im Tessin. Ihre Früchte, die Marroni, stecken in einer stacheligen Hülle. Früher waren sie im Winter ein wichtiges Essen.'),
  ('baeume', 'Winterlinde', 'Die Winterlinde hat Blätter in Herzform. Im Sommer duften ihre Blüten, und viele Bienen kommen. Aus den Blüten macht man Tee.'),
  ('baeume', 'Hagebuche', 'Die Hagebuche hat sehr hartes Holz. Man pflanzt sie oft als Hecke. Ihr grauer Stamm sieht aus, als hätte er Muskeln.'),
  ('baeume', 'Hängebirke', 'Die Hängebirke hat eine weisse Rinde mit schwarzen Rissen. Ihre dünnen Zweige hängen nach unten. Sie wächst oft als erster Baum auf leeren Flächen.'),
  ('baeume', 'Vogelbeere', 'Die Vogelbeere wächst bis hoch in die Berge. Im Herbst hat sie orangerote Beeren. Amseln und andere Vögel fressen sie gern.'),
  ('baeume', 'Eibe', 'Die Eibe ist ein Nadelbaum, der sehr langsam wächst. Fast alles an ihr ist giftig. Eiben können über 1000 Jahre alt werden.'),
  ('baeume', 'Feldahorn', 'Der Feldahorn ist der kleinste Ahorn. Er wächst oft am Waldrand und in Hecken. Seine Blätter sind klein und haben runde Lappen.'),
  -- Sträucher
  ('straeucher', 'Hasel', 'Die Hasel blüht schon im Februar mit gelben Kätzchen. Im Herbst reifen die Haselnüsse. Eichhörnchen und Menschen essen sie gern.'),
  ('straeucher', 'Schwarzer Holunder', 'Der Holunder hat im Juni grosse weisse Blüten. Daraus macht man Sirup. Die schwarzen Beeren darf man nur gekocht essen.'),
  ('straeucher', 'Weissdorn', 'Der Weissdorn ist ein Strauch mit Dornen. Im Mai ist er voller weisser Blüten. In seinen Zweigen bauen Vögel geschützt ihre Nester.'),
  ('straeucher', 'Schwarzdorn (Schlehe)', 'Der Schwarzdorn blüht im Frühling weiss, noch bevor er Blätter hat. Seine blauen Früchte heissen Schlehen. Sie schmecken erst nach dem ersten Frost besser.'),
  ('straeucher', 'Hundsrose', 'Die Hundsrose ist die häufigste wilde Rose der Schweiz. Aus ihren Blüten werden rote Hagebutten. Daraus macht man Tee oder Konfitüre.'),
  ('straeucher', 'Roter Hartriegel', 'Der Rote Hartriegel hat im Winter rote Zweige. Im Herbst werden seine Blätter weinrot. Seine schwarzen Beeren fressen Vögel, Menschen nicht.'),
  ('straeucher', 'Liguster', 'Der Liguster wächst oft als Hecke im Garten. Seine weissen Blüten duften stark. Die schwarzen Beeren sind für Menschen giftig.'),
  ('straeucher', 'Pfaffenhütchen', 'Das Pfaffenhütchen hat rosarote Früchte, die wie ein Hut aussehen. Darin sind orange Samen. Die ganze Pflanze ist sehr giftig.'),
  ('straeucher', 'Wolliger Schneeball', 'Der Wollige Schneeball hat weich behaarte Blätter. Seine Früchte sind zuerst grün, dann rot und zuletzt schwarz. Oft sieht man alle Farben gleichzeitig.'),
  ('straeucher', 'Berberitze', 'Die Berberitze hat scharfe Dornen und gelbe Blüten. Ihre roten Beeren sind sehr sauer. Sie haben viel Vitamin C.'),
  ('straeucher', 'Gemeiner Schneeball', 'Der Gemeine Schneeball wächst gern am Bach. Er hat flache weisse Blüten und im Herbst glänzende rote Beeren. Roh sind die Beeren giftig.'),
  ('straeucher', 'Rote Heckenkirsche', 'Die Rote Heckenkirsche hat immer zwei Blüten zusammen. Daraus werden zwei rote Beeren. Diese sind für Menschen giftig.'),
  ('straeucher', 'Seidelbast', 'Der Seidelbast blüht schon im März mit rosa Blüten. Die Blüten sitzen direkt am Zweig und duften stark. Die ganze Pflanze ist sehr giftig.'),
  ('straeucher', 'Grünerle', 'Die Grünerle wächst an steilen Hängen in den Bergen. Unter dem Schnee legt sie sich flach hin. Im Frühling richtet sie sich wieder auf.'),
  ('straeucher', 'Heidelbeere', 'Die Heidelbeere ist ein kleiner Strauch im Wald. Ihre blauen Beeren reifen im Sommer. Sie färben Mund und Finger blau.'),
  ('straeucher', 'Brombeere', 'Die Brombeere hat lange Ranken mit Stacheln. Ihre schwarzen Beeren reifen im Spätsommer. Menschen, Vögel und Füchse essen sie gern.'),
  -- Alpenblumen
  ('alpenblumen', 'Edelweiss', 'Das Edelweiss ist das bekannteste Zeichen der Alpen. Seine weissen Sterne sind mit feinen Haaren bedeckt. Die Haare schützen vor Sonne und Trockenheit.'),
  ('alpenblumen', 'Stängelloser Enzian', 'Dieser Enzian hat eine grosse, tiefblaue Glocke. Sie wächst fast direkt aus dem Boden. Bei schlechtem Wetter schliesst sich die Blüte.'),
  ('alpenblumen', 'Frühlings-Enzian', 'Der Frühlings-Enzian hat kleine, hellblaue Sternblüten. Er blüht als eine der ersten Blumen nach dem Schnee. Seine Blüten öffnen sich nur bei Sonne.'),
  ('alpenblumen', 'Alpenrose', 'Die Alpenrose ist ein kleiner Strauch in den Bergen. Im Sommer färbt sie ganze Hänge rosarot. Sie ist giftig.'),
  ('alpenblumen', 'Türkenbund', 'Der Türkenbund ist eine Lilie mit rosa Blüten. Die Blütenblätter sind nach hinten gebogen wie ein Turban. Am Abend duftet sie stark.'),
  ('alpenblumen', 'Silberwurz', 'Die Silberwurz wächst wie ein Teppich am Boden. Sie hat weisse Blüten mit acht Blättern. Später bildet sie silbrig glänzende Federn.'),
  ('alpenblumen', 'Trollblume', 'Die Trollblume hat runde, goldgelbe Blüten wie kleine Kugeln. Die Blüten gehen nie ganz auf. Sie wächst auf feuchten Bergwiesen.'),
  ('alpenblumen', 'Alpen-Anemone', 'Die Alpen-Anemone blüht kurz nach der Schneeschmelze. Ihre Blüten sind weiss oder gelb. Danach sehen ihre Fruchtstände aus wie wirre Haare.'),
  ('alpenblumen', 'Alpenglöckchen', 'Das Alpenglöckchen hat kleine violette Glöckchen mit Fransen. Es kann sich durch den letzten Schnee hindurch schmelzen. So blüht es sehr früh.'),
  ('alpenblumen', 'Gelber Enzian', 'Der Gelbe Enzian ist der grösste Enzian und hat gelbe Blüten. Er blüht erst, wenn er etwa zehn Jahre alt ist. Kühe fressen ihn nicht, weil er bitter ist.'),
  ('alpenblumen', 'Arnika', 'Die Arnika hat leuchtend gelbe, zerzauste Blüten. Sie wächst nur auf Wiesen, die nicht gedüngt sind. Aus ihr macht man Salbe gegen Prellungen.'),
  ('alpenblumen', 'Schwarzes Kohlröschen', 'Das Kohlröschen ist eine kleine Orchidee mit dunkelroten Blüten. Es duftet nach Vanille und Schokolade. Es ist geschützt und darf nicht gepflückt werden.'),
  ('alpenblumen', 'Alpen-Aster', 'Die Alpen-Aster hat eine grosse Blüte mit violetten Blättern und gelber Mitte. Sie wächst an sonnigen, trockenen Orten. Ihre Haare schützen sie vor dem Austrocknen.'),
  ('alpenblumen', 'Gletscher-Hahnenfuss', 'Der Gletscher-Hahnenfuss wächst höher als fast alle anderen Blumen der Alpen. Er hat weisse Blüten, die später rötlich werden. Er wächst auf Steinen, wo lange Schnee liegt.'),
  ('alpenblumen', 'Stängelloses Leimkraut', 'Das Leimkraut wächst als flaches Kissen mit vielen kleinen rosa Blüten. Die Kissenform schützt vor Wind und Kälte. Ein Kissen kann über 100 Jahre alt werden.'),
  ('alpenblumen', 'Blauer Eisenhut', 'Der Eisenhut hat dunkelblaue Blüten, die wie ein Helm aussehen. Er ist die giftigste Pflanze Europas. Man darf ihn nie pflücken.'),
  ('alpenblumen', 'Silberdistel', 'Die Silberdistel hat einen grossen, silbrig glänzenden Blütenkopf direkt am Boden. Ihre Blätter sind stachelig. Bei feuchtem Wetter schliesst sie sich.'),
  ('alpenblumen', 'Feuerlilie', 'Die Feuerlilie hat grosse, leuchtend orangerote Blüten. Sie wachsen nach oben wie ein Kelch. Die Feuerlilie ist selten und geschützt.'),
  -- Wiesenblumen
  ('wiesenblumen', 'Margerite', 'Die Margerite hat aussen weisse und innen gelbe Blüten. Was aussieht wie eine Blüte, sind ganz viele kleine Blüten. Sie wächst auf Wiesen und am Wegrand.'),
  ('wiesenblumen', 'Wiesen-Salbei', 'Der Wiesen-Salbei hat blauviolette Blüten. Kriecht eine Hummel hinein, bekommt sie Blütenstaub auf den Rücken. Er wächst auf trockenen, sonnigen Wiesen.'),
  ('wiesenblumen', 'Wiesen-Glockenblume', 'Die Wiesen-Glockenblume hat violette Glocken, die weit offen stehen. Ihre Stängel sind dünn. Sie wächst auf Wiesen und an Böschungen.'),
  ('wiesenblumen', 'Kuckucks-Lichtnelke', 'Die Kuckucks-Lichtnelke hat rosa Blüten mit zerfransten Blättern. Sie blüht, wenn der Kuckuck ruft. Sie wächst auf feuchten Wiesen.'),
  ('wiesenblumen', 'Wiesen-Bocksbart', 'Der Wiesen-Bocksbart hat gelbe Blüten, die nur am Morgen offen sind. Danach bildet er grosse Pusteblumen. Seine Blätter sind lang und schmal.'),
  ('wiesenblumen', 'Zottiger Klappertopf', 'Der Klappertopf holt sich Nahrung aus den Wurzeln von Gräsern. Darum haben andere Blumen mehr Platz. Seine reifen Samen klappern in der Kapsel.'),
  ('wiesenblumen', 'Wiesen-Flockenblume', 'Die Wiesen-Flockenblume hat purpurrote Blüten mit Fransen. Schmetterlinge, Bienen und Hummeln besuchen sie gern. Sie blüht bis in den Herbst.'),
  ('wiesenblumen', 'Rot-Klee', 'Der Rot-Klee hat runde, rosarote Blütenköpfe und Blätter mit drei Teilen. Er düngt den Boden mit Hilfe von Bakterien an den Wurzeln. Kühe fressen ihn gern.'),
  ('wiesenblumen', 'Gewöhnlicher Hornklee', 'Der Hornklee hat gelbe Blüten, oft mit etwas Rot. Seine Früchte sehen aus wie Vogelkrallen. Die Raupen von vielen Schmetterlingen fressen ihn.'),
  ('wiesenblumen', 'Acker-Witwenblume', 'Die Witwenblume hat flache, lila Blüten wie kleine Nadelkissen. Sie wächst auf Wiesen und am Wegrand. Viele Bienen und Schmetterlinge besuchen sie.'),
  ('wiesenblumen', 'Scharfer Hahnenfuss', 'Der Hahnenfuss färbt im Frühling ganze Wiesen gelb. Seine Blüten glänzen wie lackiert. Frisch ist er giftig, im Heu ist er harmlos.'),
  ('wiesenblumen', 'Löwenzahn', 'Der Löwenzahn ist eine der häufigsten Pflanzen der Schweiz. Aus der gelben Blüte wird eine Pusteblume. Ihre Samen fliegen mit kleinen Schirmen davon.'),
  ('wiesenblumen', 'Wiesen-Schaumkraut', 'Das Wiesen-Schaumkraut färbt feuchte Wiesen im Frühling hell lila. Die Raupen des Aurorafalters fressen es. Oft hängt Schaum an seinen Stängeln.'),
  ('wiesenblumen', 'Gewöhnliche Schafgarbe', 'Die Schafgarbe hat flache, weisse Blütenschirme. Ihre Blätter sind ganz fein geteilt. Man macht aus ihr Tee gegen Bauchweh.'),
  ('wiesenblumen', 'Herbstzeitlose', 'Die Herbstzeitlose blüht im Herbst lila, ganz ohne Blätter. Die Blätter kommen erst im Frühling. Die Pflanze ist sehr giftig.'),
  ('wiesenblumen', 'Gänseblümchen', 'Das Gänseblümchen blüht fast das ganze Jahr. Es wächst im Rasen und verträgt das Mähen. Nachts und bei Regen schliesst es sich.'),
  -- Gräser
  ('graeser', 'Knaulgras', 'Das Knaulgras ist ein wichtiges Futter für Kühe. Seine Blüten sitzen in dichten Knäueln. Es wächst auf Wiesen und am Wegrand.'),
  ('graeser', 'Englisches Raigras', 'Das Englische Raigras verträgt es, wenn man darauf läuft. Es wächst schnell nach. Darum braucht man es für Rasen und Sportplätze.'),
  ('graeser', 'Wiesen-Fuchsschwanz', 'Der Wiesen-Fuchsschwanz blüht als eines der ersten Gräser im Frühling. Seine weiche Ähre sieht aus wie ein Fuchsschwanz. Er wächst auf feuchten Wiesen.'),
  ('graeser', 'Aufrechte Trespe', 'Die Aufrechte Trespe wächst auf trockenen Wiesen, zum Beispiel im Jura. In diesen Wiesen gibt es viele Blumen und Schmetterlinge. Ihre Rispen sind oft violett.'),
  ('graeser', 'Wiesen-Lieschgras', 'Das Lieschgras hat eine lange, raue Ähre. Es ist ein gutes Futter für Tiere. Sein Blütenstaub löst oft Heuschnupfen aus.'),
  ('graeser', 'Schilf', 'Das Schilf ist das grösste Gras der Schweiz. Es wächst am Ufer von Seen und wird über 3 m hoch. Viele Vögel leben im Schilf.'),
  ('graeser', 'Zittergras', 'Das Zittergras hat Ährchen in Herzform an ganz dünnen Stielen. Schon bei wenig Wind zittern sie. Es wächst auf Wiesen ohne Dünger.'),
  ('graeser', 'Gewöhnliches Ruchgras', 'Das Ruchgras sorgt für den Duft von frischem Heu. Es blüht früh im Jahr. Sein Blütenstaub löst oft Heuschnupfen aus.'),
  ('graeser', 'Rot-Schwingel', 'Der Rot-Schwingel hat feine, dünne Blätter. Er bildet einen dichten Rasen. Er wächst vom Tal bis in die Berge.'),
  ('graeser', 'Glatthafer', 'Der Glatthafer ist ein hohes Gras auf Heuwiesen im Mittelland. Er wird bis 1,5 m hoch. Er verträgt das Mähen gut.'),
  ('graeser', 'Goldhafer', 'Der Goldhafer glänzt zur Blütezeit goldgelb. Er ist ein gutes Futter auf Bergwiesen. Diese Wiesen heissen nach ihm Goldhaferwiesen.'),
  ('graeser', 'Wiesen-Rispengras', 'Das Wiesen-Rispengras bildet einen dichten Rasen. Man braucht es für Wiesen, Weiden und Sportplätze. Seine Blätter haben eine Spitze wie ein Boot.'),
  ('graeser', 'Borstgras', 'Das Borstgras hat steife Blätter wie Borsten. Es wächst auf mageren Alpweiden. Kühe fressen es nicht gern.'),
  ('graeser', 'Blaugras', 'Das Blaugras blüht im Frühling mit kleinen blauen Ähren. Es wächst an sonnigen Hängen mit Kalk. Es hält den Boden an steilen Hängen fest.'),
  ('graeser', 'Pfeifengras', 'Das Pfeifengras wächst in Riedwiesen und Mooren. Früher putzte man mit seinen Halmen Tabakpfeifen. Im Herbst wird es goldgelb bis orange.'),
  ('graeser', 'Wolliges Honiggras', 'Das Wollige Honiggras hat weiche, behaarte Blätter. Seine Rispen sind hell bis rosa. Kühe fressen es nicht besonders gern.'),
  -- Pilze
  ('pilze', 'Steinpilz', 'Der Steinpilz ist ein beliebter Speisepilz. Er hat einen braunen Hut und einen dicken Stiel. Unter dem Hut hat er Röhren statt Lamellen.'),
  ('pilze', 'Eierschwamm', 'Der Eierschwamm ist dottergelb und riecht leicht nach Aprikosen. Er ist ein beliebter Speisepilz. Unter dem Hut hat er weiche Leisten.'),
  ('pilze', 'Maronen-Röhrling', 'Der Maronen-Röhrling hat einen braunen Hut wie eine Kastanie. Drückt man auf die gelben Röhren, werden sie blau. Er ist ein guter Speisepilz.'),
  ('pilze', 'Parasol', 'Der Parasol hat einen sehr grossen Hut. Jung sieht er aus wie ein Trommelschlegel, später wie ein Sonnenschirm. Seinen Ring am Stiel kann man verschieben.'),
  ('pilze', 'Speisemorchel', 'Die Morchel wächst im Frühling. Ihr Hut sieht aus wie ein Schwamm und ist innen hohl. Man darf sie nur gut gekocht essen.'),
  ('pilze', 'Semmel-Stoppelpilz', 'Der Semmel-Stoppelpilz hat einen hellgelben Hut. Unter dem Hut hat er kleine, weiche Stacheln. Er ist ein guter Speisepilz.'),
  ('pilze', 'Hallimasch', 'Der Hallimasch wächst in grossen Gruppen an Baumstümpfen. Er kann Bäume krank machen. Roh ist er giftig.'),
  ('pilze', 'Riesenbovist', 'Der Riesenbovist ist eine weisse Kugel, so gross wie ein Fussball. Solange er innen weiss ist, kann man ihn essen. Später zerfällt er zu Staub.'),
  ('pilze', 'Schwefelporling', 'Der Schwefelporling wächst gelb bis orange an Bäumen. Er sieht aus wie Regale am Stamm. Er zersetzt das Holz im Baum.'),
  ('pilze', 'Fliegenpilz', 'Der Fliegenpilz hat einen roten Hut mit weissen Punkten. Er ist der bekannteste Pilz. Er ist giftig.'),
  ('pilze', 'Grüner Knollenblätterpilz', 'Der Grüne Knollenblätterpilz ist der gefährlichste Giftpilz der Schweiz. Schon ein Pilz kann tödlich sein. Er hat weisse Lamellen, einen Ring und eine Knolle.'),
  ('pilze', 'Pantherpilz', 'Der Pantherpilz hat einen braunen Hut mit weissen Flocken. Er ist sehr giftig. Man kann ihn mit einem essbaren Pilz verwechseln.'),
  ('pilze', 'Satans-Röhrling', 'Der Satans-Röhrling hat einen hellen Hut und einen dicken roten Stiel. Schneidet man ihn an, wird er blau. Er ist giftig.'),
  ('pilze', 'Zunderschwamm', 'Der Zunderschwamm wächst hart wie ein Pferdehuf an Buchen und Birken. Jedes Jahr wächst er ein Stück. Früher machte man mit ihm Feuer.'),
  ('pilze', 'Stinkmorchel', 'Die Stinkmorchel wächst aus einem weissen Ei. Ihr Kopf stinkt stark nach Aas. Der Gestank lockt Fliegen an.'),
  ('pilze', 'Schopf-Tintling', 'Der Schopf-Tintling hat einen hohen, weissen Hut mit Schuppen. Schon bald zerfliesst er zu schwarzer Flüssigkeit. Früher schrieb man damit wie mit Tinte.'),
  -- Säugetiere
  ('saeugetiere', 'Rothirsch', 'Der Rothirsch ist das grösste Wildtier der Schweiz. Das Männchen hat ein grosses Geweih und verliert es jedes Jahr. Im Herbst röhrt es laut.'),
  ('saeugetiere', 'Reh', 'Das Reh ist ein häufiges Wildtier in der Schweiz. Nur der Rehbock hat ein kleines Geweih. Die Jungen haben weisse Tupfen und liegen still im hohen Gras.'),
  ('saeugetiere', 'Gämse', 'Die Gämse klettert sehr gut in steilem Fels. Sie hat kleine, hakenförmige Hörner. Ihr Gesicht ist schwarz-weiss gezeichnet.'),
  ('saeugetiere', 'Alpensteinbock', 'Der Steinbock lebt hoch oben in den Felsen. Die Männchen haben sehr lange Hörner mit Knoten. Er war in der Schweiz verschwunden und lebt heute wieder hier.'),
  ('saeugetiere', 'Murmeltier', 'Das Murmeltier lebt in Familien in Höhlen auf Alpweiden. Bei Gefahr pfeift es laut. Im Winter schläft es mehrere Monate.'),
  ('saeugetiere', 'Rotfuchs', 'Der Fuchs lebt fast überall, im Wald, in den Bergen und sogar in der Stadt. Er frisst Mäuse, Insekten, Früchte und Abfälle. Sein Schwanz ist lang und buschig.'),
  ('saeugetiere', 'Dachs', 'Der Dachs hat einen schwarz-weiss gestreiften Kopf. Er wohnt in grossen Höhlen unter dem Boden. In der Nacht sucht er Regenwürmer.'),
  ('saeugetiere', 'Luchs', 'Der Luchs ist die grösste Katze Europas. Er hat Pinsel an den Ohren und einen kurzen Schwanz. Er jagt vor allem Rehe und Gämsen.'),
  ('saeugetiere', 'Wolf', 'Der Wolf ist von selbst in die Schweiz zurückgekommen. Wölfe leben in Familien, die man Rudel nennt. Weil sie manchmal Schafe reissen, wird oft über den Wolf gestritten.'),
  ('saeugetiere', 'Schneehase', 'Der Schneehase lebt hoch in den Alpen. Im Winter ist sein Fell weiss, im Sommer braun. Seine breiten Pfoten wirken wie Schneeschuhe.'),
  ('saeugetiere', 'Hermelin', 'Das Hermelin ist ein kleines, schnelles Raubtier. Im Winter ist es weiss, nur die Schwanzspitze bleibt schwarz. Es jagt Mäuse.'),
  ('saeugetiere', 'Biber', 'Der Biber ist das grösste Nagetier Europas. Mit seinen scharfen Zähnen fällt er Bäume. Er baut Dämme im Wasser.'),
  ('saeugetiere', 'Eichhörnchen', 'Das Eichhörnchen klettert flink in den Bäumen. Mit dem buschigen Schwanz hält es das Gleichgewicht. Im Herbst versteckt es Nüsse im Boden.'),
  ('saeugetiere', 'Wildschwein', 'Das Wildschwein hat ein dunkles, borstiges Fell. Mit der Schnauze wühlt es im Boden nach Futter. Seine Jungen haben helle Streifen.'),
  ('saeugetiere', 'Igel', 'Der Igel hat auf dem Rücken viele Stacheln. Bei Gefahr rollt er sich zu einer Kugel. Im Winter schläft er unter Laub.'),
  ('saeugetiere', 'Steinmarder', 'Der Steinmarder lebt oft nahe bei den Menschen, zum Beispiel in Scheunen. Er ist in der Nacht unterwegs. Manchmal beisst er Kabel in Autos an.'),
  -- Hunde
  ('hunde', 'Grosser Schweizer Sennenhund', 'Der Grosse Schweizer Sennenhund ist der grösste Sennenhund. Früher zog er Karren mit Milch. Sein Fell ist schwarz, braun und weiss.'),
  ('hunde', 'Entlebucher Sennenhund', 'Der Entlebucher ist der kleinste Sennenhund. Er kommt aus dem Kanton Luzern und half beim Treiben der Kühe. Er ist flink und lernt gern.'),
  ('hunde', 'Labrador Retriever', 'Der Labrador ist ein beliebter Familienhund. Er ist ruhig und lernt gut. Oft arbeitet er als Blindenhund.'),
  ('hunde', 'Deutscher Schäferhund', 'Der Deutsche Schäferhund ist kräftig und aufmerksam. Er arbeitet oft bei der Polizei. Er hat stehende Ohren.'),
  ('hunde', 'Golden Retriever', 'Der Golden Retriever ist freundlich und geduldig. Er schwimmt gern. Sein langes Fell ist goldfarben.'),
  ('hunde', 'Border Collie', 'Der Border Collie ist ein sehr kluger Hund. Er hütet Schafe und lenkt sie mit seinem Blick. Er braucht viel Beschäftigung.'),
  ('hunde', 'Weisser Schweizer Schäferhund', 'Der Weisse Schweizer Schäferhund hat ein ganz weisses Fell und stehende Ohren. Als Rasse gilt die Schweiz als sein Herkunftsland.'),
  ('hunde', 'Schweizer Laufhund', 'Der Schweizer Laufhund ist ein Jagdhund mit langen Ohren. Er folgt mit seiner feinen Nase einer Spur. Dabei bellt er laut.'),
  ('hunde', 'Jack Russell Terrier', 'Der Jack Russell Terrier ist klein, lebhaft und mutig. Sein Fell ist meist weiss mit Flecken. Er ist ein häufiger Familienhund.'),
  ('hunde', 'Chihuahua', 'Der Chihuahua ist der kleinste Hund der Welt. Sein Name kommt aus Mexiko. Er ist wachsam und bellt oft.'),
  ('hunde', 'Dackel', 'Der Dackel hat kurze Beine und einen langen Körper. So passt er in enge Höhlen von Dachs und Fuchs. Er ist mutig und hat seinen eigenen Kopf.'),
  ('hunde', 'Malinois', 'Der Malinois ist ein schneller Schäferhund aus Belgien. Er arbeitet oft bei Polizei und Armee. Er hat eine schwarze Maske im Gesicht.'),
  ('hunde', 'Schweizer Niederlaufhund', 'Der Niederlaufhund ist ein Jagdhund mit kurzen Beinen. Er ist langsamer als der Laufhund. Er hat lange Ohren und eine sehr gute Nase.'),
  ('hunde', 'Bernhardiner', 'Der Bernhardiner ist ein grosser Hund vom Grossen St. Bernhard. Früher suchte er Menschen im Schnee. Der berühmteste hiess Barry.'),
  ('hunde', 'Berner Sennenhund', 'Der Berner Sennenhund ist gross und schwarz, braun und weiss. Früher zog er Milchkarren. Heute ist er ein beliebter Familienhund.'),
  ('hunde', 'Appenzeller Sennenhund', 'Der Appenzeller Sennenhund trägt seinen Schwanz als Ringel auf dem Rücken. Er ist lebhaft und wachsam. Er bellt gern.'),
  -- Vögel
  ('voegel', 'Bartgeier', 'Der Bartgeier ist einer der grössten Vögel der Alpen. Er frisst vor allem Knochen. Grosse Knochen lässt er auf Felsen fallen, bis sie zerbrechen.'),
  ('voegel', 'Steinadler', 'Der Steinadler ist ein grosser Greifvogel der Alpen. Er jagt Murmeltiere und Schneehasen. Sein Nest baut er in Felswänden.'),
  ('voegel', 'Alpendohle', 'Die Alpendohle ist schwarz mit gelbem Schnabel und roten Beinen. Sie fliegt sehr geschickt. Auf Berggipfeln bettelt sie oft um Essen.'),
  ('voegel', 'Alpenschneehuhn', 'Das Alpenschneehuhn lebt hoch in den Bergen. Im Winter ist es weiss, im Sommer braun gefleckt. So ist es immer gut getarnt.'),
  ('voegel', 'Weissstorch', 'Der Weissstorch baut sein grosses Nest auf Dächern und Kaminen. Fast wäre er aus der Schweiz verschwunden. Im Herbst fliegen viele Störche in den Süden.'),
  ('voegel', 'Graureiher', 'Der Graureiher steht oft lange still am Wasser. Dann stösst er blitzschnell mit dem Schnabel zu. Er frisst Fische, Frösche und Mäuse.'),
  ('voegel', 'Buntspecht', 'Der Buntspecht ist schwarz-weiss und hat Rot unter dem Schwanz. Mit dem Schnabel hackt er Löcher in Bäume. Im Frühling trommelt er laut.'),
  ('voegel', 'Amsel', 'Die Amsel ist einer der häufigsten Vögel der Schweiz. Das Männchen ist schwarz mit orangem Schnabel. Es singt schön, oft in der Dämmerung.'),
  ('voegel', 'Rotkehlchen', 'Das Rotkehlchen hat eine orangerote Brust. Es ist wenig scheu. Es singt auch im Winter.'),
  ('voegel', 'Schleiereule', 'Die Schleiereule hat ein helles Gesicht in Herzform. Sie hört so gut, dass sie Mäuse im Dunkeln findet. Sie wohnt gern in Scheunen und Kirchtürmen.'),
  ('voegel', 'Mauersegler', 'Der Mauersegler ist fast immer in der Luft. Er frisst und schläft sogar im Flug. Er ist nur im Sommer bei uns.'),
  ('voegel', 'Haussperling', 'Der Spatz lebt nahe bei den Menschen. Er badet gern im Staub. Er brütet in Löchern an Häusern.'),
  ('voegel', 'Kohlmeise', 'Die Kohlmeise hat einen gelben Bauch mit einem schwarzen Streifen. Sie brütet gern in Nistkästen. Im Winter kommt sie ans Futterhäuschen.'),
  ('voegel', 'Haubentaucher', 'Der Haubentaucher lebt auf Seen. Im Frühling tanzen die Paare auf dem Wasser. Die Jungen reiten auf dem Rücken der Eltern.'),
  ('voegel', 'Tannenhäher', 'Der Tannenhäher versteckt im Herbst viele Arvennüsse im Boden. Die meisten findet er wieder. Aus den vergessenen wachsen neue Arven.'),
  ('voegel', 'Mäusebussard', 'Der Mäusebussard ist der häufigste Greifvogel der Schweiz. Er sitzt oft auf Zaunpfählen. Er frisst vor allem Mäuse.'),
  ('voegel', 'Blaumeise', 'Die Blaumeise hat einen blauen Kopf und einen gelben Bauch. Sie ist kleiner als die Kohlmeise. Sie brütet gern in Nistkästen.'),
  -- Reptilien
  ('reptilien', 'Zauneidechse', 'Die Zauneidechse sonnt sich gern an warmen Orten. Im Frühling sind die Männchen an der Seite grün. Bei Gefahr kann sie ihren Schwanz abwerfen.'),
  ('reptilien', 'Mauereidechse', 'Die Mauereidechse ist schlank und sehr schnell. Sie klettert an Mauern und Felsen. Man sieht sie oft sogar in der Stadt.'),
  ('reptilien', 'Waldeidechse', 'Die Waldeidechse lebt höher in den Bergen als alle anderen Reptilien. Sie legt keine Eier, sondern bekommt lebende Junge. Sie lebt in Mooren und auf Alpweiden.'),
  ('reptilien', 'Westliche Smaragdeidechse', 'Die Smaragdeidechse ist die grösste Eidechse der Schweiz. Sie ist leuchtend grün. Sie liebt Wärme und lebt vor allem im Tessin, im Wallis und bei Genf.'),
  ('reptilien', 'Blindschleiche', 'Die Blindschleiche sieht aus wie eine Schlange, ist aber eine Eidechse ohne Beine. Sie ist nicht blind und ganz harmlos. Im Garten frisst sie Schnecken.'),
  ('reptilien', 'Barren-Ringelnatter', 'Die Barren-Ringelnatter ist eine harmlose Schlange. Sie schwimmt sehr gut und jagt Frösche. Bei Gefahr stellt sie sich tot.'),
  ('reptilien', 'Östliche Ringelnatter', 'Die Östliche Ringelnatter sieht der Barren-Ringelnatter sehr ähnlich. Sie lebt im Osten der Schweiz. Sie ist harmlos.'),
  ('reptilien', 'Würfelnatter', 'Die Würfelnatter lebt fast nur im Wasser und fängt Fische. Auf dem Rücken hat sie Flecken wie Würfel. Sie ist harmlos und selten.'),
  ('reptilien', 'Vipernatter', 'Die Vipernatter hat ein Zickzack-Muster wie eine Viper. Sie ist aber harmlos. Sie lebt am Wasser im Wallis und bei Genf.'),
  ('reptilien', 'Schlingnatter', 'Die Schlingnatter ist eine kleine, harmlose Schlange. Man verwechselt sie oft mit der Kreuzotter. Ihre Beute hält sie mit dem Körper fest.'),
  ('reptilien', 'Äskulapnatter', 'Die Äskulapnatter ist die längste Schlange der Schweiz. Sie klettert sehr gut auf Bäume. Sie ist das Zeichen der Medizin.'),
  ('reptilien', 'Gelbgrüne Zornnatter', 'Die Zornnatter ist sehr schnell. Sie ist schwarz mit gelbgrünen Flecken. Sie ist nicht giftig und lebt vor allem im Tessin.'),
  ('reptilien', 'Kreuzotter', 'Die Kreuzotter ist eine Giftschlange der Alpen. Auf dem Rücken hat sie ein dunkles Zickzackband. Sie beisst fast nur, wenn man auf sie tritt oder sie anfasst.'),
  ('reptilien', 'Aspisviper', 'Die Aspisviper ist die zweite Giftschlange der Schweiz. Sie lebt an warmen, steinigen Hängen. Nach einem Biss muss man immer zum Arzt.'),
  ('reptilien', 'Europäische Sumpfschildkröte', 'Die Sumpfschildkröte ist die einzige Schildkröte, die von Natur aus in der Schweiz lebt. Sie war fast verschwunden. Sie sonnt sich gern auf Baumstämmen im Wasser.'),
  ('reptilien', 'Rotwangen-Schmuckschildkröte', 'Diese Schildkröte kommt aus Amerika. Viele wurden als Haustier ausgesetzt. Darum darf man Haustiere nie in der Natur aussetzen.'),
  -- Amphibien
  ('amphibien', 'Grasfrosch', 'Der Grasfrosch ist der häufigste Frosch der Schweiz. Schon früh im Jahr legt er grosse Laichballen. Hinter dem Auge hat er einen dunklen Fleck.'),
  ('amphibien', 'Erdkröte', 'Die Erdkröte hat eine warzige Haut. Im Frühling wandern viele Kröten zu ihrem Teich. An Strassen helfen Menschen ihnen dabei.'),
  ('amphibien', 'Feuersalamander', 'Der Feuersalamander ist schwarz mit gelben Flecken. Die Farben warnen: Seine Haut ist giftig. Man sieht ihn vor allem bei Regen.'),
  ('amphibien', 'Alpensalamander', 'Der Alpensalamander ist ganz schwarz und lebt in den Alpen. Er braucht kein Wasser für seine Jungen. Sie kommen fertig entwickelt auf die Welt.'),
  ('amphibien', 'Bergmolch', 'Der Bergmolch hat einen orangen Bauch. Im Frühling sind die Männchen an der Seite blau. Er ist der häufigste Molch der Schweiz.'),
  ('amphibien', 'Laubfrosch', 'Der Laubfrosch ist klein und grasgrün. Mit seinen Haftscheiben klettert er auf Büsche. Die Männchen rufen sehr laut.'),
  ('amphibien', 'Gelbbauchunke', 'Die Gelbbauchunke ist oben braun und unten gelb-schwarz. Bei Gefahr zeigt sie ihren gelben Bauch. Sie legt ihre Eier in kleine Pfützen.'),
  ('amphibien', 'Geburtshelferkröte', 'Bei der Geburtshelferkröte trägt der Vater die Eier an den Beinen herum. Ihr Ruf klingt wie ein Glöckchen. Darum heisst sie auch Glögglifrosch.'),
  ('amphibien', 'Kammmolch', 'Der Kammmolch ist der grösste Molch der Schweiz. Im Frühling haben die Männchen einen hohen, gezackten Kamm. Sein Bauch ist gelb mit schwarzen Flecken.'),
  ('amphibien', 'Teichfrosch', 'Der Teichfrosch ist grün mit dunklen Flecken. Er sonnt sich gern am Ufer. Im Frühsommer quaken die Männchen laut.'),
  ('amphibien', 'Springfrosch', 'Der Springfrosch hat sehr lange Hinterbeine. Er kann bis zu zwei Meter weit springen. In der Schweiz ist er selten.'),
  ('amphibien', 'Kreuzkröte', 'Die Kreuzkröte hat einen gelben Streifen auf dem Rücken. Sie hüpft kaum, sondern rennt wie eine Maus. Ihr Ruf ist sehr laut.'),
  ('amphibien', 'Fadenmolch', 'Der Fadenmolch ist der kleinste Molch der Schweiz. Das Männchen hat am Schwanz einen kleinen Faden. Er lebt in kleinen Weihern im Wald.'),
  ('amphibien', 'Teichmolch', 'Der Teichmolch ist in der Schweiz selten. Im Frühling haben die Männchen einen hohen Kamm. Danach leben die Molche versteckt an Land.'),
  ('amphibien', 'Italienischer Laubfrosch', 'Der Italienische Laubfrosch lebt in der Schweiz vor allem im Tessin. Er ist leuchtend grün. Er klettert auf Schilf und Sträucher.'),
  ('amphibien', 'Kleiner Wasserfrosch', 'Der Kleine Wasserfrosch lebt in kleinen Weihern und Mooren. Er sonnt sich gern am Ufer. Beim Quaken bläst er zwei weisse Blasen auf.'),
  -- Fische
  ('fische', 'Bachforelle', 'Die Bachforelle lebt in kühlen Bächen. Sie hat rote Punkte mit hellem Rand. Warmes Wasser verträgt sie schlecht.'),
  ('fische', 'Äsche', 'Die Äsche hat eine grosse Rückenflosse wie eine Fahne. Sie lebt in schnellen, klaren Flüssen. Wenn das Wasser zu warm wird, kann sie sterben.'),
  ('fische', 'Felchen', 'Felchen sind die wichtigsten Speisefische in Schweizer Seen. Sie leben im offenen Wasser. Sie fressen winzige Tiere, das Plankton.'),
  ('fische', 'Egli', 'Das Egli ist ein häufiger Fisch in Schweizer Seen. Es hat dunkle Streifen und rote Flossen. Eglifilets sind ein bekanntes Essen.'),
  ('fische', 'Hecht', 'Der Hecht ist ein Raubfisch mit vielen spitzen Zähnen. Er versteckt sich zwischen Wasserpflanzen. Dann schiesst er blitzschnell auf seine Beute los.'),
  ('fische', 'Seesaibling', 'Der Seesaibling lebt in tiefen, kalten Seen. Zur Laichzeit wird der Bauch der Männchen orangerot. Er ist ein beliebter Speisefisch.'),
  ('fische', 'Karpfen', 'Der Karpfen wühlt im Schlamm nach Futter. Am Maul hat er vier Bartfäden. Er mag warmes Wasser und kann sehr alt werden.'),
  ('fische', 'Wels', 'Der Wels ist der grösste Fisch in Schweizer Seen und Flüssen. Er hat keine Schuppen und lange Bartfäden. Er jagt in der Nacht.'),
  ('fische', 'Barbe', 'Die Barbe lebt am Grund von Flüssen mit Kies. Mit vier Bartfäden sucht sie Futter. Ihre Eier sind giftig.'),
  ('fische', 'Groppe', 'Die Groppe ist ein kleiner Fisch mit grossem Kopf. Sie kann nicht im Wasser schweben und bewegt sich ruckartig über den Grund. Am Tag versteckt sie sich unter Steinen.'),
  ('fische', 'Nase', 'Die Nase hat eine Schnauze wie eine Nase. Damit weidet sie Algen von Steinen. Heute ist sie in der Schweiz sehr selten.'),
  ('fische', 'Rotauge', 'Das Rotauge hat rote Augen und rötliche Flossen. Es lebt in grossen Schwärmen. Viele grössere Fische fressen es.'),
  ('fische', 'Aal', 'Der Aal kommt im Meer zur Welt und schwimmt bis in die Schweiz. Nach vielen Jahren schwimmt er zurück ins Meer. Kraftwerke versperren ihm oft den Weg.'),
  ('fische', 'Trüsche', 'Die Trüsche hat einen Bartfaden am Kinn. Sie lebt versteckt am Grund. Sie legt ihre Eier mitten im Winter.'),
  ('fische', 'Elritze', 'Die Elritze ist ein kleiner Fisch in klaren Bächen und Bergseen. Sie lebt im Schwarm. Forellen fressen sie gern.'),
  ('fische', 'Alet', 'Der Alet ist ein häufiger Fisch in Flüssen und Seen. Er frisst fast alles, sogar Früchte. Er verträgt wärmeres Wasser als die Forelle.'),
  -- Insekten
  ('insekten', 'Honigbiene', 'Honigbienen leben in grossen Völkern mit einer Königin. Sie bestäuben viele Blumen und Obstbäume. Mit einem Tanz zeigen sie einander, wo es Futter gibt.'),
  ('insekten', 'Erdhummel', 'Die Erdhummel ist gross, pelzig und schwarz-gelb gestreift. Sie fliegt auch, wenn es noch kühl ist. Ihr Nest baut sie oft in einem alten Mauseloch.'),
  ('insekten', 'Siebenpunkt-Marienkäfer', 'Der Marienkäfer ist rot mit sieben schwarzen Punkten. Er frisst sehr viele Blattläuse. Darum ist er im Garten nützlich.'),
  ('insekten', 'Rote Waldameise', 'Die Rote Waldameise baut grosse Hügel aus Nadeln. In einem Hügel leben sehr viele Ameisen. Sie sind geschützt.'),
  ('insekten', 'Maikäfer', 'Der Maikäfer kommt im Mai und frisst Blätter. Seine Larven leben mehrere Jahre im Boden. Darum gibt es nur alle paar Jahre sehr viele Maikäfer.'),
  ('insekten', 'Blauflügel-Prachtlibelle', 'Diese Libelle glänzt blaugrün, die Männchen haben dunkelblaue Flügel. Sie lebt an sauberen Bächen. Wo sie lebt, ist das Wasser gut.'),
  ('insekten', 'Grünes Heupferd', 'Das Grüne Heupferd ist eine grosse Heuschrecke. Am Abend zirpt es laut. Es hat sehr lange Fühler.'),
  ('insekten', 'Alpenbock', 'Der Alpenbock ist ein hellblauer Käfer mit schwarzen Flecken und langen Fühlern. Seine Larven leben in totem Buchenholz. Er ist selten geworden.'),
  ('insekten', 'Hirschkäfer', 'Der Hirschkäfer ist der grösste Käfer der Schweiz. Die Männchen haben Zangen wie ein Geweih. Die Larven leben mehrere Jahre in morschem Holz.'),
  ('insekten', 'Feldgrille', 'Die Feldgrille ist schwarz und glänzt. Sie lebt in einem kleinen Loch in der Wiese. Im Frühling zirpen die Männchen vor ihrem Loch.'),
  ('insekten', 'Hornisse', 'Die Hornisse ist die grösste Wespe der Schweiz. Sie ist friedlich und sticht nur, wenn man ihr Nest stört. Sie frisst viele andere Insekten.'),
  ('insekten', 'Blaugrüne Mosaikjungfer', 'Die Blaugrüne Mosaikjungfer ist eine grosse Libelle. Sie besucht oft Gartenteiche. Manchmal fliegt sie neugierig ganz nahe zu Menschen.'),
  ('insekten', 'Streifenwanze', 'Die Streifenwanze hat rote und schwarze Streifen. Die Farben warnen: Sie schmeckt schlecht. Man findet sie im Sommer auf weissen Blütendolden.'),
  ('insekten', 'Grosses Glühwürmchen', 'Das Glühwürmchen ist ein Käfer. Die Weibchen leuchten in Sommernächten grün. So locken sie die Männchen an.'),
  ('insekten', 'Goldglänzender Rosenkäfer', 'Der Rosenkäfer glänzt grün wie Metall. Er frisst Blütenstaub und Blüten. Seine Larven fressen nur morsches Holz und Kompost.'),
  ('insekten', 'Gemeine Wespe', 'Die Gemeine Wespe kommt im Spätsommer gern an süsses Essen. Ihr Nest baut sie aus zerkautem Holz. Sie fängt viele andere Insekten.'),
  -- Falter
  ('falter', 'Schwalbenschwanz', 'Der Schwalbenschwanz ist ein grosser, schöner Schmetterling. Seine Hinterflügel haben Spitzen wie ein Schwalbenschwanz. Seine Raupe frisst gern an Rüebli und Fenchel.'),
  ('falter', 'Tagpfauenauge', 'Das Tagpfauenauge hat vier grosse Augen auf den Flügeln. Damit erschreckt es Vögel. Seine Raupen fressen Brennnesseln.'),
  ('falter', 'Apollofalter', 'Der Apollofalter ist gross und weiss mit roten Augenflecken. Er fliegt an sonnigen Felshängen in den Bergen. Er ist geschützt.'),
  ('falter', 'Zitronenfalter', 'Der Zitronenfalter ist oft der erste Schmetterling im Jahr. Die Männchen sind zitronengelb. Er überwintert draussen an Zweigen.'),
  ('falter', 'Kleiner Fuchs', 'Der Kleine Fuchs ist ein häufiger, orangeroter Schmetterling. Seine Raupen fressen Brennnesseln. Im Winter versteckt er sich in Kellern oder Scheunen.'),
  ('falter', 'Admiral', 'Der Admiral ist schwarz mit einem roten Band. Viele Admirale fliegen jeden Frühling aus dem Süden zu uns. Im Herbst saugen sie gern an Fallobst.'),
  ('falter', 'Distelfalter', 'Der Distelfalter fliegt sehr weit, von Afrika bis Nordeuropa. Er ist orange mit schwarzen und weissen Flecken. In manchen Jahren kommen Millionen über die Alpen.'),
  ('falter', 'Kaisermantel', 'Der Kaisermantel ist ein grosser, oranger Schmetterling mit schwarzen Flecken. Man sieht ihn im Sommer auf Waldlichtungen. Seine Raupen fressen Veilchen.'),
  ('falter', 'Aurorafalter', 'Der Aurorafalter fliegt im Frühling. Nur die Männchen haben orange Flügelspitzen. Seine Raupen fressen Wiesen-Schaumkraut.'),
  ('falter', 'Grosser Kohlweissling', 'Der Kohlweissling ist weiss mit schwarzen Flügelspitzen. Seine Raupen fressen Kohl. Sie können ein Gemüsebeet kahl fressen.'),
  ('falter', 'Hauhechel-Bläuling', 'Der Hauhechel-Bläuling ist ein kleiner Schmetterling. Die Männchen sind himmelblau. Ameisen beschützen seine Raupen.'),
  ('falter', 'Schachbrett', 'Das Schachbrett hat schwarz-weisse Flügel wie ein Schachbrett. Es fliegt auf Wiesen mit vielen Blumen. Seine Raupen fressen Gräser.'),
  ('falter', 'Grosser Schillerfalter', 'Beim Grossen Schillerfalter schimmern die Flügel der Männchen blau. Er fliegt meist oben in den Bäumen. Er saugt an Pfützen statt an Blüten.'),
  ('falter', 'Taubenschwänzchen', 'Das Taubenschwänzchen ist ein Schmetterling, der am Tag fliegt. Es schwirrt vor den Blüten wie ein Kolibri. Mit seinem langen Rüssel saugt es Nektar.'),
  ('falter', 'Sechsfleck-Widderchen', 'Das Widderchen hat dunkle Flügel mit sechs roten Flecken. Die rote Farbe warnt: Es ist giftig. Es fliegt langsam von Blüte zu Blüte.'),
  ('falter', 'Grosses Ochsenauge', 'Das Grosse Ochsenauge ist ein brauner Schmetterling. Auf jedem Vorderflügel hat es ein schwarzes Auge. Es ist auf Wiesen sehr häufig.'),
  -- Nutztiere
  ('nutztiere', 'Braunvieh', 'Das Braunvieh ist eine graubraune Kuh mit hellem Maul. Es ist eine sehr alte Rasse aus der Schweiz. Man hält es vor allem wegen der Milch.'),
  ('nutztiere', 'Eringer', 'Die Eringerkuh ist klein, kräftig und dunkel. Im Wallis gibt es Kuhkämpfe mit Eringerkühen. Die Siegerin heisst «Königin».'),
  ('nutztiere', 'Simmentaler', 'Das Simmentaler Fleckvieh ist rotbraun und weiss gefleckt. Es hat einen weissen Kopf. Es gibt viel Milch und gutes Fleisch.'),
  ('nutztiere', 'Rätisches Grauvieh', 'Das Rätische Grauvieh ist eine kleine, graue Kuh aus Graubünden. Es klettert gut auf steilen Weiden. Es war fast ausgestorben.'),
  ('nutztiere', 'Freiberger', 'Der Freiberger ist ein Pferd aus dem Jura. Er ist kräftig und ruhig. Man kann ihn reiten oder vor eine Kutsche spannen.'),
  ('nutztiere', 'Einsiedler', 'Das Einsiedler Pferd wird seit dem Mittelalter im Kloster Einsiedeln gezüchtet. Es ist ein elegantes Pferd zum Reiten und Fahren.'),
  ('nutztiere', 'Walliser Schwarznasenschaf', 'Das Schwarznasenschaf hat weisse Wolle und eine schwarze Nase. Auch die Ohren und die Augen sind schwarz umrandet. Es lebt im Sommer auf den Alpen im Wallis.'),
  ('nutztiere', 'Saanenziege', 'Die Saanenziege ist ganz weiss. Sie kommt aus dem Berner Oberland. Sie gibt sehr viel Milch.'),
  ('nutztiere', 'Toggenburger Ziege', 'Die Toggenburger Ziege ist braun mit weissen Streifen im Gesicht. Sie kommt aus dem Toggenburg. Sie ist eine gute Milchziege.'),
  ('nutztiere', 'Walliser Schwarzhalsziege', 'Die Schwarzhalsziege ist vorne schwarz und hinten weiss. Sie hat lange Haare und grosse Hörner. Sie kommt aus dem Wallis.'),
  ('nutztiere', 'Bündner Strahlenziege', 'Die Strahlenziege ist schwarz mit hellen Streifen im Gesicht. Sie ist robust und klettert gut. Sie kommt aus Graubünden.'),
  ('nutztiere', 'Appenzeller Spitzhaubenhuhn', 'Das Spitzhaubenhuhn hat eine spitze Haube aus Federn. Sein Kamm ist klein und erfriert im Winter nicht. Es ist eine alte Schweizer Rasse.'),
  ('nutztiere', 'Schweizer Edelschwein', 'Das Schweizer Edelschwein ist ganz weiss. Es hat stehende Ohren und einen langen Körper. Die Mutterschweine bekommen viele Ferkel.'),
  ('nutztiere', 'Weisses Alpenschaf', 'Das Weisse Alpenschaf ist das häufigste Schaf der Schweiz. Es ist ganz weiss und hat keine Hörner. Im Sommer weidet es auf den Alpen.'),
  ('nutztiere', 'Schweizerhuhn', 'Das Schweizerhuhn ist ganz weiss und hat einen kleinen roten Kamm. Es ist eine alte Schweizer Rasse. Heute ist es selten.'),
  ('nutztiere', 'Evolèner', 'Das Evolènerrind ist eine kleine Kuh aus dem Wallis. Es ist braun bis schwarz mit weissen Flecken. Es kommt gut mit steilen Weiden zurecht.'),
  -- Steine
  ('steine', 'Granit', 'Granit ist ein sehr hartes Gestein. Man sieht darin kleine Kristalle. Es entsteht tief in der Erde aus heissem, flüssigem Gestein.'),
  ('steine', 'Gneis', 'Gneis ist ein Gestein mit Streifen. Es entsteht, wenn andere Gesteine stark gedrückt und erhitzt werden. In den Alpen ist es sehr häufig.'),
  ('steine', 'Kalkstein', 'Kalkstein ist vor langer Zeit im Meer entstanden. Darin findet man oft Versteinerungen. Mit Säure schäumt er.'),
  ('steine', 'Sandstein (Molasse)', 'Sandstein besteht aus vielen Sandkörnern, die zusammenkleben. Er ist eher weich. Die Altstadt von Bern ist aus Sandstein gebaut.'),
  ('steine', 'Nagelfluh', 'Nagelfluh besteht aus runden Kieselsteinen, die wie zusammengeklebt sind. Die Steine sehen aus wie Nagelköpfe. Die Rigi besteht zum grossen Teil aus Nagelfluh.'),
  ('steine', 'Schiefer', 'Schiefer lässt sich in dünne Platten spalten. Früher machte man daraus Schreibtafeln für die Schule. Bekannt ist der Glarner Schiefer.'),
  ('steine', 'Marmor', 'Marmor entsteht aus Kalkstein, der stark erhitzt und gedrückt wurde. Er ist oft ganz weiss. Im Tessin wird weisser Marmor abgebaut.'),
  ('steine', 'Serpentinit', 'Serpentinit ist ein grünes, oft gesprenkeltes Gestein. Es kommt aus grosser Tiefe. Man findet es zum Beispiel bei Zermatt und Davos.'),
  ('steine', 'Bergkristall', 'Bergkristall ist klarer Quarz. Er wächst in Hohlräumen in den Alpen zu sechseckigen Kristallen. Strahler suchen in den Bergen nach Bergkristallen.'),
  ('steine', 'Dolomit', 'Dolomit sieht aus wie Kalkstein. Er bildet helle, steile Felswände. Er zerfällt zu scharfkantigen Steinen.'),
  ('steine', 'Mergel', 'Mergel ist ein weiches Gestein aus Kalk und Ton. Er bildet sanfte Hänge. Man braucht ihn, um Zement herzustellen.'),
  ('steine', 'Gips', 'Gips ist so weich, dass man ihn mit dem Fingernagel ritzen kann. Er entsteht, wenn Meerwasser verdunstet. Man braucht ihn für Wände und Gipsverbände.'),
  ('steine', 'Steinsalz', 'Steinsalz ist Kochsalz als Gestein. Es entstand, als vor sehr langer Zeit Meere austrockneten. In Bex wird es in einem Bergwerk abgebaut.'),
  ('steine', 'Speckstein (Giltstein)', 'Speckstein ist sehr weich und fühlt sich an wie Seife. Er speichert Wärme lange. Darum baute man aus ihm Öfen.'),
  ('steine', 'Flysch', 'Flysch besteht aus vielen dünnen Schichten. Er bildet sanfte, grüne Hügel. Hänge aus Flysch rutschen leicht.'),
  ('steine', 'Verrucano', 'Verrucano ist ein rotes, sehr altes Gestein. In den Glarner Alpen liegt es über jüngerem Gestein. Das kommt daher, dass es bei der Entstehung der Alpen darüber geschoben wurde.'),
  -- Schädlinge
  ('schaedlinge', 'Buchdrucker', 'Der Buchdrucker ist ein kleiner Käfer, der Fichten befällt. Seine Larven fressen Gänge unter der Rinde, und der Baum stirbt. Nach heissen, trockenen Sommern gibt es besonders viele.'),
  ('schaedlinge', 'Kartoffelkäfer', 'Der Kartoffelkäfer hat gelbe Flügel mit schwarzen Streifen. Er frisst die Blätter von Kartoffeln. Er kommt aus Amerika.'),
  ('schaedlinge', 'Buchsbaumzünsler', 'Der Buchsbaumzünsler ist ein Schmetterling aus Asien. Seine grünen Raupen fressen Buchsbäume kahl. Er kam mit Pflanzen nach Europa.'),
  ('schaedlinge', 'Japankäfer', 'Der Japankäfer frisst die Blätter von sehr vielen Pflanzen. Er wurde aus Asien eingeschleppt. Wer ihn findet, muss ihn melden.'),
  ('schaedlinge', 'Kirschessigfliege', 'Die Kirschessigfliege ist eine kleine Fliege aus Asien. Sie legt ihre Eier in reife Kirschen und Beeren. Die Früchte werden dann faul.'),
  ('schaedlinge', 'Marmorierte Baumwanze', 'Die Marmorierte Baumwanze kommt aus Asien. Sie saugt an Obst und Gemüse. Im Herbst kommt sie in Häuser und stinkt, wenn man sie stört.'),
  ('schaedlinge', 'Schwarze Bohnenlaus', 'Die Schwarze Bohnenlaus sitzt in dichten Gruppen an Bohnen und anderen Pflanzen. Sie saugt Pflanzensaft. Sie vermehrt sich sehr schnell.'),
  ('schaedlinge', 'Apfelwickler', 'Der Apfelwickler ist ein kleiner Schmetterling. Seine Raupe ist der «Wurm im Apfel». Sie frisst sich bis zum Kerngehäuse.'),
  ('schaedlinge', 'Eichenprozessionsspinner', 'Die Raupen des Eichenprozessionsspinners wandern in langen Reihen. Sie fressen Eichen kahl. Ihre feinen Haare machen Ausschlag auf der Haut.'),
  ('schaedlinge', 'Rosskastanien-Miniermotte', 'Die Miniermotte ist ein winziger Schmetterling. Ihre Larven fressen Gänge in die Blätter der Rosskastanie. Die Blätter werden schon im Sommer braun.'),
  ('schaedlinge', 'Kirschenfliege', 'Die Kirschenfliege legt ihre Eier in reife Kirschen. Darin wächst eine kleine Made. Die Kirsche wird «wurmig».'),
  ('schaedlinge', 'Kleiner Frostspanner', 'Der Frostspanner fliegt im Spätherbst, wenn es schon kalt ist. Die Weibchen können nicht fliegen und kriechen auf die Bäume. Seine grünen Raupen fressen im Frühling junge Blätter.'),
  ('schaedlinge', 'Maiszünsler', 'Der Maiszünsler ist ein Schmetterling. Seine Raupen bohren sich in Maisstängel. Die Stängel knicken dann ab.'),
  ('schaedlinge', 'Kastaniengallwespe', 'Die Kastaniengallwespe kommt aus China. Sie legt ihre Eier in die Knospen der Edelkastanie. Die Bäume tragen dann weniger Marroni.'),
  ('schaedlinge', 'Rapsglanzkäfer', 'Der Rapsglanzkäfer ist ein winziger, glänzender Käfer. Er beisst die Knospen von Raps an. Dann gibt es weniger Samen.'),
  ('schaedlinge', 'Gefurchter Dickmaulrüssler', 'Der Dickmaulrüssler ist ein schwarzer Käfer, der nachts frisst. Er beisst Löcher in den Rand von Blättern. Seine Larven fressen die Wurzeln.'),
  -- Wetterphänomene
  ('wetterphaenomene', 'Gewitter', 'Bei einem Gewitter blitzt und donnert es. Es entsteht, wenn warme, feuchte Luft schnell aufsteigt. Im Sommer gibt es die meisten Gewitter.'),
  ('wetterphaenomene', 'Föhn', 'Der Föhn ist ein warmer, trockener Wind aus den Bergen. Er weht oft sehr stark. Bei Föhn sieht man sehr weit.'),
  ('wetterphaenomene', 'Nebelmeer', 'Beim Nebelmeer liegt unten im Tal grauer Nebel. Oben auf den Bergen scheint die Sonne. Von dort sieht der Nebel aus wie ein weisses Meer.'),
  ('wetterphaenomene', 'Hagel', 'Hagel sind Körner aus Eis, die aus Gewitterwolken fallen. Sie bestehen aus vielen Schichten wie eine Zwiebel. Hagel kann Autos, Dächer und Obst beschädigen.'),
  ('wetterphaenomene', 'Regenbogen', 'Ein Regenbogen entsteht, wenn die Sonne auf Regentropfen scheint. Das Licht wird in seine Farben zerlegt. Man sieht ihn nur, wenn die Sonne im Rücken ist.'),
  ('wetterphaenomene', 'Schneefall', 'Schnee entsteht in den Wolken, wenn es kalt ist. Jede Schneeflocke besteht aus sechseckigen Kristallen. Frischer Schnee macht alles leiser.'),
  ('wetterphaenomene', 'Bise', 'Die Bise ist ein kalter Wind aus Nordosten. Sie weht durch das Mittelland. Am stärksten ist sie am Genfersee.'),
  ('wetterphaenomene', 'Sturm', 'Ein Sturm ist ein sehr starker Wind. Er kann Bäume umwerfen und Dächer abdecken. In der Schweiz gibt es Stürme vor allem im Herbst und Winter.'),
  ('wetterphaenomene', 'Alpenglühen', 'Beim Alpenglühen leuchten die Berggipfel rot oder rosa. Das sieht man kurz vor Sonnenaufgang oder nach Sonnenuntergang. Die Täler sind dann schon dunkel.'),
  ('wetterphaenomene', 'Raureif', 'Raureif entsteht bei Frost und Nebel. Feine Eisnadeln wachsen an Bäumen und Zäunen. Alles sieht aus wie mit Zucker bestreut.'),
  ('wetterphaenomene', 'Glatteis', 'Glatteis entsteht, wenn Regen auf gefrorenem Boden gefriert. Die dünne Eisschicht sieht man kaum. Darum ist sie sehr gefährlich.'),
  ('wetterphaenomene', 'Hitzewelle', 'Bei einer Hitzewelle ist es mehrere Tage sehr heiss. Manchmal wird es auch in der Nacht nicht kühler als 20 °C. Wegen des Klimawandels gibt es immer mehr Hitzewellen.'),
  ('wetterphaenomene', 'Starkregen', 'Bei Starkregen fällt in kurzer Zeit sehr viel Regen. Bäche treten über die Ufer, und Keller werden nass. In den Bergen kann Erde und Geröll abrutschen.'),
  ('wetterphaenomene', 'Saharastaub', 'Manchmal bringt der Wind Staub aus der Sahara bis in die Schweiz. Der Himmel wird dann gelb oder orange. Auch der Schnee kann orange werden.'),
  ('wetterphaenomene', 'Berg- und Talwind', 'In Bergtälern wechselt der Wind jeden Tag die Richtung. Am Tag weht er den Berg hinauf, in der Nacht hinunter. Das kommt von der Sonne, die die Hänge wärmt.'),
  ('wetterphaenomene', 'Halo', 'Ein Halo ist ein heller Ring um die Sonne oder den Mond. Er entsteht in Wolken aus winzigen Eiskristallen. Manchmal sieht man daneben helle Flecken.'),
  ('wetterphaenomene', 'Cumulus-Wolke', 'Die Cumulus-Wolke ist eine Haufenwolke. Sie ist unten flach und oben rund wie Blumenkohl. Kleine Haufenwolken sieht man bei schönem Wetter.'),
  ('wetterphaenomene', 'Stratus-Wolke', 'Die Stratus-Wolke ist eine graue, tiefe Wolkenschicht. Im Winter liegt sie oft als Hochnebel über dem Mittelland. Oben in den Bergen scheint dann die Sonne.'),
  ('wetterphaenomene', 'Cirrus-Wolke', 'Cirrus-Wolken sind hohe, feine Wolken wie weisse Federn. Sie bestehen aus Eiskristallen. Oft kündigen sie einen Wetterwechsel an.'),
  -- Berge
  ('berge', 'Tödi', 'Der Tödi ist der höchste Berg der Glarner Alpen. Man nennt ihn «König der Glarner Alpen». An seinem Fuss beginnt die Linth.'),
  ('berge', 'Dufourspitze', 'Die Dufourspitze ist der höchste Berg der Schweiz. Sie liegt im Wallis und ist 4634 m hoch. Sie heisst nach General Dufour, der eine genaue Karte der Schweiz machen liess.'),
  ('berge', 'Dom', 'Der Dom ist der höchste Berg, der ganz in der Schweiz steht. Er liegt im Wallis bei Saas-Fee. Er ist über 4500 m hoch.'),
  ('berge', 'Weisshorn', 'Das Weisshorn sieht aus wie eine Pyramide mit drei Kanten. Viele finden, es ist einer der schönsten Berge der Alpen. Es steht im Wallis.'),
  ('berge', 'Eiger', 'Der Eiger hat eine riesige, fast senkrechte Nordwand. Sie ist sehr schwierig zu besteigen. Zusammen mit Mönch und Jungfrau ist er sehr berühmt.'),
  ('berge', 'Finsteraarhorn', 'Das Finsteraarhorn ist der höchste Berg der Berner Alpen. Es steht mitten in riesigen Gletschern. Von den Tälern aus sieht man es kaum.'),
  ('berge', 'Piz Bernina', 'Der Piz Bernina ist der höchste Berg in Graubünden. Er ist über 4000 m hoch. Sein langer, schneeweisser Grat heisst «Himmelsleiter».'),
  ('berge', 'Titlis', 'Der Titlis steht über Engelberg. Viele Menschen fahren mit der Bahn hinauf. Die Gondel dreht sich auf dem Weg einmal im Kreis.'),
  ('berge', 'Säntis', 'Der Säntis ist der höchste Berg im Alpstein in der Ostschweiz. Vom Gipfel sieht man bis in sechs Länder. Oben steht ein hoher Sendeturm.'),
  ('berge', 'Pilatus', 'Der Pilatus ist der Hausberg von Luzern. Es gibt viele Sagen über Drachen auf dem Pilatus. Eine sehr steile Zahnradbahn fährt hinauf.'),
  ('berge', 'Rigi', 'Die Rigi heisst «Königin der Berge». Sie steht zwischen mehreren Seen. Hier fuhr die erste Bergbahn Europas.'),
  ('berge', 'Grosser Mythen', 'Der Grosse Mythen ist ein steiler Felszahn über Schwyz. Sein Gestein ist älter als der Boden darunter. Ein steiler Weg führt auf den Gipfel.'),
  ('berge', 'Niesen', 'Der Niesen sieht aus wie eine Pyramide am Thunersee. Eine Bahn fährt hinauf. Neben der Bahn gibt es die längste Treppe der Welt.'),
  ('berge', 'Chasseral', 'Der Chasseral ist der höchste Berg im Berner Jura. Von oben sieht man die ganze Alpenkette. Auf dem Gipfel steht ein hoher Sendeturm.'),
  ('berge', 'Monte Generoso', 'Der Monte Generoso liegt ganz im Süden der Schweiz. Eine Zahnradbahn fährt hinauf. Von oben sieht man über die Seen bis nach Italien.'),
  ('berge', 'Matterhorn', 'Das Matterhorn ist der bekannteste Berg der Schweiz. Es hat die Form einer Pyramide. Jedes Jahr wollen viele Bergsteiger hinauf.'),
  ('berge', 'Glärnisch', 'Der Glärnisch ist ein grosses Bergmassiv über der Stadt Glarus. Er hat drei hohe Gipfel und einen Gletscher. Der Gletscher wird wegen der Klimaerwärmung kleiner.'),
  ('berge', 'Hausstock', 'Der Hausstock ist einer der höchsten Berge der Glarner Alpen. Er steht an der Grenze zu Graubünden. Von Elm aus sieht man seine steile Wand.'),
  ('berge', 'Kärpf', 'Der Kärpf liegt im ältesten Wildschutzgebiet Europas. Seit 1548 darf man dort nicht jagen. Heute leben dort viele Gämsen und Steinböcke.'),
  ('berge', 'Ortstock', 'Der Ortstock ist der Hausberg von Braunwald. Er steht an der Grenze von Glarus und Schwyz. Seine Wände sind sehr steil.'),
  -- Gewässer
  ('gewaesser', 'Genfersee', 'Der Genfersee ist der grösste See der Alpen. Ein Teil gehört zu Frankreich. Die Rhone fliesst durch ihn hindurch.'),
  ('gewaesser', 'Bodensee', 'Der Bodensee liegt zwischen der Schweiz, Deutschland und Österreich. Der Rhein fliesst durch ihn hindurch. Im Sommer baden viele Menschen darin.'),
  ('gewaesser', 'Vierwaldstättersee', 'Der Vierwaldstättersee hat viele Arme zwischen steilen Bergen. Er heisst nach vier alten Orten der Eidgenossenschaft. Am Ufer liegt die Rütliwiese.'),
  ('gewaesser', 'Zürichsee', 'Der Zürichsee ist über 40 km lang. In Zürich fliesst die Limmat aus dem See. Ein grosser Teil des Zürcher Trinkwassers kommt aus dem See.'),
  ('gewaesser', 'Neuenburgersee', 'Der Neuenburgersee ist der grösste See, der ganz in der Schweiz liegt. Am Ufer gibt es viel Schilf. Dort leben viele Vögel.'),
  ('gewaesser', 'Lago Maggiore', 'Der Lago Maggiore liegt zum grössten Teil in Italien. Hier ist der tiefste Punkt der Schweiz. Am Ufer wachsen sogar Palmen.'),
  ('gewaesser', 'Walensee', 'Der Walensee liegt zwischen steilen Bergen. Das Dorf Quinten am Ufer erreicht man nur zu Fuss oder mit dem Schiff. Dort ist es so warm, dass Feigen wachsen.'),
  ('gewaesser', 'Silsersee', 'Der Silsersee liegt hoch oben im Engadin. Im Winter friert er zu. Dann kann man auf dem Eis spazieren.'),
  ('gewaesser', 'Rhein', 'Der Rhein beginnt in Graubünden. Er fliesst durch den Bodensee und über den Rheinfall nach Basel. Am Ende fliesst er in die Nordsee.'),
  ('gewaesser', 'Rhone', 'Die Rhone beginnt am Rhonegletscher. Sie fliesst durch das Wallis und den Genfersee. Am Ende fliesst sie ins Mittelmeer.'),
  ('gewaesser', 'Aare', 'Die Aare ist der längste Fluss, der ganz in der Schweiz fliesst. Sie fliesst auch durch Bern. Im Sommer schwimmen dort viele Leute in der Aare.'),
  ('gewaesser', 'Reuss', 'Die Reuss beginnt am Gotthard. Sie fliesst durch eine wilde Schlucht und durch die Stadt Luzern. Später fliesst sie in die Aare.'),
  ('gewaesser', 'Inn', 'Der Inn fliesst durch das Engadin. Das Wort Engadin bedeutet «Tal des Inn». Sein Wasser kommt bis ins Schwarze Meer.'),
  ('gewaesser', 'Ticino', 'Der Ticino beginnt am Nufenenpass. Er gab dem Kanton Tessin seinen Namen. Er fliesst in den Lago Maggiore.'),
  ('gewaesser', 'Doubs', 'Der Doubs bildet die Grenze zwischen der Schweiz und Frankreich. Er fliesst in grossen Schleifen durch den Jura. An einer Stelle stürzt er als Wasserfall in die Tiefe.'),
  ('gewaesser', 'Thunersee', 'Der Thunersee liegt im Berner Oberland. Die Aare fliesst durch ihn. Am Ufer stehen schöne Schlösser.'),
  ('gewaesser', 'Klöntalersee', 'Der Klöntalersee liegt westlich von Glarus unter steilen Felswänden. Er entstand durch einen Bergsturz. Sein Wasser wird für Strom gebraucht.'),
  ('gewaesser', 'Linth', 'Die Linth fliesst durch das ganze Glarnerland. Sie beginnt hinter Linthal. Heute fliesst sie durch einen Kanal in den Walensee.'),
  ('gewaesser', 'Limmernsee', 'Der Limmernsee ist ein Stausee hoch über Linthal. Wenn es viel Strom gibt, wird Wasser nach oben gepumpt. Braucht man Strom, fliesst es durch Turbinen zurück.'),
  ('gewaesser', 'Obersee', 'Der Obersee liegt in einem stillen Tal über Näfels. Bei ruhigem Wetter spiegeln sich die Berge im Wasser. Viele Leute wandern dorthin.'),
  -- Sehenswürdigkeiten
  ('sehenswuerdigkeiten', 'Kapellbrücke', 'Die Kapellbrücke in Luzern ist eine alte Holzbrücke mit Dach. Unter dem Dach hängen alte Bilder. Daneben steht ein achteckiger Turm im Wasser.'),
  ('sehenswuerdigkeiten', 'Schloss Chillon', 'Das Schloss Chillon steht auf einem Felsen im Genfersee. Es ist viele Hundert Jahre alt. Sehr viele Menschen besuchen es.'),
  ('sehenswuerdigkeiten', 'Zytglogge', 'Der Zytglogge ist ein alter Turm in Bern mit einer besonderen Uhr. Kurz vor jeder vollen Stunde bewegen sich Figuren. Früher war der Turm ein Stadttor.'),
  ('sehenswuerdigkeiten', 'Landwasserviadukt', 'Das Landwasserviadukt ist eine hohe, gebogene Brücke aus Stein. Die Züge fahren darüber direkt in einen Tunnel im Felsen. Es steht in Graubünden.'),
  ('sehenswuerdigkeiten', 'Lavaux', 'Im Lavaux wachsen Reben auf Terrassen am Genfersee. Mönche haben sie vor langer Zeit angelegt. Die Landschaft ist Welterbe.'),
  ('sehenswuerdigkeiten', 'Jungfraujoch', 'Auf das Jungfraujoch fährt eine Bahn durch den Berg. Dort ist der höchste Bahnhof Europas. Von oben sieht man den grossen Aletschgletscher.'),
  ('sehenswuerdigkeiten', 'Stiftsbezirk St. Gallen', 'Im Stiftsbezirk in St. Gallen stand früher ein grosses Kloster. Die Bibliothek ist einer der schönsten Büchersäle der Welt. Dort liegen sehr alte Bücher.'),
  ('sehenswuerdigkeiten', 'Burgen von Bellinzona', 'In Bellinzona stehen drei alte Burgen. Mit einer langen Mauer sperrten sie früher das ganze Tal ab. So bewachten sie den Weg über die Alpen.'),
  ('sehenswuerdigkeiten', 'Jet d''eau', 'Der Jet d''eau ist eine riesige Wasserfontäne im Genfersee. Das Wasser spritzt bis 140 m hoch. Sie ist das Wahrzeichen von Genf.'),
  ('sehenswuerdigkeiten', 'Bundeshaus', 'Im Bundeshaus in Bern arbeitet das Parlament der Schweiz. Auch der Bundesrat hat hier seine Büros. Das Haus hat eine grüne Kuppel.'),
  ('sehenswuerdigkeiten', 'Grossmünster', 'Das Grossmünster ist eine Kirche mit zwei Türmen in Zürich. Hier predigte Zwingli. Von einem Turm sieht man über die Stadt.'),
  ('sehenswuerdigkeiten', 'Kloster Einsiedeln', 'Das Kloster Einsiedeln ist der wichtigste Wallfahrtsort der Schweiz. In der Kirche steht die Schwarze Madonna. Viele Pilger kommen hierher.'),
  ('sehenswuerdigkeiten', 'Rütli', 'Das Rütli ist eine Wiese über dem Urnersee. Nach der Sage wurde hier die Eidgenossenschaft gegründet. Am 1. August wird hier gefeiert.'),
  ('sehenswuerdigkeiten', 'Schloss Greyerz', 'Das Schloss Greyerz steht auf einem Hügel im Kanton Freiburg. Heute ist es ein Museum. Der Ort ist auch für seinen Käse bekannt.'),
  ('sehenswuerdigkeiten', 'Munot', 'Der Munot ist eine runde Festung in Schaffhausen. Im Turm wohnt ein Wächter. Jeden Abend läutet er eine Glocke.'),
  ('sehenswuerdigkeiten', 'Kloster St. Johann', 'Das Kloster St. Johann in Müstair ist sehr alt. In der Kirche gibt es Wandbilder, die über 1200 Jahre alt sind. Noch heute leben dort Nonnen.'),
  ('sehenswuerdigkeiten', 'Freulerpalast', 'Der Freulerpalast in Näfels ist ein prächtiges altes Haus. Ein Offizier liess es vor fast 400 Jahren bauen. Heute ist darin das Museum des Kantons Glarus.'),
  ('sehenswuerdigkeiten', 'Landesplattenberg Engi', 'Im Landesplattenberg in Engi wurde früher Schiefer abgebaut. Daraus machte man zum Beispiel Schreibtafeln. Heute kann man das Bergwerk besuchen.'),
  ('sehenswuerdigkeiten', 'Pantenbrücke', 'Die Pantenbrücke führt hinter Linthal über eine tiefe Schlucht. Dort stehen zwei Brücken übereinander. Die erste Brücke gab es schon vor über 550 Jahren.'),
  ('sehenswuerdigkeiten', 'Escherkanal', 'Der Escherkanal leitet die Linth in den Walensee. Früher gab es in der Linthebene oft Überschwemmungen. Der Kanal schützt das Land davor.'),
  ('sehenswuerdigkeiten', 'Braunwald', 'Braunwald ist ein Dorf ohne Autos hoch über Linthal. Man fährt mit einer Bahn hinauf. Im Sommer kann man wandern, im Winter Ski fahren.'),
  -- Naturwunder
  ('naturwunder', 'Rheinfall', 'Der Rheinfall ist der grösste Wasserfall Europas. Der Rhein stürzt dort sehr breit in die Tiefe. Mit dem Boot kann man zum Felsen in der Mitte fahren.'),
  ('naturwunder', 'Grosser Aletschgletscher', 'Der Grosse Aletschgletscher ist der grösste Gletscher der Alpen. Er ist etwa 20 km lang. Wegen der Klimaerwärmung wird er jedes Jahr kürzer.'),
  ('naturwunder', 'Oeschinensee', 'Der Oeschinensee ist ein türkisblauer Bergsee bei Kandersteg. Er entstand durch einen Bergsturz. Sein Wasser kommt von schmelzendem Schnee und Eis.'),
  ('naturwunder', 'Creux du Van', 'Der Creux du Van ist ein riesiger Felsenkessel im Jura. Die Felswände sind sehr hoch und senkrecht. Dort sieht man manchmal Steinböcke.'),
  ('naturwunder', 'Staubbachfall', 'Der Staubbachfall stürzt fast 300 m eine Felswand hinunter. Das Wasser wird dabei zu feinem Nebel. Er ist im Lauterbrunnental.'),
  ('naturwunder', 'Martinsloch', 'Das Martinsloch ist ein grosses Loch im Fels über Elm. Zweimal im Jahr scheint die Sonne hindurch auf die Kirche von Elm. Darunter sieht man eine besondere Linie im Gestein.'),
  ('naturwunder', 'Trümmelbachfälle', 'Die Trümmelbachfälle sind Wasserfälle im Innern eines Berges. Ihr Wasser kommt von Gletschern. Ein Lift fährt im Berg hinauf.'),
  ('naturwunder', 'Aareschlucht', 'Die Aareschlucht bei Meiringen ist tief und eng. An einer Stelle ist sie nur etwa einen Meter breit. Ein Weg führt an den Felswänden entlang.'),
  ('naturwunder', 'Rhonegletscher', 'Am Rhonegletscher beginnt die Rhone. Der Gletscher ist schon viel kleiner geworden. Im Sommer deckt man ihn teilweise mit weissen Tüchern ab.'),
  ('naturwunder', 'Viamala-Schlucht', 'Die Viamala ist eine tiefe, enge Schlucht in Graubünden. Ihr Name bedeutet «schlechter Weg». Viele Treppen führen hinunter zum Fluss.'),
  ('naturwunder', 'Ruinaulta', 'Die Ruinaulta ist eine Schlucht des Rheins in Graubünden. Man nennt sie «Swiss Grand Canyon». Sie entstand nach einem riesigen Bergsturz.'),
  ('naturwunder', 'Hölloch', 'Das Hölloch im Muotathal ist eine der längsten Höhlen der Welt. Man kennt schon über 200 km Gänge. Einen kleinen Teil kann man besuchen.'),
  ('naturwunder', 'Giessbachfälle', 'Die Giessbachfälle stürzen in vielen Stufen in den Brienzersee. An einer Stelle geht ein Weg hinter dem Wasser durch. Am Abend sind sie beleuchtet.'),
  ('naturwunder', 'Seealpsee', 'Der Seealpsee liegt am Fuss des Säntis. Im grünen Wasser spiegeln sich die Felswände. Man wandert etwa eine Stunde bis zum See.'),
  ('naturwunder', 'Morteratschgletscher', 'Der Morteratschgletscher ist ein grosser Gletscher in Graubünden. Ein Weg mit Tafeln zeigt, wo das Eis früher war. Er ist schon über zwei Kilometer kürzer geworden.'),
  ('naturwunder', 'Taminaschlucht', 'In der Taminaschlucht bei Bad Ragaz gibt es eine warme Quelle. Früher liess man Kranke an Seilen hinunter, damit sie baden konnten. Heute führt ein Weg zur Quelle.'),
  ('naturwunder', 'Lochsite', 'Bei der Lochsite in Schwanden liegt altes Gestein über jüngerem. Man kann die Linie dazwischen mit dem Finger berühren. Das kommt von der Entstehung der Alpen.'),
  ('naturwunder', 'Berglistüber', 'Der Berglistüber ist ein Wasserfall bei Linthal. Das Wasser fällt etwa 40 m tief. Vom Parkplatz sind es nur wenige Minuten.'),
  -- Spezialitäten
  ('spezialitaeten', 'Fondue', 'Beim Fondue tunkt man Brot in geschmolzenen Käse. Der Käse wird in einem Topf warm gehalten. Fondue ist ein Nationalgericht der Schweiz.'),
  ('spezialitaeten', 'Raclette', 'Beim Raclette schmilzt man Käse und schabt ihn auf den Teller. Dazu gibt es Kartoffeln und Essiggurken. Raclette kommt aus dem Wallis.'),
  ('spezialitaeten', 'Rösti', 'Rösti macht man aus geraffelten Kartoffeln. Sie wird in der Pfanne goldbraun gebraten. Früher war sie ein Frühstück im Kanton Bern.'),
  ('spezialitaeten', 'Zürcher Geschnetzeltes', 'Beim Zürcher Geschnetzelten gibt es feine Streifen Kalbfleisch. Dazu gibt es eine Sauce mit Rahm und Pilzen. Meist isst man Rösti dazu.'),
  ('spezialitaeten', 'Älplermagronen', 'Älplermagronen kocht man aus Teigwaren, Kartoffeln, Käse und Rahm. Oben drauf kommen geröstete Zwiebeln. Dazu isst man Apfelmus.'),
  ('spezialitaeten', 'Birchermüesli', 'Das Birchermüesli hat ein Arzt aus Zürich erfunden. Es besteht vor allem aus geriebenem Apfel und Haferflocken. Heute kennt man es auf der ganzen Welt.'),
  ('spezialitaeten', 'Basler Läckerli', 'Basler Läckerli sind harte Lebkuchen aus Basel. Sie enthalten Honig, Mandeln und kandierte Früchte. Oben haben sie eine Zuckerglasur.'),
  ('spezialitaeten', 'Zuger Kirschtorte', 'Die Zuger Kirschtorte ist eine Torte aus Zug. Sie ist mit Kirsch getränkt. Oben ist sie mit Mandeln und Puderzucker bedeckt.'),
  ('spezialitaeten', 'Bündner Nusstorte', 'Die Bündner Nusstorte ist mit Baumnüssen und Karamell gefüllt. Sie kommt aus dem Engadin. Sie ist sehr süss und hält lange.'),
  ('spezialitaeten', 'Berner Platte', 'Die Berner Platte ist ein grosses Essen mit viel Fleisch und Würsten. Dazu gibt es Sauerkraut, Bohnen und Kartoffeln. Man isst sie in grossen Runden.'),
  ('spezialitaeten', 'Luzerner Chügelipastete', 'Die Chügelipastete ist eine grosse Pastete aus Blätterteig. Darin sind kleine Fleischkugeln in einer Sauce. Sie ist ein Festessen in Luzern.'),
  ('spezialitaeten', 'St. Galler Bratwurst', 'Die St. Galler Bratwurst ist eine helle Wurst. Man isst sie ohne Senf. Dazu gibt es ein knuspriges Brot, das Bürli.'),
  ('spezialitaeten', 'Polenta', 'Polenta ist ein dicker Brei aus Mais. Man rührt sie lange in einem Topf. Im Tessin isst man sie oft mit Ragout oder Käse.'),
  ('spezialitaeten', 'Schabziger', 'Der Schabziger ist ein grüner Käse aus Glarus. Er hat die Form eines kleinen Kegels. Ein Kraut gibt ihm die grüne Farbe und den starken Geschmack.'),
  ('spezialitaeten', 'Glarner Kalberwurst', 'Die Glarner Kalberwurst ist eine helle Wurst aus Kalbfleisch, Milch und Brot. Dazu gibt es Zwiebelsauce und Kartoffelstock. Oft gibt es auch gedörrte Zwetschgen.'),
  ('spezialitaeten', 'Glarner Pastete', 'Die Glarner Pastete ist ein süsses Gebäck aus Blätterteig. Die eine Hälfte ist mit Mandeln gefüllt, die andere mit Zwetschgen. Oft sitzt ein Fridolin aus Marzipan darauf.'),
  -- Geschichte
  ('geschichte', 'Bundesbrief 1291', 'Im Bundesbrief von 1291 versprachen sich Uri, Schwyz und Unterwalden Hilfe. Er gilt als Anfang der Eidgenossenschaft. Darum feiern wir am 1. August.'),
  ('geschichte', 'Wilhelm Tell', 'Wilhelm Tell ist ein Held aus einer Sage. Er musste einen Apfel vom Kopf seines Sohnes schiessen. Ob es Tell wirklich gab, weiss man nicht.'),
  ('geschichte', 'Schlacht am Morgarten', 'Im Jahr 1315 besiegten die Schwyzer bei Morgarten die Ritter der Habsburger. Sie griffen sie auf einem schmalen Weg am See an. Der Sieg machte ihren Bund stärker.'),
  ('geschichte', 'Schlacht bei Sempach', 'Im Jahr 1386 siegten die Eidgenossen bei Sempach gegen die Habsburger. Ihr Herzog starb in der Schlacht. Eine Sage erzählt vom Helden Winkelried.'),
  ('geschichte', 'Schlacht bei Näfels', 'Im Jahr 1388 siegten die Glarner bei Näfels gegen ein grösseres Heer der Habsburger. Daran denkt man jedes Jahr an der Näfelser Fahrt. Sie ist im April.'),
  ('geschichte', 'Schlacht bei Marignano', 'Im Jahr 1515 verloren die Eidgenossen bei Marignano in Italien gegen Frankreich. Sehr viele Soldaten starben. Danach wollten sie keine Länder mehr erobern.'),
  ('geschichte', 'Huldrych Zwingli', 'Zwingli war Pfarrer in Zürich. Er brachte dort die Reformation, eine neue Form des Glaubens. Vorher war er zehn Jahre Pfarrer in Glarus.'),
  ('geschichte', 'Helvetische Republik', 'Im Jahr 1798 eroberte Frankreich die Schweiz. Alle Bürger bekamen gleiche Rechte. Nach fünf Jahren war diese Zeit wieder vorbei.'),
  ('geschichte', 'Bundesverfassung 1848', 'Im Jahr 1848 bekam die Schweiz eine neue Verfassung. Seither gibt es den Bundesrat und das Parlament. Bern wurde Bundesstadt.'),
  ('geschichte', 'Henri Dunant', 'Henri Dunant aus Genf sah, wie verletzte Soldaten litten. Darum gründete er das Rote Kreuz mit. Es hilft allen Verletzten, egal auf welcher Seite.'),
  ('geschichte', 'Gotthardtunnel', 'Im Jahr 1882 wurde der Bahntunnel durch den Gotthard fertig. Er war damals der längste Tunnel der Welt. Beim Bau starben viele Arbeiter.'),
  ('geschichte', 'Brand von Glarus', 'Im Jahr 1861 brannte der grösste Teil der Stadt Glarus ab. Der Föhn blies das Feuer durch die Gassen. Danach baute man die Stadt mit geraden Strassen neu.'),
  ('geschichte', 'Bergsturz von Elm', 'Im Jahr 1881 stürzte bei Elm ein Berg ins Tal. Viele Menschen starben. Schuld war, dass man unten am Berg unvorsichtig Schiefer abgebaut hatte.'),
  ('geschichte', 'Heiliger Fridolin', 'Fridolin ist der Schutzpatron von Glarus. Er steht im Glarner Wappen. Am 6. März feiert man den Fridolinstag mit Feuern.'),
  ('geschichte', 'Landesstreik 1918', 'Im Jahr 1918 hörten in der ganzen Schweiz sehr viele Menschen auf zu arbeiten. Sie wollten bessere Arbeit und mehr Rechte. Einiges davon bekamen sie später.'),
  ('geschichte', 'Rütlirapport 1940', 'Im Zweiten Weltkrieg rief General Guisan die Offiziere auf das Rütli. Er sagte, die Schweiz werde sich verteidigen. Das machte vielen Menschen Mut.'),
  -- Politik
  ('politik', 'Bundesrat', 'Der Bundesrat ist die Regierung der Schweiz. Er hat sieben Mitglieder. Sie entscheiden gemeinsam.'),
  ('politik', 'Nationalrat', 'Der Nationalrat ist ein Teil des Parlaments. Er hat 200 Mitglieder. Grosse Kantone haben mehr Sitze als kleine.'),
  ('politik', 'Ständerat', 'Der Ständerat ist der andere Teil des Parlaments. Er vertritt die Kantone. Fast jeder Kanton hat zwei Sitze.'),
  ('politik', 'Bundespräsident', 'Jedes Jahr wird ein Mitglied des Bundesrats Bundespräsidentin oder Bundespräsident. Diese Person leitet die Sitzungen. Sie ist aber nicht Chef der anderen.'),
  ('politik', 'Bundesgericht', 'Das Bundesgericht ist das höchste Gericht der Schweiz. Es ist in Lausanne. Dort wird zum letzten Mal über einen Streit entschieden.'),
  ('politik', 'Volksinitiative', 'Mit einer Volksinitiative können Bürgerinnen und Bürger etwas Neues verlangen. Dafür braucht es 100 000 Unterschriften. Dann stimmt das ganze Volk darüber ab.'),
  ('politik', 'Referendum', 'Mit einem Referendum kann das Volk über ein neues Gesetz abstimmen. Dafür braucht es 50 000 Unterschriften. Änderungen der Verfassung kommen immer vors Volk.'),
  ('politik', 'Föderalismus', 'In der Schweiz entscheiden Bund, Kantone und Gemeinden. Jeder Kanton hat eigene Gesetze. Darum sind zum Beispiel die Schulen nicht überall gleich.'),
  ('politik', 'Neutralität', 'Die Schweiz ist neutral. Sie macht bei Kriegen anderer Länder nicht mit. Darum treffen sich hier oft Länder zu Friedensgesprächen.'),
  ('politik', 'Frauenstimmrecht', 'Erst seit 1971 dürfen Frauen in der Schweiz abstimmen und wählen. Das ist viel später als in anderen Ländern. Vorher durften nur Männer abstimmen.'),
  ('politik', 'Milizsystem', 'In der Schweiz machen viele Leute neben ihrem Beruf ein Amt. Sie sind zum Beispiel im Gemeinderat oder in der Feuerwehr. Das nennt man Milizsystem.'),
  ('politik', 'Gemeindeversammlung', 'An der Gemeindeversammlung entscheiden die Leute eines Dorfes selbst. Alle Stimmberechtigten dürfen mitreden. Es geht zum Beispiel um Geld und Bauprojekte.'),
  ('politik', 'Landsgemeinde', 'An der Landsgemeinde in Glarus stimmen die Leute draussen auf einem Platz ab. Sie heben dazu die Hand. Schon ab 16 Jahren darf man mitmachen.'),
  ('politik', 'Glarner Gemeindereform', 'Früher hatte der Kanton Glarus 25 Gemeinden. Seit 2011 sind es nur noch drei. Das hat die Landsgemeinde so entschieden.'),
  ('politik', 'Stimmrecht ab 16', 'Im Kanton Glarus dürfen Jugendliche schon ab 16 abstimmen. Glarus war der erste Kanton, der das erlaubt hat. Das war im Jahr 2007.'),
  ('politik', 'Landrat Glarus', 'Der Landrat ist das Parlament des Kantons Glarus. Er hat 60 Mitglieder. Das letzte Wort hat aber oft das Volk an der Landsgemeinde.')
  ) as v(cat, name, txt)
 where e.category_id = v.cat and e.name = v.name and e.simple = '';

update public.app_meta set schema_version = 27, updated_at = now();

commit;
