// Bisherige Daten aus index.html (nur für die einmalige Migration nach Supabase)
window.CATS = [
{ id:"baeume", name:"Bäume", desc:"Die wichtigsten Waldbäume", latin:true, cover:3,
  labels:["Baum","Blätter","Früchte","Rinde"],
  items:[
  { n:"Fichte (Rottanne)", s:"Picea abies", lb:["Baum","Nadeln","Zapfen","Rinde"],
    q:["Picea abies needles","Picea abies cones","Picea abies bark"],
    t:"Die Fichte ist mit Abstand der häufigste Baum im Schweizer Wald und liefert fast die Hälfte des Holzvorrats. Ihre spitzen, vierkantigen Nadeln stehen rund um den Zweig. Die Zapfen hängen nach unten und fallen als Ganzes ab. Als Flachwurzler ist sie anfällig für Sturm, Trockenheit und den Borkenkäfer.",
    f:{Höhe:"bis 50 m", Alter:"bis 600 Jahre", Vorkommen:"Voralpen, Alpen, auch Mittelland (oft gepflanzt)", Merkmal:"hängende Zapfen, rötliche Rinde"} },
  { n:"Buche", s:"Fagus sylvatica", lb:["Baum","Blätter","Bucheckern","Rinde"],
    q:["Fagus sylvatica leaves","Fagus sylvatica beechnuts","Fagus sylvatica bark"],
    t:"Die Rotbuche ist der häufigste Laubbaum der Schweiz und würde ohne menschlichen Einfluss grosse Teile des Mittellandes und des Juras bedecken. Typisch sind die glatte, silbergraue Rinde und die eiförmigen Blätter mit leicht gewelltem, bewimpertem Rand. Ihre dreikantigen Früchte heissen Bucheckern.",
    f:{Höhe:"bis 40 m", Alter:"bis 300 Jahre", Vorkommen:"Mittelland, Jura, bis ca. 1500 m", Merkmal:"glatte, silbergraue Rinde"} },
  { n:"Weisstanne", s:"Abies alba", lb:["Baum","Nadeln","Zapfen","Rinde"],
    q:["Abies alba needles","Abies alba cones","Abies alba bark"],
    t:"Die Weisstanne erkennt man an den flachen, stumpfen Nadeln mit zwei weissen Streifen auf der Unterseite. Ihre Zapfen stehen aufrecht auf den Zweigen und zerfallen noch am Baum – am Boden findet man deshalb nie ganze Tannzapfen. Dank ihrer tiefen Pfahlwurzel ist sie sturmfester als die Fichte.",
    f:{Höhe:"bis 50 m", Alter:"bis 600 Jahre", Vorkommen:"Jura, Voralpen, 500–1500 m", Merkmal:"aufrechte Zapfen, weissgraue Rinde"} },
  { n:"Lärche", s:"Larix decidua", lb:["Baum","Nadeln","Zapfen","Rinde"],
    q:["Larix decidua needles","Larix decidua cones","Larix decidua bark"],
    t:"Die Europäische Lärche ist der einzige einheimische Nadelbaum, der im Herbst seine Nadeln abwirft – vorher färbt sie ganze Berghänge goldgelb. Die weichen Nadeln wachsen in Büscheln. Sie liebt Licht und steigt in den Alpen, etwa im Wallis und in Graubünden, bis an die Waldgrenze.",
    f:{Höhe:"bis 45 m", Alter:"bis 1000 Jahre", Vorkommen:"Zentral- und Südalpen, bis 2400 m", Merkmal:"wirft im Herbst die Nadeln ab"} },
  { n:"Waldföhre", s:"Pinus sylvestris", lb:["Baum","Nadeln","Zapfen","Rinde"],
    q:["Pinus sylvestris needles","Pinus sylvestris cone","Pinus sylvestris bark"],
    t:"Die Waldföhre (Waldkiefer) trägt jeweils zwei lange, oft gedrehte Nadeln pro Kurztrieb. Im oberen Stammbereich leuchtet ihre Rinde fuchsrot, unten ist sie grau und tief gefurcht. Als genügsamer Pionierbaum wächst sie auch an sehr trockenen Standorten, zum Beispiel im Wallis.",
    f:{Höhe:"bis 40 m", Alter:"bis 600 Jahre", Vorkommen:"trockene Hänge, Wallis, Jura, Mittelland", Merkmal:"orangerote Rinde im Oberstamm"} },
  { n:"Bergahorn", s:"Acer pseudoplatanus",
    q:["Acer pseudoplatanus leaves","Acer pseudoplatanus fruit samara","Acer pseudoplatanus bark"],
    t:"Der Bergahorn ist der häufigste Ahorn der Schweiz. Seine grossen Blätter sind fünflappig mit stumpfen Buchten. Die Doppel-Flügelfrüchte («Nasenzwicker») stehen etwa im rechten Winkel zueinander und segeln wie Propeller zu Boden. Ältere Bäume haben eine schuppig abblätternde Rinde. Das helle Holz ist im Instrumenten- und Möbelbau beliebt.",
    f:{Höhe:"bis 35 m", Alter:"bis 500 Jahre", Vorkommen:"ganze Schweiz, bis ca. 1800 m", Merkmal:"Flügelfrüchte, schuppige Rinde"} },
  { n:"Esche", s:"Fraxinus excelsior",
    q:["Fraxinus excelsior leaves","Fraxinus excelsior fruit","Fraxinus excelsior bark"],
    t:"Die Gemeine Esche hat unpaarig gefiederte Blätter und auffällige schwarze Knospen. Ihre Früchte sind einseitig geflügelte Nüsschen, die in Büscheln hängen. Das zähe, elastische Holz wird für Werkzeugstiele und Sportgeräte verwendet. Seit etwa 2008 leidet die Esche in der Schweiz stark unter dem Eschentriebsterben, einer Pilzkrankheit.",
    f:{Höhe:"bis 40 m", Alter:"bis 250 Jahre", Vorkommen:"feuchte Böden, Auen, Mittelland", Merkmal:"schwarze Knospen, Fiederblätter"} },
  { n:"Stieleiche", s:"Quercus robur", lb:["Baum","Blätter","Eicheln","Rinde"],
    q:["Quercus robur leaves","Quercus robur acorns","Quercus robur bark"],
    t:"Die Stieleiche – zusammen mit der ähnlichen Traubeneiche die wichtigste Eiche der Schweiz – trägt ihre Eicheln an langen Stielen, während die gebuchteten Blätter fast ungestielt sind. Die dicke Borke ist tief längsrissig. Kaum ein anderer Baum bietet so vielen Insekten- und Vogelarten Lebensraum.",
    f:{Höhe:"bis 40 m", Alter:"bis 1000 Jahre", Vorkommen:"tiefe Lagen, Mittelland, Tessin", Merkmal:"Eicheln an langen Stielen"} },
  { n:"Arve", s:"Pinus cembra", lb:["Baum","Nadeln","Zapfen","Rinde"],
    q:["Pinus cembra needles","Pinus cembra cones","Pinus cembra bark"],
    t:"Die Arve (Zirbelkiefer) gilt als «Königin der Alpen». Sie trägt fünf weiche Nadeln pro Büschel und erträgt extreme Kälte bis zur Waldgrenze. Die Samen, die Arvennüssli, werden vom Tannenhäher versteckt und so verbreitet. Das duftende Holz wird gerne für Arvenstuben und Möbel verwendet.",
    f:{Höhe:"bis 25 m", Alter:"bis 1000 Jahre", Vorkommen:"Engadin, Wallis, 1500–2500 m", Merkmal:"fünf Nadeln pro Büschel"} }
  ]},

{ id:"straeucher", name:"Sträucher", desc:"Häufige Sträucher in Hecken und an Waldrändern", latin:true, cover:4,
  labels:["Strauch","Blätter","Blüten","Früchte"],
  items:[
  { n:"Hasel", s:"Corylus avellana",
    q:["Corylus avellana leaves","Corylus avellana catkins","Corylus avellana nuts"],
    t:"Die Hasel blüht als einer der ersten Sträucher schon im Februar: Die gelben männlichen Kätzchen verstreuen massenhaft Pollen, die winzigen roten weiblichen Blüten sind kaum zu sehen. Im Herbst reifen die Haselnüsse, die bei Eichhörnchen, Haselmaus und Menschen beliebt sind. Die biegsamen Ruten wurden früher für Zäune und Körbe genutzt.",
    f:{Höhe:"2–6 m", Blütezeit:"Februar–März", Früchte:"Haselnüsse (essbar)", Standort:"Waldränder, Hecken"} },
  { n:"Schwarzer Holunder", s:"Sambucus nigra",
    q:["Sambucus nigra leaves","Sambucus nigra flowers","Sambucus nigra berries"],
    t:"Der Schwarze Holunder wächst gerne in der Nähe von Häusern und auf nährstoffreichen Böden. Im Juni trägt er grosse, weisse, duftende Blütendolden, aus denen Sirup gemacht wird. Die schwarzen Beeren sind roh leicht giftig, gekocht aber essbar und werden zu Gelee oder Saft verarbeitet.",
    f:{Höhe:"3–7 m", Blütezeit:"Mai–Juni", Früchte:"schwarze Beeren (nur gekocht essbar)", Standort:"Waldränder, Siedlungen"} },
  { n:"Weissdorn", s:"Crataegus monogyna",
    q:["Crataegus monogyna leaves","Crataegus monogyna flowers","Crataegus monogyna fruit"],
    t:"Der Eingriffelige Weissdorn ist ein dorniger Strauch mit tief gelappten Blättern. Im Mai ist er über und über mit weissen Blüten bedeckt. Seine roten Früchte sind eine wichtige Winternahrung für Vögel, und in seinen dornigen Zweigen brüten viele Heckenvögel geschützt vor Feinden.",
    f:{Höhe:"2–8 m", Blütezeit:"Mai", Früchte:"rote Steinfrüchte", Merkmal:"Dornen, gelappte Blätter"} },
  { n:"Schwarzdorn (Schlehe)", s:"Prunus spinosa",
    q:["Prunus spinosa leaves","Prunus spinosa flowers","Prunus spinosa fruit sloes"],
    t:"Der Schwarzdorn blüht im März und April, noch bevor seine Blätter erscheinen – dann leuchten ganze Hecken weiss. Die blauen, bereiften Früchte (Schlehen) schmecken erst nach dem ersten Frost weniger herb. Mit Dornen und Ausläufern bildet er dichte Gebüsche, in denen zum Beispiel der Neuntöter brütet.",
    f:{Höhe:"1–3 m", Blütezeit:"März–April", Früchte:"blaue Schlehen", Merkmal:"blüht vor dem Blattaustrieb"} },
  { n:"Hundsrose", s:"Rosa canina",
    q:["Rosa canina leaves","Rosa canina flower","Rosa canina hips"],
    t:"Die Hundsrose ist die häufigste Wildrose der Schweiz. Ihre rosa bis weissen Blüten haben fünf Kronblätter. Aus ihnen entstehen die roten Hagebutten, die viel Vitamin C enthalten und zu Tee oder Konfitüre verarbeitet werden. Die behaarten Samen sind als Juckpulver bekannt.",
    f:{Höhe:"1–3 m", Blütezeit:"Juni", Früchte:"Hagebutten", Merkmal:"hakenförmige Stacheln"} },
  { n:"Roter Hartriegel", s:"Cornus sanguinea",
    q:["Cornus sanguinea leaves","Cornus sanguinea flowers","Cornus sanguinea fruit"],
    t:"Der Rote Hartriegel ist an seinen im Winter blutroten Zweigen gut zu erkennen. Die Blätter haben bogig verlaufende Nerven und färben sich im Herbst weinrot. Die weissen Blütendolden werden von Insekten besucht, die schwarzen Beeren von Vögeln gefressen – für Menschen sind sie ungeniessbar.",
    f:{Höhe:"2–5 m", Blütezeit:"Mai–Juni", Früchte:"schwarze Steinfrüchte (ungeniessbar)", Merkmal:"rote Zweige, bogige Blattnerven"} },
  { n:"Liguster", s:"Ligustrum vulgare",
    q:["Ligustrum vulgare leaves","Ligustrum vulgare flowers","Ligustrum vulgare berries"],
    t:"Der Gewöhnliche Liguster ist ein häufiger Strauch in Hecken und an Waldrändern und wird auch gerne als Gartenhecke gepflanzt. Seine weissen Blütenrispen duften stark. Die glänzend schwarzen Beeren bleiben oft bis in den Winter am Strauch und sind für Menschen giftig.",
    f:{Höhe:"2–5 m", Blütezeit:"Juni–Juli", Früchte:"schwarze Beeren (giftig)", Merkmal:"Blätter oft bis in den Winter grün"} },
  { n:"Pfaffenhütchen", s:"Euonymus europaeus",
    q:["Euonymus europaeus leaves","Euonymus europaeus flowers","Euonymus europaeus fruit"],
    t:"Das Pfaffenhütchen verdankt seinen Namen den leuchtend rosaroten Früchten, die an die Kopfbedeckung eines Priesters erinnern. Beim Aufplatzen zeigen sie orange umhüllte Samen. Alle Teile der Pflanze sind stark giftig. Die grünen Zweige tragen oft vier Korkleisten.",
    f:{Höhe:"2–6 m", Blütezeit:"Mai–Juni", Früchte:"rosarote Kapseln (giftig)", Merkmal:"vierkantige Zweige"} },
  { n:"Wolliger Schneeball", s:"Viburnum lantana",
    q:["Viburnum lantana leaves","Viburnum lantana flowers","Viburnum lantana fruit"],
    t:"Der Wollige Schneeball wächst an trockenen, kalkreichen Waldrändern, etwa im Jura. Blätter und junge Zweige sind filzig behaart. Die Früchte färben sich von Grün über Rot nach Schwarz, sodass oft alle Farben gleichzeitig an einem Fruchtstand zu sehen sind.",
    f:{Höhe:"1–4 m", Blütezeit:"April–Juni", Früchte:"erst rot, dann schwarz (giftig)", Merkmal:"filzige Blätter"} }
  ]},

{ id:"alpenblumen", name:"Alpenblumen", desc:"Blütenpracht über der Waldgrenze", latin:true, cover:0,
  labels:["Pflanze","Blüte","Blätter","Lebensraum"],
  items:[
  { n:"Edelweiss", s:"Leontopodium nivale subsp. alpinum", wp:"Edelweiss",
    q:["Leontopodium alpinum flower close-up","Leontopodium alpinum leaves","Leontopodium alpinum rock"],
    t:"Das Edelweiss ist das bekannteste Symbol der Alpen. Die weissen «Blütensterne» sind eigentlich filzig behaarte Hochblätter; die eigentlichen Blüten sitzen als kleine gelbe Köpfchen in der Mitte. Der dichte Haarfilz schützt vor Austrocknung und starker UV-Strahlung.",
    f:{Blütezeit:"Juli–September", Höhenlage:"1800–3000 m", Standort:"Kalkfelsen, steinige Rasen", Schutz:"in vielen Kantonen geschützt"} },
  { n:"Stängelloser Enzian", s:"Gentiana acaulis",
    q:["Gentiana acaulis flower","Gentiana acaulis leaves","Gentiana acaulis meadow"],
    t:"Der Stängellose Enzian trägt eine grosse, tiefblaue Glockenblüte, die fast direkt aus der Blattrosette wächst. Bei schlechtem Wetter schliesst sich die Blüte. Er wächst auf sauren, kalkarmen Böden; auf Kalk ersetzt ihn der sehr ähnliche Clusius-Enzian.",
    f:{Blütezeit:"Mai–August", Höhenlage:"1200–3000 m", Standort:"Alpweiden, saure Böden", Merkmal:"grosse blaue Glocke"} },
  { n:"Frühlings-Enzian", s:"Gentiana verna",
    q:["Gentiana verna flower","Gentiana verna leaves","Gentiana verna meadow"],
    t:"Der Frühlings-Enzian bildet kleine, leuchtend azurblaue Sternblüten mit fünf Zipfeln. Er gehört zu den ersten Blumen, die nach der Schneeschmelze blühen. Seine Blüten öffnen sich nur bei Sonnenschein.",
    f:{Blütezeit:"März–Juli (je nach Höhe)", Höhenlage:"500–2600 m", Standort:"magere Rasen", Merkmal:"kleine blaue Sternblüte"} },
  { n:"Alpenrose", s:"Rhododendron ferrugineum",
    q:["Rhododendron ferrugineum flowers","Rhododendron ferrugineum leaves","Rhododendron ferrugineum slope"],
    t:"Die Rostblättrige Alpenrose ist ein immergrüner Zwergstrauch, der im Sommer ganze Hänge rosarot färbt. Die Blattunterseite ist rostbraun gefärbt – daher der Name. Sie wächst auf sauren Böden und ist wie alle Rhododendren giftig.",
    f:{Blütezeit:"Juni–August", Höhenlage:"1500–2500 m", Standort:"Zwergstrauchheiden", Merkmal:"rostbraune Blattunterseite"} },
  { n:"Türkenbund", s:"Lilium martagon",
    q:["Lilium martagon flower","Lilium martagon leaves","Lilium martagon meadow"],
    t:"Die Türkenbund-Lilie hat nickende, rosa-violette Blüten mit dunklen Flecken, deren Blütenblätter stark zurückgebogen sind – wie ein Turban. Abends duftet sie stark und lockt Nachtfalter an. Sie wächst in lichten Bergwäldern und Hochstaudenfluren.",
    f:{Blütezeit:"Juni–August", Höhenlage:"bis 2300 m", Standort:"lichte Bergwälder", Schutz:"vielerorts geschützt"} },
  { n:"Silberwurz", s:"Dryas octopetala",
    q:["Dryas octopetala flower","Dryas octopetala leaves","Dryas octopetala seed heads"],
    t:"Die Silberwurz ist ein kriechender Zwergstrauch mit weissen Blüten, die meist acht Kronblätter haben. Nach der Blüte entstehen fedrige, silbrig glänzende Fruchtstände. Mit ihren dichten Teppichen festigt sie Schutthänge auf Kalk.",
    f:{Blütezeit:"Juni–August", Höhenlage:"1200–2500 m", Standort:"Kalkschutt, Felsen", Merkmal:"acht weisse Kronblätter"} },
  { n:"Trollblume", s:"Trollius europaeus",
    q:["Trollius europaeus flower","Trollius europaeus leaves","Trollius europaeus meadow"],
    t:"Die Trollblume trägt kugelige, goldgelbe Blüten, die sich nie ganz öffnen. In ihrem Inneren legen winzige Fliegen ihre Eier ab und bestäuben dabei die Blüte. Sie liebt feuchte Bergwiesen.",
    f:{Blütezeit:"Mai–Juli", Höhenlage:"bis 2500 m", Standort:"feuchte Bergwiesen", Merkmal:"kugelige gelbe Blüte"} },
  { n:"Alpen-Anemone", s:"Pulsatilla alpina",
    q:["Pulsatilla alpina flower","Pulsatilla alpina leaves","Pulsatilla alpina seed head"],
    t:"Die Alpen-Anemone (Alpen-Küchenschelle) blüht kurz nach der Schneeschmelze mit grossen weissen oder – auf sauren Böden – schwefelgelben Blüten. Nach der Blüte bildet sie auffällige, zottige Fruchtstände, die an wirres Haar erinnern.",
    f:{Blütezeit:"Mai–Juli", Höhenlage:"1200–2700 m", Standort:"Alpweiden", Merkmal:"zottige Fruchtstände"} },
  { n:"Alpenglöckchen", s:"Soldanella alpina",
    q:["Soldanella alpina flower","Soldanella alpina leaves","Soldanella alpina snow"],
    t:"Das Alpenglöckchen (Soldanelle) ist berühmt dafür, dass es sich durch die letzte Schneeschicht hindurchschmelzen kann. Seine violetten, fransig eingeschnittenen Glöckchen nicken an dünnen Stielen. Die rundlichen Blätter sind ledrig.",
    f:{Blütezeit:"April–Juli", Höhenlage:"1000–3000 m", Standort:"Schneetälchen", Merkmal:"gefranste Glöckchen"} }
  ]},

{ id:"saeugetiere", name:"Wilde Säugetiere", desc:"Wildtiere in Wald und Gebirge", latin:true, cover:3,
  labels:["Tier","Porträt","Jungtier","Im Winter"],
  items:[
  { n:"Rothirsch", s:"Cervus elaphus",
    q:["Cervus elaphus head","Cervus elaphus calf","Cervus elaphus snow"],
    t:"Der Rothirsch ist das grösste Wildtier der Schweiz. Die Männchen tragen ein mächtiges Geweih, das sie jedes Jahr im Spätwinter abwerfen und neu bilden. In der Brunft im September und Oktober ist ihr lautes Röhren weit zu hören. Grosse Bestände gibt es in Graubünden, etwa im Nationalpark.",
    f:{Schulterhöhe:"bis 1.5 m", Gewicht:"Stier bis über 200 kg", Nahrung:"Gräser, Kräuter, Triebe", Lebensraum:"Wälder, Alpweiden"} },
  { n:"Reh", s:"Capreolus capreolus",
    q:["Capreolus capreolus head","Capreolus capreolus fawn","Capreolus capreolus snow"],
    t:"Das Reh ist der häufigste Hirschartige der Schweiz. Nur der Rehbock trägt ein kleines Geweih. Die Kitze haben weisse Tupfen als Tarnung und liegen in den ersten Wochen reglos im hohen Gras – deshalb werden Wiesen vor dem Mähen abgesucht.",
    f:{Schulterhöhe:"60–80 cm", Gewicht:"15–30 kg", Nahrung:"Knospen, Kräuter, Blätter", Lebensraum:"Waldränder, Felder"} },
  { n:"Gämse", s:"Rupicapra rupicapra",
    q:["Rupicapra rupicapra head","Rupicapra rupicapra kid","Rupicapra rupicapra winter"],
    t:"Die Gämse ist eine hervorragende Kletterin in Fels und steilem Gelände. Männchen und Weibchen tragen hakenförmig gebogene Hörner. Im Sommer ist ihr Fell rötlich-braun, im Winter fast schwarz. Typisch ist die schwarz-weisse Gesichtszeichnung.",
    f:{Schulterhöhe:"70–85 cm", Gewicht:"25–50 kg", Nahrung:"Gräser, Kräuter, Flechten", Lebensraum:"Alpen, Jura"} },
  { n:"Alpensteinbock", s:"Capra ibex",
    q:["Capra ibex head","Capra ibex kid","Capra ibex snow"],
    t:"Der Steinbock war in der Schweiz um 1800 ausgerottet. Ab 1906 wurden Tiere aus dem Gran-Paradiso-Gebiet in Italien wieder angesiedelt – heute leben wieder über 15 000 Steinböcke in der Schweiz. Die Böcke tragen bis zu 1 m lange, geknotete Hörner. Der Steinbock ist das Wappentier von Graubünden.",
    f:{Schulterhöhe:"bis 90 cm", Gewicht:"Bock bis 100 kg", Nahrung:"Gräser, Kräuter", Lebensraum:"Felsgebiete, 1600–3200 m"} },
  { n:"Murmeltier", s:"Marmota marmota",
    q:["Marmota marmota head","Marmota marmota young","Marmota marmota burrow"], lb:["Tier","Porträt","Jungtier","Bau"],
    t:"Das Alpenmurmeltier lebt in Familiengruppen in selbst gegrabenen Bauen auf Alpweiden. Bei Gefahr warnt es mit einem schrillen Pfiff. Von Oktober bis April hält es Winterschlaf, dabei sinkt seine Körpertemperatur auf wenige Grad.",
    f:{Länge:"50–60 cm (ohne Schwanz)", Gewicht:"3–7 kg", Nahrung:"Gräser, Kräuter", Lebensraum:"Alpweiden, 1300–2700 m"} },
  { n:"Rotfuchs", s:"Vulpes vulpes",
    q:["Vulpes vulpes head","Vulpes vulpes cub","Vulpes vulpes snow"],
    t:"Der Rotfuchs ist das häufigste Raubtier der Schweiz und lebt vom Hochgebirge bis mitten in die Städte. Er frisst fast alles: Mäuse, Insekten, Früchte und Abfälle. Mit seinem buschigen Schwanz hält er die Balance und wärmt sich im Winter.",
    f:{Länge:"60–90 cm (ohne Schwanz)", Gewicht:"5–10 kg", Nahrung:"Allesfresser", Lebensraum:"überall, auch in Städten"} },
  { n:"Dachs", s:"Meles meles",
    q:["Meles meles head","Meles meles cub","Meles meles snow"],
    t:"Der Dachs ist an seinem schwarz-weiss gestreiften Kopf leicht zu erkennen. Er lebt in grossen, verzweigten Bauen, die über Generationen genutzt werden, und ist vor allem nachts aktiv. Er frisst viele Regenwürmer, aber auch Insekten, Früchte und Wurzeln.",
    f:{Länge:"65–90 cm", Gewicht:"10–15 kg", Nahrung:"Regenwürmer, Insekten, Früchte", Lebensraum:"Wälder, Hecken"} },
  { n:"Luchs", s:"Lynx lynx",
    q:["Lynx lynx head","Lynx lynx kitten","Lynx lynx snow"],
    t:"Der Luchs ist die grösste Katze Europas. Nach seiner Ausrottung wurde er ab 1971 in der Schweiz wieder angesiedelt und lebt heute vor allem im Jura und in den Nordwestalpen. Typisch sind die Pinselohren und der kurze Stummelschwanz. Er jagt vor allem Rehe und Gämsen.",
    f:{Länge:"80–120 cm", Gewicht:"15–30 kg", Nahrung:"Rehe, Gämsen", Lebensraum:"grosse Wälder"} },
  { n:"Wolf", s:"Canis lupus",
    q:["Canis lupus lupus head","Canis lupus pup","Canis lupus snow"],
    t:"Der Wolf ist 1995 auf natürlichem Weg aus Italien in die Schweiz zurückgekehrt. Heute leben wieder zahlreiche Rudel, vor allem in Graubünden, im Wallis und im Tessin. Ein Rudel ist eine Familie aus den Elterntieren und ihren Jungen. Wegen Angriffen auf Nutztiere sorgt seine Rückkehr für Diskussionen.",
    f:{Schulterhöhe:"60–80 cm", Gewicht:"25–45 kg", Nahrung:"Hirsche, Rehe, Gämsen", Lebensraum:"Alpen, zunehmend Jura"} }
  ]},

{ id:"amphibien", name:"Amphibien", desc:"Frösche, Kröten, Molche und Salamander", latin:true, cover:2,
  labels:["Tier","Nahaufnahme","Nachwuchs","Lebensraum"],
  items:[
  { n:"Grasfrosch", s:"Rana temporaria",
    q:["Rana temporaria close-up","Rana temporaria spawn","Rana temporaria pond"],
    t:"Der Grasfrosch ist der häufigste Frosch der Schweiz und kommt bis über 2500 m vor. Schon im Februar oder März wandert er zu den Laichgewässern und legt grosse Laichballen. Typisch ist der dunkle Fleck hinter dem Auge.",
    f:{Grösse:"7–10 cm", Laichzeit:"Februar–April", Lebensraum:"Wiesen, Wälder, Weiher", Merkmal:"dunkler Schläfenfleck"} },
  { n:"Erdkröte", s:"Bufo bufo",
    q:["Bufo bufo close-up eye","Bufo bufo spawn","Bufo bufo migration"],
    t:"Die Erdkröte hat eine warzige Haut und kupferfarbene Augen mit waagrechter Pupille. Im Frühling wandern tausende Kröten zu ihren Geburtsgewässern – an Strassen helfen Freiwillige mit Amphibienzäunen. Den Laich legt sie in langen Schnüren ab.",
    f:{Grösse:"8–12 cm", Laichzeit:"März–April", Lebensraum:"Wälder, Gärten, grössere Weiher", Merkmal:"Laich in Schnüren"} },
  { n:"Feuersalamander", s:"Salamandra salamandra",
    q:["Salamandra salamandra close-up","Salamandra salamandra larva","Salamandra salamandra forest"],
    t:"Der Feuersalamander ist schwarz mit leuchtend gelben Flecken – eine Warnfarbe, denn seine Haut sondert ein giftiges Sekret ab. Er ist nachtaktiv und zeigt sich vor allem bei Regen. Das Weibchen setzt fertig entwickelte Larven in kühlen Waldbächen ab.",
    f:{Grösse:"15–20 cm", Fortpflanzung:"Larven in Waldbächen", Lebensraum:"feuchte Laubwälder", Gefährdung:"verletzlich"} },
  { n:"Alpensalamander", s:"Salamandra atra",
    q:["Salamandra atra close-up","Salamandra atra juvenile","Salamandra atra alpine"],
    t:"Der Alpensalamander ist ganz schwarz und lebt in den Alpen zwischen etwa 800 und 2800 m. Er braucht keine Gewässer: Das Weibchen bringt nach einer Tragzeit von zwei bis vier Jahren ein bis zwei fertig entwickelte Jungtiere zur Welt.",
    f:{Grösse:"11–15 cm", Fortpflanzung:"lebendgebärend", Lebensraum:"Alpweiden, Bergwälder", Merkmal:"ganz schwarz"} },
  { n:"Bergmolch", s:"Ichthyosaura alpestris",
    q:["Ichthyosaura alpestris male","Ichthyosaura alpestris larva","Ichthyosaura alpestris pond"],
    t:"Der Bergmolch hat einen leuchtend orangen, ungefleckten Bauch. Zur Paarungszeit im Frühling sind die Männchen an den Flanken blau gefärbt und tragen einen niedrigen Rückenkamm. Er ist der häufigste Molch der Schweiz und kommt bis etwa 2500 m vor.",
    f:{Grösse:"8–12 cm", Laichzeit:"März–Juni", Lebensraum:"Tümpel, Weiher, Wälder", Merkmal:"oranger Bauch"} },
  { n:"Laubfrosch", s:"Hyla arborea",
    q:["Hyla arborea close-up","Hyla arborea tadpole","Hyla arborea calling"],
    t:"Der Europäische Laubfrosch ist klein, grasgrün und kann mit den Haftscheiben an seinen Fingern auf Büsche und Bäume klettern. Die Männchen rufen im Chor und sind sehr laut. In der Schweiz ist er stark gefährdet, weil viele seiner sonnigen Laichgewässer verschwunden sind.",
    f:{Grösse:"3–5 cm", Laichzeit:"April–Juni", Lebensraum:"sonnige Weiher, Auen", Gefährdung:"stark gefährdet"} },
  { n:"Gelbbauchunke", s:"Bombina variegata",
    q:["Bombina variegata belly","Bombina variegata tadpole","Bombina variegata puddle"],
    t:"Die Gelbbauchunke ist oben lehmfarben und gut getarnt, der Bauch aber leuchtend gelb-schwarz gefleckt. Bei Gefahr zeigt sie ihn in einer Schreckstellung. Sie laicht in kleinen, oft nur vorübergehend gefüllten Pfützen, etwa in Fahrspuren.",
    f:{Grösse:"4–5 cm", Laichzeit:"Mai–August", Lebensraum:"Kiesgruben, Pfützen", Gefährdung:"stark gefährdet"} },
  { n:"Geburtshelferkröte", s:"Alytes obstetricans",
    q:["Alytes obstetricans close-up","Alytes obstetricans eggs male","Alytes obstetricans tadpole"], lb:["Tier","Nahaufnahme","Mit Eiern","Kaulquappe"],
    t:"Bei der Geburtshelferkröte kümmert sich das Männchen um den Nachwuchs: Es wickelt sich die Eischnüre um die Hinterbeine und trägt sie wochenlang herum, bis die Larven schlüpfbereit sind. Ihr heller Ruf klingt wie ein Glöckchen und brachte ihr den Namen «Glögglifrosch» ein.",
    f:{Grösse:"4–5 cm", Fortpflanzung:"Männchen trägt die Eier", Lebensraum:"Kiesgruben, Steinbrüche", Gefährdung:"stark gefährdet"} },
  { n:"Kammmolch", s:"Triturus cristatus",
    q:["Triturus cristatus male crest","Triturus cristatus larva","Triturus cristatus pond"],
    t:"Der Nördliche Kammmolch ist der grösste Molch der Schweiz. Die Männchen tragen zur Paarungszeit einen hohen, gezackten Rückenkamm. Der Bauch ist gelb bis orange mit schwarzen Flecken. Er braucht grössere, pflanzenreiche Weiher ohne Fische.",
    f:{Grösse:"12–16 cm", Laichzeit:"März–Juni", Lebensraum:"pflanzenreiche Weiher", Gefährdung:"stark gefährdet"} }
  ]},

{ id:"steine", name:"Steine", desc:"Gesteine und Mineralien der Schweiz", latin:false, cover:8,
  labels:["Gestein","Nahaufnahme","Handstück","Vorkommen"],
  items:[
  { n:"Granit", s:"Tiefengestein (magmatisch)", wp:"Granite",
    q:["granite texture close-up","granite rock sample","Grimsel granite"],
    t:"Granit entsteht, wenn Magma tief in der Erdkruste langsam abkühlt. Dabei bilden sich gut sichtbare Kristalle aus Quarz, Feldspat und Glimmer. Granit ist sehr hart und verwittert nur langsam – darum sind Granitlandschaften oft von glatt geschliffenen Felsen geprägt.",
    f:{Bestandteile:"Quarz, Feldspat, Glimmer", Vorkommen:"Grimsel, Gotthard, Bergell", Verwendung:"Pflastersteine, Treppen, Mauern"} },
  { n:"Gneis", s:"Metamorphes Gestein", wp:"Gneiss",
    q:["gneiss texture","gneiss rock sample","gneiss Ticino"],
    t:"Gneis entsteht, wenn Granit oder andere Gesteine bei der Gebirgsbildung unter hohem Druck und hoher Temperatur umgewandelt werden. Typisch ist die streifige, gebänderte Struktur. Gneis ist eines der häufigsten Gesteine der Zentralalpen.",
    f:{Bestandteile:"Quarz, Feldspat, Glimmer (in Lagen)", Vorkommen:"Tessin, Graubünden, Wallis", Verwendung:"Steinplatten, Tessiner Steindächer"} },
  { n:"Kalkstein", s:"Sedimentgestein", wp:"Limestone",
    q:["limestone texture","limestone fossil","Creux du Van"],
    t:"Kalkstein besteht aus Kalk (Calcit), der sich vor Millionen Jahren am Grund warmer Meere abgelagert hat – oft aus Schalen und Skeletten von Meerestieren. Darum findet man darin häufig Fossilien. Mit verdünnter Salzsäure braust Kalk auf.",
    f:{Entstehung:"Ablagerung im Meer", Vorkommen:"Jura, Voralpen (Pilatus, Säntis)", Verwendung:"Zement, Baustein", Merkmal:"enthält oft Fossilien"} },
  { n:"Sandstein (Molasse)", s:"Sedimentgestein", wp:"Sandstone",
    q:["sandstone texture","Molasse sandstone","Bern old town sandstone"],
    t:"Der Molasse-Sandstein besteht aus verkitteten Sandkörnern – Abtragungsschutt der jungen Alpen, der ins Mittelland verfrachtet wurde. Er ist relativ weich und leicht zu bearbeiten. Die Berner Altstadt ist grösstenteils aus grünlich-grauem Sandstein gebaut.",
    f:{Entstehung:"verkitteter Sand", Vorkommen:"Mittelland", Verwendung:"Fassaden, Brunnen, Altstadt Bern", Merkmal:"verwittert relativ schnell"} },
  { n:"Nagelfluh", s:"Sedimentgestein (Konglomerat)", wp:"Conglomerate (geology)",
    q:["Nagelfluh","Nagelfluh close-up","Rigi Nagelfluh"],
    t:"Nagelfluh ist ein Gestein aus runden Kieselsteinen, die durch natürlichen Zement verkittet sind. Die herausragenden Steine erinnern an Nagelköpfe – daher der Name. Sie entstand aus dem Geröll von Urflüssen, die aus den jungen Alpen kamen. Die Rigi besteht zu grossen Teilen aus Nagelfluh.",
    f:{Entstehung:"verkittetes Flussgeröll", Vorkommen:"Rigi, Speer, Napf, Hörnli", Merkmal:"runde Steine im Gestein"} },
  { n:"Schiefer", s:"Metamorphes Gestein", wp:"Slate",
    q:["slate texture","slate rock sample","Landesplattenberg Engi"],
    t:"Schiefer lässt sich entlang feiner Ebenen in dünne Platten spalten. Er entstand aus Ton, der unter Druck verfestigt und umgewandelt wurde. Berühmt ist der Glarner Schiefer vom Landesplattenberg in Engi, der früher für Schiefertafeln und Tischplatten abgebaut wurde und Fischfossilien enthält.",
    f:{Entstehung:"umgewandelter Ton", Vorkommen:"Glarnerland, Wallis", Verwendung:"Dachplatten, Schreibtafeln"} },
  { n:"Marmor", s:"Metamorphes Gestein", wp:"Marble",
    q:["white marble texture","marble rock sample","Peccia marble"],
    t:"Marmor entsteht, wenn Kalkstein durch Hitze und Druck umgewandelt wird. Dabei wachsen die Calcitkristalle zu einem körnigen, oft reinweissen Gestein zusammen. In der Schweiz wird bei Peccia im Maggiatal weisser Marmor abgebaut.",
    f:{Entstehung:"umgewandelter Kalkstein", Vorkommen:"Peccia (Tessin)", Verwendung:"Skulpturen, Böden, Treppen"} },
  { n:"Serpentinit", s:"Metamorphes Gestein", wp:"Serpentinite",
    q:["serpentinite texture","serpentinite rock sample","serpentinite Zermatt"],
    t:"Serpentinit ist ein grünes, oft gesprenkeltes Gestein. Es entstand aus Gestein des Erdmantels, das am Grund eines früheren Ozeans mit Wasser reagierte, und wurde bei der Alpenbildung emporgehoben. Man findet es zum Beispiel rund um Zermatt und bei Davos.",
    f:{Entstehung:"umgewandeltes Mantelgestein", Vorkommen:"Zermatt, Davos, Oberhalbstein", Verwendung:"Ziersteine, Bodenplatten"} },
  { n:"Bergkristall", s:"Mineral (Quarz)", wp:"Quartz",
    q:["rock crystal quartz","quartz crystal cluster Switzerland","Planggenstock"],
    lb:["Kristall","Nahaufnahme","Kristallgruppe","Fundort"],
    t:"Bergkristall ist reiner, klarer Quarz. Er wächst in Klüften – Hohlräumen im Gestein der Alpen – über lange Zeit zu sechseckigen Kristallen heran. Strahler suchen in den Alpen nach solchen Schätzen. Berühmt ist der Fund am Planggenstock (Uri) im Jahr 2005 mit riesigen Kristallgruppen.",
    f:{Härte:"7 (ritzt Glas)", Vorkommen:"Gotthard, Grimsel, Uri", Verwendung:"Schmuck, Sammlerstücke"} }
  ]},

{ id:"graeser", name:"Gräser", desc:"Wiesen- und Ufergräser", latin:true, cover:6,
  labels:["Gras","Blütenstand","Ährchen","Lebensraum"],
  items:[
  { n:"Knaulgras", s:"Dactylis glomerata",
    q:["Dactylis glomerata inflorescence","Dactylis glomerata spikelets","Dactylis glomerata meadow"],
    t:"Das Knaulgras ist eines der wichtigsten Futtergräser. Seine Ährchen sitzen in dichten, einseitigen Knäueln am Ende der Rispenäste – daher der Name. Es bildet kräftige Horste und wächst in Fettwiesen und an Wegrändern.",
    f:{Höhe:"30–120 cm", Blütezeit:"Mai–Juli", Lebensraum:"Fettwiesen, Wegränder", Merkmal:"Ährchen in Knäueln"} },
  { n:"Englisches Raigras", s:"Lolium perenne",
    q:["Lolium perenne inflorescence","Lolium perenne spikelets","Lolium perenne lawn"],
    t:"Das Englische Raigras ist trittfest und wächst schnell nach. Darum ist es wichtig für Weiden, Rasen und Sportplätze. Die Ährchen sitzen abwechselnd und mit der Schmalseite an der Ährenachse. Die Blattunterseite glänzt.",
    f:{Höhe:"10–60 cm", Blütezeit:"Mai–September", Lebensraum:"Weiden, Rasen", Merkmal:"trittfest"} },
  { n:"Wiesen-Fuchsschwanz", s:"Alopecurus pratensis",
    q:["Alopecurus pratensis inflorescence","Alopecurus pratensis spikelets","Alopecurus pratensis meadow"],
    t:"Der Wiesen-Fuchsschwanz blüht als eines der ersten Gräser im Frühling. Seine walzenförmige, weich behaarte Scheinähre erinnert an einen Fuchsschwanz. Er wächst auf feuchten, nährstoffreichen Wiesen.",
    f:{Höhe:"30–100 cm", Blütezeit:"April–Juni", Lebensraum:"feuchte Fettwiesen", Merkmal:"weiche Scheinähre"} },
  { n:"Aufrechte Trespe", s:"Bromus erectus",
    q:["Bromus erectus inflorescence","Bromus erectus spikelets","Bromus erectus dry grassland"],
    t:"Die Aufrechte Trespe ist das typische Gras der artenreichen Trockenwiesen auf Kalkboden, zum Beispiel im Jura. Sie bildet dichte Horste mit aufrechten, oft violett überlaufenen Rispen. In ihren Wiesen wachsen viele Orchideen und leben seltene Schmetterlinge.",
    f:{Höhe:"30–100 cm", Blütezeit:"Mai–Juli", Lebensraum:"Trockenwiesen auf Kalk", Merkmal:"Zeiger für Magerwiesen"} },
  { n:"Wiesen-Lieschgras", s:"Phleum pratense",
    q:["Phleum pratense inflorescence","Phleum pratense spikelets","Phleum pratense meadow"],
    t:"Das Wiesen-Lieschgras (Timothe) hat eine lange, walzenförmige Scheinähre, die sich rau anfühlt – anders als der weiche Fuchsschwanz. Es ist ein wertvolles Futtergras und wird oft angesät. Sein Pollen löst häufig Heuschnupfen aus.",
    f:{Höhe:"30–100 cm", Blütezeit:"Juni–August", Lebensraum:"Wiesen, Weiden", Merkmal:"raue Scheinähre"} },
  { n:"Schilf", s:"Phragmites australis",
    q:["Phragmites australis inflorescence","Phragmites australis panicle close-up","Phragmites australis reed bed lake"],
    t:"Das Schilf ist das grösste einheimische Gras und kann über 3 m hoch werden. Es bildet dichte Röhrichte an Seeufern, die vielen Vögeln Lebensraum bieten und das Ufer vor Wellen schützen. Die Halme wurden früher für Dächer und Matten genutzt.",
    f:{Höhe:"1–4 m", Blütezeit:"Juli–September", Lebensraum:"Seeufer, Sümpfe", Merkmal:"grösstes einheimisches Gras"} },
  { n:"Zittergras", s:"Briza media",
    q:["Briza media inflorescence","Briza media spikelets","Briza media meadow"],
    t:"Das Zittergras hat herzförmige Ährchen an haarfeinen Stielen, die beim leisesten Wind zittern. Es wächst in mageren, ungedüngten Wiesen und zeigt deshalb artenreiches Grünland an.",
    f:{Höhe:"20–50 cm", Blütezeit:"Mai–Juli", Lebensraum:"Magerwiesen", Merkmal:"herzförmige, zitternde Ährchen"} },
  { n:"Gewöhnliches Ruchgras", s:"Anthoxanthum odoratum",
    q:["Anthoxanthum odoratum inflorescence","Anthoxanthum odoratum spikelets","Anthoxanthum odoratum meadow"],
    t:"Das Ruchgras enthält Cumarin und ist für den typischen Duft von frischem Heu verantwortlich. Es blüht früh im Jahr mit einer kurzen, ährenartigen Rispe. Sein Pollen löst oft schon im April Heuschnupfen aus.",
    f:{Höhe:"10–50 cm", Blütezeit:"April–Juni", Lebensraum:"Wiesen, Weiden", Merkmal:"duftet nach Heu"} },
  { n:"Rot-Schwingel", s:"Festuca rubra",
    q:["Festuca rubra inflorescence","Festuca rubra spikelets","Festuca rubra grassland"],
    t:"Der Rot-Schwingel hat feine, borstenförmige Blätter und bildet mit unterirdischen Ausläufern dichte Rasen. Er ist sehr anpassungsfähig und wächst vom Tiefland bis in die Alpen. Oft ist er in Rasensaatmischungen enthalten.",
    f:{Höhe:"20–70 cm", Blütezeit:"Mai–Juli", Lebensraum:"Wiesen, Rasen, Alpweiden", Merkmal:"borstenförmige Blätter"} }
  ]},

{ id:"insekten", name:"Insekten", desc:"Käfer, Falter, Bienen und mehr", latin:true, cover:4,
  labels:["Insekt","Nahaufnahme","Larve","Lebensraum"],
  items:[
  { n:"Honigbiene", s:"Apis mellifera",
    q:["Apis mellifera macro","Apis mellifera brood larvae","Apis mellifera on flower"],
    t:"Die Westliche Honigbiene lebt in Völkern mit bis zu 50 000 Tieren: einer Königin, vielen Arbeiterinnen und im Sommer auch Drohnen. Sie bestäubt viele Obstbäume und Wildpflanzen. Mit dem Schwänzeltanz teilen die Bienen einander mit, wo sich Futterquellen befinden.",
    f:{Grösse:"12–15 mm (Arbeiterin)", Nahrung:"Nektar, Pollen", Lebensweise:"Staat mit einer Königin", Besonderes:"Schwänzeltanz"} },
  { n:"Erdhummel", s:"Bombus terrestris",
    q:["Bombus terrestris macro","Bombus terrestris nest","Bombus terrestris on flower"], lb:["Insekt","Nahaufnahme","Nest","Lebensraum"],
    t:"Die Dunkle Erdhummel ist gross, pelzig und schwarz mit zwei gelben Binden und einem weissen Hinterleibsende. Hummeln fliegen schon bei tiefen Temperaturen, weil sie sich durch Muskelzittern aufwärmen. Nur die jungen Königinnen überwintern und gründen im Frühling ein neues Volk, oft in einem alten Mauseloch.",
    f:{Grösse:"15–25 mm", Nahrung:"Nektar, Pollen", Lebensweise:"einjähriger Staat", Besonderes:"fliegt schon ab ca. 2 °C"} },
  { n:"Siebenpunkt-Marienkäfer", s:"Coccinella septempunctata",
    q:["Coccinella septempunctata macro","Coccinella septempunctata larva","Coccinella septempunctata aphids"],
    t:"Der Siebenpunkt-Marienkäfer ist rot mit sieben schwarzen Punkten – die Zahl der Punkte verrät nicht sein Alter. Käfer und Larven fressen grosse Mengen Blattläuse und sind deshalb im Garten sehr nützlich. Die Käfer überwintern oft in Gruppen.",
    f:{Grösse:"5–8 mm", Nahrung:"Blattläuse", Entwicklung:"Ei – Larve – Puppe – Käfer", Besonderes:"Nützling im Garten"} },
  { n:"Tagpfauenauge", s:"Aglais io",
    q:["Aglais io wings macro","Aglais io caterpillar","Aglais io on flower"], lb:["Falter","Nahaufnahme","Raupe","Lebensraum"],
    t:"Das Tagpfauenauge ist an den vier grossen Augenflecken auf den Flügeln leicht zu erkennen. Sie sollen Feinde wie Vögel erschrecken. Die schwarzen, stacheligen Raupen leben gesellig auf Brennnesseln. Der Falter überwintert in Kellern, Schuppen oder Baumhöhlen.",
    f:{Spannweite:"50–55 mm", Raupenfutter:"Brennnesseln", Flugzeit:"März–Oktober", Besonderes:"überwintert als Falter"} },
  { n:"Schwalbenschwanz", s:"Papilio machaon",
    q:["Papilio machaon macro","Papilio machaon caterpillar","Papilio machaon on flower"], lb:["Falter","Nahaufnahme","Raupe","Lebensraum"],
    t:"Der Schwalbenschwanz ist einer der grössten und schönsten Tagfalter der Schweiz. Die Hinterflügel tragen schwanzartige Fortsätze und einen roten Augenfleck. Die grün-schwarz-orange geringelte Raupe frisst an Doldenblütlern wie Wilder Möhre, Fenchel oder Rüebli.",
    f:{Spannweite:"65–80 mm", Raupenfutter:"Doldenblütler (Möhre, Fenchel)", Flugzeit:"April–September", Besonderes:"schwanzartige Hinterflügel"} },
  { n:"Rote Waldameise", s:"Formica rufa",
    q:["Formica rufa macro","Formica rufa pupae","Formica rufa nest mound"], lb:["Insekt","Nahaufnahme","Puppen","Ameisenhaufen"],
    t:"Die Rote Waldameise baut grosse Hügelnester aus Nadeln und Zweigen, in denen bis zu mehrere hunderttausend Tiere leben. Sie vertilgt viele Schadinsekten und verbreitet Pflanzensamen. Bei Gefahr verspritzt sie Ameisensäure. Waldameisen sind in der Schweiz geschützt.",
    f:{Grösse:"4–9 mm", Nahrung:"Insekten, Honigtau", Lebensweise:"Staat mit mehreren Königinnen", Besonderes:"geschützt"} },
  { n:"Maikäfer", s:"Melolontha melolontha",
    q:["Melolontha melolontha antennae macro","Melolontha melolontha larva grub","Melolontha melolontha oak leaves"], lb:["Käfer","Nahaufnahme","Engerling","Lebensraum"],
    t:"Der Feldmaikäfer erscheint im Mai und frisst an Laubbäumen. Seine Larven, die Engerlinge, leben drei bis vier Jahre im Boden und fressen Wurzeln. Deshalb gibt es in vielen Regionen nur alle drei bis vier Jahre ein grosses «Maikäferjahr». Die Männchen erkennt man an ihren grossen, fächerförmigen Fühlern.",
    f:{Grösse:"20–30 mm", Nahrung:"Laub (Käfer), Wurzeln (Larve)", Entwicklung:"3–4 Jahre im Boden", Besonderes:"Maikäferjahre"} },
  { n:"Blauflügel-Prachtlibelle", s:"Calopteryx virgo",
    q:["Calopteryx virgo male macro","Calopteryx virgo larva","Calopteryx virgo stream"],
    t:"Die Blauflügel-Prachtlibelle schillert metallisch blaugrün; die Männchen haben dunkelblaue Flügel. Sie lebt an sauberen, kühlen Bächen mit Uferpflanzen. Ihre Larven entwickeln sich ein bis zwei Jahre im Wasser und zeigen eine gute Wasserqualität an.",
    f:{Länge:"45–50 mm", Nahrung:"kleine Insekten", Entwicklung:"Larve 1–2 Jahre im Wasser", Besonderes:"zeigt sauberes Wasser an"} },
  { n:"Grünes Heupferd", s:"Tettigonia viridissima",
    q:["Tettigonia viridissima macro","Tettigonia viridissima nymph","Tettigonia viridissima grass"],
    t:"Das Grüne Heupferd ist eine der grössten Heuschrecken der Schweiz. An Sommerabenden hört man es laut zirpen – dazu reibt das Männchen seine Flügel aneinander. Anders als Grashüpfer hat es sehr lange Fühler und frisst neben Pflanzen auch andere Insekten. Das Weibchen trägt einen langen, säbelförmigen Legebohrer.",
    f:{Grösse:"28–42 mm", Nahrung:"Insekten, Pflanzen", Entwicklung:"ohne Puppenstadium", Besonderes:"sehr lange Fühler"} }
  ]},

{ id:"sehenswuerdigkeiten", name:"Sehenswürdigkeiten", desc:"Berühmte Orte der Schweiz", latin:false, cover:0,
  labels:["Ansicht","Detail","Umgebung","Stimmung"],
  items:[
  { n:"Matterhorn", s:"Zermatt, Wallis", wp:"Matterhorn",
    q:["Matterhorn north face","Zermatt Matterhorn village","Matterhorn sunrise"],
    t:"Das Matterhorn ist mit seiner markanten Pyramidenform der bekannteste Berg der Schweiz. Die Erstbesteigung gelang 1865 Edward Whymper und seiner Seilschaft; beim Abstieg stürzten vier von ihnen tödlich ab. Heute versuchen jedes Jahr rund 3000 Alpinisten den Aufstieg.",
    f:{Höhe:"4478 m", Erstbesteigung:"14. Juli 1865", Lage:"Grenze Schweiz–Italien"} },
  { n:"Kapellbrücke", s:"Luzern", wp:"Kapellbrücke",
    q:["Kapellbrücke paintings","Kapellbrücke Wasserturm","Kapellbrücke night"],
    t:"Die Kapellbrücke ist eine gedeckte Holzbrücke über die Reuss und gilt als eine der ältesten erhaltenen Holzbrücken Europas. Im Giebel hängen Bildtafeln aus dem 17. Jahrhundert. 1993 brannte ein grosser Teil ab und wurde wieder aufgebaut. Daneben steht der achteckige Wasserturm.",
    f:{Baujahr:"um 1365", Länge:"rund 200 m", Besonderes:"Bildtafeln, Wasserturm"} },
  { n:"Rheinfall", s:"Neuhausen am Rheinfall, Schaffhausen", wp:"Rhine Falls",
    q:["Rheinfall rock boat","Schloss Laufen Rheinfall","Rheinfall night"],
    t:"Der Rheinfall gilt als grösster Wasserfall Europas. Auf 150 m Breite stürzt der Rhein 23 m in die Tiefe; im Sommer fliessen im Durchschnitt rund 600 m³ Wasser pro Sekunde. Mit dem Boot kann man bis zum Felsen in der Mitte fahren.",
    f:{Höhe:"23 m", Breite:"150 m", Alter:"rund 15 000 Jahre"} },
  { n:"Schloss Chillon", s:"Veytaux, Waadt", wp:"Chillon Castle",
    q:["Chillon Castle courtyard","Chillon Castle Lake Geneva","Chillon Castle winter"],
    t:"Das Schloss Chillon steht auf einer Felseninsel am Ufer des Genfersees. Es wurde über Jahrhunderte von den Grafen von Savoyen ausgebaut und kontrollierte den Weg über die Alpen. Lord Byron machte es mit seinem Gedicht «The Prisoner of Chillon» berühmt. Es gehört zu den meistbesuchten historischen Bauten der Schweiz.",
    f:{"Erste Erwähnung":"1150", Lage:"Genfersee bei Montreux", Besonderes:"Wasserschloss auf Felsinsel"} },
  { n:"Grosser Aletschgletscher", s:"Wallis", wp:"Aletsch Glacier",
    q:["Aletsch Glacier Konkordiaplatz","Aletsch Glacier Eggishorn","Aletsch Glacier autumn"],
    t:"Der Grosse Aletschgletscher ist der grösste und längste Gletscher der Alpen. Er gehört zum UNESCO-Welterbe Schweizer Alpen Jungfrau-Aletsch. Wegen der Klimaerwärmung zieht er sich jedes Jahr um bis zu 50 m zurück.",
    f:{Länge:"rund 20 km", Eisdicke:"bis rund 800 m", Aussichtspunkte:"Eggishorn, Bettmerhorn, Jungfraujoch"} },
  { n:"Zytglogge", s:"Bern", wp:"Zytglogge",
    q:["Zytglogge astronomical clock","Bern old town Kramgasse","Zytglogge night"],
    t:"Der Zytglogge ist ein mittelalterlicher Torturm in der Berner Altstadt, die zum UNESCO-Welterbe gehört. Er diente früher als Stadttor und Gefängnis. Seine astronomische Uhr von 1530 zeigt neben der Zeit auch Tierkreiszeichen und Mondphasen; kurz vor jeder vollen Stunde setzt sich ein Figurenspiel in Bewegung.",
    f:{Baujahr:"um 1220", Uhr:"1530", Besonderes:"Figurenspiel zur vollen Stunde"} },
  { n:"Landwasserviadukt", s:"Filisur, Graubünden", wp:"Landwasser Viaduct",
    q:["Landwasser Viaduct train","Landwasser Viaduct tunnel","Landwasser Viaduct winter"],
    t:"Das Landwasserviadukt ist das Wahrzeichen der Rhätischen Bahn. Die gebogene Steinbrücke ist 65 m hoch und 136 m lang; die Züge fahren direkt in einen Tunnel in der senkrechten Felswand. Die Albulalinie gehört seit 2008 zum UNESCO-Welterbe.",
    f:{Baujahr:"1901–1902", Höhe:"65 m", Länge:"136 m"} },
  { n:"Lavaux", s:"Waadt", wp:"Lavaux",
    q:["Lavaux vineyards terraces","Lavaux grapes Chasselas","Lavaux Lake Geneva autumn"],
    t:"Die Weinbergterrassen des Lavaux ziehen sich am Nordufer des Genfersees zwischen Lausanne und Montreux entlang. Sie wurden im 12. Jahrhundert von Mönchen angelegt. Seit 2007 gehören sie zum UNESCO-Welterbe. Die wichtigste Rebsorte ist der Chasselas.",
    f:{Lage:"zwischen Lausanne und Montreux", "UNESCO-Welterbe":"seit 2007", Rebsorte:"Chasselas"} },
  { n:"Oeschinensee", s:"Kandersteg, Bern", wp:"Oeschinen Lake",
    q:["Oeschinensee boat","Oeschinensee Blüemlisalp","Oeschinensee winter"],
    t:"Der Oeschinensee liegt auf 1578 m am Fuss der Blüemlisalp. Er entstand, als ein gewaltiger Bergsturz das Tal aufstaute. Das türkisblaue Wasser wird von Schmelzwasser gespeist. Der See gehört zum UNESCO-Welterbe Schweizer Alpen Jungfrau-Aletsch.",
    f:{Höhe:"1578 m ü. M.", Entstehung:"Bergsturz", Erreichbar:"Gondelbahn ab Kandersteg"} }
  ]}
];
